<?php
$generalTypes = $this->generalType;
$arrData    = $this->arrData;
?>
<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-group"></i>
        <span class="capitalize">General</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <div class="title-content bg-blue clearfix">
        <h5 class="white bold pull-left capitalize">Add general</h5>
    </div><!-- title-content -->
    <div class="widget-content">
        <form method="post">
            <div id="general" class="general">
                <ul>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Name</h6>
                        <input type="text" name="name" value="<?php echo $arrData['name']; ?>" class="w500">
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Type</h6>
                        <div class="combobox w500 pull-left">
                            <span class="arrow"></span>
                            <select name="type" class="combobox-group bor-raduis4">
                                <?php foreach($generalTypes as $key=>$type){ ?>
                                    <option value="<?php echo $key;?>" <?php if($key == $arrData['type']) { echo "selected";} ?>> <?php echo $type; ?></option>
                                <?php } ?>
                            </select>
                        </div><!-- bombobox -->
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Order</h6>
                        <input type="text" name="sort_order" value="<?php echo $arrData['sort_order']; ?>" class="w500">
                    </li>

                    <li class="clearfix">
                        <h6 class="bold pull-left">Active</h6>
                        <div class="checkbox">
                            <label> Yes <input type="radio" name="active" class="" value="1" <?php if($arrData['active'] == 1) { echo "checked";}?>></label>
                            <label> No <input type="radio" name="active" class="" value="0" <?php if($arrData['active'] == 0) { echo "checked";}?>></label>
                        </div>

                    </li>
                </ul>
                <div class="footer-btn-tab clearfix">
                    <a href="javascript:void(0);" class="back grey bor-raduis4" data-action="back-page">Back</a>
                    <a href="javascript:void(0);" class="save white bor-raduis4 bg-blue" onclick="submitForm(); return false;">Save change</a>
                </div><!--footer-btn-tab-->
            </div><!-- add general -->
        </form>
    </div><!-- widget-content -->
</div><!-- container-content -->
<script type="text/javascript">
    $(function(){
        $('.error-report').remove();

        <?php
        if(!empty($this->arrError)) {
            foreach ($this->arrError as $error) {
                ?>
        var html = '';
        html = '<span class="margin-10 red error-report"><?php echo $error['message']; ?></span>';
        $('[name="<?php echo $error['field']; ?>"]').after(html);
        <?php
            }
        }
    ?>
    });
    function submitForm()
    {
        $('form').submit();
    }
</script>