<?php $actionLog    = $this->actionLog; ?>
<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-group"></i>
        <span class="capitalize">Action Log Detail</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <div class="widget-content">
        <?php if(!is_null($actionLog)){
            $actionLog  = Core_Common::actionLogsProcess($actionLog);
            $accountName    = '<a href="'.BASE_ADMIN_URL.'/user/summary?account_id='.$actionLog['account_id'].'">'.$actionLog['account_name'].'</a>';
            $note = $actionLog['account_name'].' '.$actionLog['sActionName'].' '.$actionLog['note'];
            ?>
            <div class="container-table">
                <div class="table-responsive">
                    <table id="table-content" class="display responsive nowrap table table-hover table-condensed" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th width="7%">ID</th>
                            <th>Time</th>
                            <th>Action</th>
                            <th>Type</th>
                            <th>Object</th>
                            <th>Note</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><?php echo $actionLog['id'];?></td>
                                <td><?php echo date('m-d-Y H:i:s',$actionLog['created']->sec);?></td>
                                <td><?php echo $actionLog['sActionName'];?></td>
                                <td><?php echo $actionLog['sType'];?></td>
                                <td><?php echo $accountName;?></td>
                                <td><?php echo $note;?></td>
                            </tr>
                        </tbody>
                    </table>
                </div><!-- table-responsive -->
            </div><!-- container-table -->
        <?php }else {?>
            <h3 class="txtCenter">No Data</h3>
        <?php }?>
    </div><!-- widget-content -->
</div><!-- container-content -->

