<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-file-o"></i>
        <span class="capitalize">Action Log</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
<!--    <div class="title-content bg-blue clearfix">-->
<!--        <h5 class="white bold pull-left capitalize">Add group</h5>-->
<!--        <ul class="function-header pull-right">-->
<!--            <li>-->
<!--                <a href="--><?php //echo BASE_ADMIN_URL.'/groupmember/add?group_id='.$group['group_id'];?><!--">-->
<!--                    <i class="fa fa-plus"></i>-->
<!--                    <span class="capitalize">add new</span>-->
<!--                </a>-->
<!--            </li>-->
<!--        </ul>-->
<!--    </div><!-- title-content -->
    <div class="widget-content">
        <div class="container-table">
            <div class="table-responsive">
                <table id="table-content" class="display responsive nowrap table table-hover table-condensed" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th width="7%">ID</th>
                        <th>Time</th>
                        <th>Action</th>
                        <th>Type</th>
                        <th>Object</th>
                        <th>Note</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div><!-- table-responsive -->
        </div><!-- container-table -->
    </div><!-- widget-content -->
</div><!-- container-content -->

<script>
    $(document).ready(function() {
        $('#table-content tbody').on('click', 'td', function(e){
            if($(this).index() !=  4)
            {
                var action = $(this).parent('tr').find('td').eq(0).find('a');
                if(typeof action.attr('href') !== 'undefined');
                {
                    hrefRedirect(action);
                }
            }

        });

        $('body').on('click','[data-action="check-all"]',function(){
            var _this = $(this);
            var checkboxItems = $( '[data-action="check-delete"]');
            if(_this.is(':checked'))
                doChecked(checkboxItems,true);
            else
                doChecked(checkboxItems,false);
        });

        var groupTable  = $('#table-content').DataTable( {
            "dom": '<"top" lpf <"clear">>rt<"bottom"ip<"clear">>',
            "processing": true,
            "serverSide": true,
            "bSort":      false,
            "ajax": "<?php echo BASE_ADMIN_URL."/actionlogs/lstactionlogs"; ?>",
            "columns": [
                { "data": "id" },
                { "data": "time" },
                { "data": "actionName" },
                { "data": "typeName" },
                { "data": "accountName" },
                { "data": "note"}
            ]
        } );

    } );
</script>