 <!-- source for popup image slide -->
<link rel="stylesheet" href="<?= $this->static->frontend->css .'/v2/album-detail.css'?>">
<script type="text/javascript" src="<?php echo $this->static->frontend->js . '/feed.js'; ?>"></script> 
<script src="<?= $this->static->frontend->js ;?>/v2/ng-tags-input.min.js"></script>
<script src="<?= $this->static->frontend->js ;?>/v2/contextMenu.js"></script>
  <div class="photowrapper">
    <!-- header-menu-album -->
      <div class="header-menu-album">
          <div class=""><a href="<?= BASE_URL; ?>/photo"><i class="fa fa-long-arrow-left m-r-10" aria-hidden="true"></i>Back to photos</a>
          </div>
          <ul> <li> <a href="javascript:void(0);" onclick="showPopupPhotoPost();"> <span class="a_pt2"><i class="fa fa-image"></i></span> <?php echo $this->locales->photo->addphoto;?> </a> </li> </ul> </div>
    <div class="contain-album">
        <div class="title-page text-center">
            <h4><?php echo $this->albumName; ?></h4>
        </div>
        <div class="contain-photos-detail masonry" data-item="lst-photo">
          
        </div>
        <div class="clearfix"></div>
       <!--  <div class="text-center ajax-loadmore" style="display:none;">
          <i class="fa fa-refresh fa-fw fa-spin"></i> Loading
        </div> -->
        <div class="clearfix"></div>
        <!-- <div class="text-center empty-post" style="display:none;">
          No more images to show...
        </div> -->
        <!--contain-photos-detail-->
    </div>
    <!--end contain album -->
</div>
  <!-- end photowrapper-->


<script>
function deleteComment(comment_id, photo_id, _this)
{
    var _this = $(_this);
    if(confirm('Do you wan to delete ?'))
    {
        $.post(baseurl+'/comment/delete/id/'+comment_id+'/photo_id/'+photo_id,function(response){
            if(response.result){
                _this.parents('[data-item="comment"]').remove();
            }
            else{
                alert(response.message);
            }
        },'json');
    }
}
  $(function(){
     var busyLikePhoto = false;
      $('body').on('click', '[data-action="like-photo"]', function(){
          var _this = $(this);
          var photoId = _this.data('value');
          var isLikeEle = _this.find("[data-item='isLike']");
          if(busyLikePhoto == false){

              busyLike = true;
              var isLike = isLikeEle.val();
              var isResult = 0;

              /*like*/
              if(isLike == 0){
                  $.post(baseurl + "/like/photofeed",{'photo_id': photoId}, function(data){
                      isResult = data.error;
                      _this.find('a').addClass('active');
                      isLikeEle.val("1");//liked
                      busyLikePhoto = false;
                  },'json');

              }else{
                  $.post(baseurl + "/like/unlikephotofeed",{'photo_id': photoId}, function(data){
                      isResult = data.error;
                      _this.find('a').removeClass('active');
                      isLikeEle.val("0");
                      busyLikePhoto = false;
                  },'json');

              }

              if(isResult == 0){
                  //alert("Error Like");
                  return false;
              }
              return true;
          }

      });

      var busy = false;
    var settings = {
      nop     : 5,
      offset  : 1,
      offsetGroupAlbum : 1,
      error   : '<p><?php echo $this->locales->no_more_posts;?></p>',
      delay   : 500,
      scroll  : true
    };


$('body').on('click', 'a[data-action="show-more-album"]', function (e) {
  var _this = $(this);
  var group = _this.data('group');
  var offset = _this.data("offset");
//        showLoading();
  $.post(baseurl + '/album/show-more', {groupId: group, offset: offset}, function (response) {
      if (response.total < <?= ADMIN_PAGE_SIZE - 1 ?>)
          _this.hide();
      if ($.trim(response.html) != '') {
          _this.data("offset", response.offset);
          _this.parents('.contain-photos').find('ul').append($('<div/>').html(response.html).text());

      }
  }, 'json');
});



function getMoreGroup()
{

  var containAlbum    = $('.contain-album');
  var lastContainAlbum    =  containAlbum.eq(containAlbum.length -1);

  $.post(baseurl+'/group/group-album',{offset: settings.offsetGroupAlbum},function(response){
    if(response.html)
    {
      busy = false;
      settings.offsetGroupAlbum = response.offset;
      $.each(response.html, function(index,value){
        lastContainAlbum.after( $('<div/>').html(value).text());
      });
    }else{
      busy = true;
    }
  },'json');

}
});

</script>
<?php echo $this->render('popup_post_photo.phtml');?>
<!-- <div class="md-overlay"></div>             
<nav id="cbp-spmenu-s2" data-item="album-detail" class="contain-add-album cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right project-panel">
  <div class="rmv-pushright pull-right">
    <i class="fa fa-times"></i>
  </div>
  <h3>Create Album</h3>

  <div class="form-group">
    <label for="album-name">Album name</label>
    <input type="text" class="form-control" id="album_name" name="album_name" value="">
  </div>
  <div class="form-group">
    <label for="album-desc">Description</label>
    <textarea rows="1" type="text" class="form-control" id="desc" name="desc" style="resize:none;"></textarea>
  </div>
  <div class="form-group">
    <div id="drop">
    <form id="upload" method="post" action="<?php echo BASE_URL;?>/upload/upload5" enctype="multipart/form-data">
      <input type="file" name="upl" multiple />
    </form>
    </div>
  </div>
  <div class="img-add-album">
    <ul id="imageUploadList" class="clearfix">
    </ul>
  </div>
  <div class="button-group share fr">
    <select name="team_id_to" id="team_id_to">
      <?php 
      foreach ($this->arrGroupMember as $group){?>      
      <option value="<?php echo $group['group_id'];?>"><?php echo $group['group_name'];?></option>         
      <?php }?>
    </select> 
    <button type="button" class="btn btn-success" name="post" value="Post" id="post">Post</button>
    <button class="btn btn-default clear-data-upload"><i class="fa fa-trash"></i></button>
  </div>

</nav> -->
<!-- <link rel="stylesheet" type="text/css" href="<?php echo $this->static->frontend->css . '/upload_style_base.css'; ?>" media="screen">
  <link rel="stylesheet" type="text/css" href="<?php echo $this->static->frontend->css . '/upload_style_image.css'; ?>" media="screen"> -->
  <script type="text/javascript" src="<?php echo $this->static->frontend->js . '/imagesloaded.pkgd.js';?>"></script>
  <script type="text/javascript" src="<?php echo $this->static->frontend->js . '/jquery.knob.js'; ?>"></script>
  <script type="text/javascript" src="<?php echo $this->static->frontend->js . '/jquery.ui.widget.js'; ?>"></script>
  <script type="text/javascript" src="<?php echo $this->static->frontend->js . '/jquery.iframe-transport.js'; ?>"></script>
  <script type="text/javascript" src="<?php echo $this->static->frontend->js . '/jquery.fileupload.js'; ?>"></script>
  <script type="text/javascript" src="<?php echo $this->static->frontend->js . '/jquery.upload.script.js'; ?>"></script>

<script type="text/javascript">
    var imgNames = [];
    var descs = [];  var descs = [];
    var albumDetailEle = $('[data-item="album-detail"]');
    var grid = $('.contain-photos-detail');
        var offset = 0;
        var paramsLoadPhoto = {"offset":offset, "limit": 24, "g_id":<?= $this->groupId ?>, "a_id": <?= $this->albumId ?>,"load_more":true};
        $(window).scroll(function()
        {
            if($(window).scrollTop() == $(document).height() - $(window).height())
            {   
                  paramsLoadPhoto.offset += 1;
                  console.log(paramsLoadPhoto.offset);
                  $.ajax({
                      data: paramsLoadPhoto,
                      method: "POST",
                      url: "/photo/show-more",
                      beforeSend: function () {
                        $('.ajax-loadmore').show();
                      },
                      dataType:'html'
                  }).success(function (data) {
                      grid.append(data);
                  });
            }
        });
        
                               
        function ajaxLoadImage() {
            if(!paramsLoadPhoto.load_more)
            return;

            $.ajax({
                data: paramsLoadPhoto,
                method: "POST",
                url: "/photo/show-more",
                beforeSend: function () {
                  $('.ajax-loadmore').show();
                },
                dataType:'html'
            }).success(function (data) {
                grid.html(data);
            });
      }
      ajaxLoadImage();
// });
        //delete photo
        $('body').on('click', '.fa-deletePhoto', function(){
            if(!confirm('Do you want to delete ?'))
                return;

            var _this = $(this);
            var itemPhoto =  _this.parents('[data-item="photo"]');
            var photoId = [];
            photoId.push(_this.data('value'));
            $.post("<?= BASE_URL.'/api/token/index'; ?>", {'method': 'generateToken'}, function (token) {
                $.post(baseurl + '/api/photo?token='+token+'&method=deletePhotos&photoIds=[' + photoId.join(',') + ']', function (response) {

                    if (response.error)
                        alert(response.message);
                    else {
                        grid.masonry('remove', itemPhoto).masonry();
                    }
                }, 'json');
            });
        });

//hide popup create album
        $(".md-overlay").click(function(){
            $(this).removeClass("md-show");
            $("#cbp-spmenu-s2").removeClass("cbp-spmenu-open");
        });

        $(".rmv-pushright").click(function(){
            imgNames = [];
            descs = [];
            $(".md-overlay").removeClass("md-show");
            $("#cbp-spmenu-s2").removeClass("cbp-spmenu-open");
        });

        $('body').on("click", "#post", function(e){
//loop images
            getImageFile();
            if(imgNames.length > 0){
                var photos = {};
                photos['name'] = albumDetailEle.find("#album_name").val();
                photos['desc'] = albumDetailEle.find("#desc").val();
                photos['team_id_to'] = albumDetailEle.find("#team_id_to").val();
                photos['teamName'] =  albumDetailEle.find('#team_id_to option:selected').text();
                photos['imageNames'] = imgNames;
                photos['descImages'] = descs;

                $.post(baseurl + "/photo/createalbum",{
                    data:JSON.stringify(photos)
                }, function(data){

                    if(data.error == 0){
                        window.location.href = baseurl + '/photo';
                        $(".md-overlay").removeClass("md-show");
                        $("#cbp-spmenu-s2").removeClass("cbp-spmenu-open");
                    }else{
                        alert('create album error');
                    }
                },'json');
            }else{
                alert('please select a Photo');
            }
        });
        function getImageFile(){
            $( "#imageUploadList li" ).each(function( index ) {
                var imageName = $(this).find('img').attr('data-f');
                var desc = $(this).find('textarea').val();
                imgNames.push(imageName);
                descs.push(desc);
            });
        }
    

    //remove image upload
    $(document).on('click','.center-img-album i', function(){
        $(this).closest('li').remove();
    });

    // clear form upload
    $(document).on('click','.clear-data-upload', function(){
        $("input[name='album_name']").val('');
        $("#desc").val('');
        $(".img-add-album").empty();
    });


</script>