<?php
$groupCompanyId = 0;
//echo '<pre>';
//var_dump($this->arrGroupMember[0]['account_id']);
//echo '</pre>';die;
?>
<link rel="stylesheet" href="<?= $this->static->frontend->css.'/v2/photo.css'?>">
<script src="<?= $this->static->frontend->js ;?>/v2/ng-tags-input.min.js"></script>
<script src="<?= $this->static->frontend->js ;?>/v2/contextMenu.js"></script>
<script type="text/javascript">
  var baseurl = "<?= BASE_URL; ?>";
  var baselinkimage = "<?= PATH_IMAGES_URL;?>";
</script>
  <div class="photowrapper">    
    <div class="header-menu-album">
      <div class=""><a href="<?= BASE_URL; ?>/photo"><i class="fa fa-long-arrow-left m-r-10" aria-hidden="true"></i>Back to photos</a></div>
      <ul>
      <?php if($this->isAdmin) {?>
        <li class="create-album-btn m-r-10">
          <a>
            <span class="crt_alb"><i class="fa fa-folder-open"></i></span>
            <?= $this->locales->photo->createalbum;?>
          </a>
        </li>
      <?php } ?>
        <li>
          <a href="javascript:void(0);" onclick="showPopupPhotoPost();">
            <span class="a_pt2"><i class="fa fa-image"></i></span>
            <?= $this->locales->photo->addphoto;?>
          </a>
        </li>
      </ul>
    </div><!-- header-menu-album -->
    <div class="contain-album">
      <div class="title-page text-center">
        <h4><?= $this->locales->company;?></h4>
      </div>
      <div class="contain-photos">
        <ul class="photos clearfix" data-item="lst-album">
          <?php foreach ($this->arrAlbumCompany['data'] as $value) {
              $album = Core_Common::albumProcess($value);
              $groupCompanyId = $album['group_id'];
              ?>
              <li style="position:relative;"  data-item="album">
                  <a href="<?= BASE_URL.'/photo/albumdetail?a_id='.$album['album_id'].'&g_id='. $album['group_id']; ?>">
                      <div class="iframe">
                          <div class="ifram-img-in" >
                              <img  class="img-responsive" src="<?=  $album['image_tag']; ?>" alt="">
                          </div>
                      </div>
                  </a>
                  <div class="_ttPh23"><?= Core_Common::SubFullStrings($album['name'], 0, 50); ?></div>
                  <span class="text-grey"><?= $album['total']; ?> images</span>
                  <?php if($album['isOwner']){?>
                      <i data-action="delete-album" data-value="<?= $album['album_id']; ?>" class="fa fa-times" style="position:absolute;top:5px;right:25px;cursor:pointer;background:#fff;padding:5px;"></i>
                  <?php }?>
              </li>

          <?php } ?>
        </ul>
          <?php if (count($this->arrAlbumCompany['data'])  < $this->arrAlbumCompany['total']) { ?>
              <p class="text-center smbtn" style="padding:20px 0px;">
                  <a data-group="<?= $groupCompanyId; ?>" class="btn showmore-photo"
                     data-offset="1" data-action="show-more-album"
                     href="javascript:void(0);"><?= $this->locales->showmore; ?> <i class="fa fa-angle-double-down"></i></a>
              </p>
          <?php
          } ?>
      </div>
    </div>
    <!-- album team -->
      <?php foreach ($this->arrGroupMember as $keyGroup => $group) {
          $show_more = false;
          $albums = Album::getInstance()->getAlbumList('',0,0,1,$group['group_id'],0,4);
          $total = $albums['total'];
          if ($group['group_type'] != 1 && !empty($albums['data']) ) {
              ?>

              <div class="contain-album">
                  <div class="title-page text-center">
                      <h4><?= ucfirst($group['group_name']); ?></h4>
                  </div>
                  <div class="contain-photos">
                      <ul class="photos" data-item="lst-album">
                          <?php
                          $show_more = true;
                          $groupId = 0;

                          foreach ($albums['data'] as $album) {

                              $album = Core_Common::albumProcess($album);

                              ?>
                              <li data-item="album">
                                  <a href="<?= BASE_URL; ?>/photo/albumdetail?a_id=<?= $album['album_id']; ?>&g_id=<?= $album['group_id']; ?>">
                                      <div class="iframe">
                                          <div class="ifram-img-in">
                                              <img class="img-responsive" src="<?= $album['image_tag']; ?>" alt="">
                                          </div>
                                      </div>
                                  </a>
                                  <div class="_ttPh23"><?= Core_Common::SubFullStrings($album['name'], 0, 50); ?></div>
                                  <span><?= $album['total']; ?>images</span>
                                 <?php if($album['isOwner']){?>
                                  <i data-action="delete-album" data-value="<?= $album['album_id']; ?>" class="fa fa-times" style="position:absolute;top:5px;right:25px;background:#fff;padding:5px;cursor:pointer;"></i>
                                  <?php }?>
                              </li>
                          <?php }
                          ?>
                      </ul>
                      <?php if (count($albums['data']) < $albums['total']) { ?>
                          <p class="text-center">
                              <a data-group="<?= $group['group_id']; ?>" class="btn showmore-photo"
                                 data-offset="1" data-action="show-more-album"
                                 href="javascript:void(0);">Show more <i class="fa fa-angle-double-down"></i></a>
                          </p>
                      <?php } ?>
                  </div>
              </div>
          <?php
          }
      } ?>
          <!-- end album team -->    

<!-- <div class="contain-album">
<div class="title-page">
<h4>Design</h4>
</div>
<div class="contain-photos">
<ul class="photos clearfix">                                	
<li>                                    	
<div class="iframe">  
<div class="ifram-img-in">  
<a href="#">                                        	
<img src="images/popup_photo.jpg" alt="">  
</a>
</div>                                          
</div>
<p>Lorem ipsum dolor sit amet</p>
<span>7 photos</span>
</li>                                         
</ul>
</div>
</div>   
-->
</div>

<script>
    $(function () {

        $('body').on('click', '[data-action="delete-album"]', function(e){
            e.preventDefault();
            if(!confirm('Do you want to delete ?'))
                return;

            var _this = $(this);
            var _val = _this.data('value');
            $.post("<?= BASE_URL.'/api/token/index'; ?>", {'method': 'generateToken'}, function (token) {
                $.post(baseurl + '/api/album?token='+token+'&method=deleteAlbum&album_id=' + _val, function (response) {
                    if (response.error)
                        alert(response.message);
                    else {
                        _this.parents('[data-item="album"]').remove();
                    }
                });
            });

        });

        var busy = false;
        var settings = {
            limit: 4,
            offset: 1,
            offsetGroupAlbum: 1,
            error: '<p><?= $this->locales->no_more_posts;?></p>',
            delay: 500,
            scroll: true,
            groupId: 0
        };
        var Group = [];
        $('body').on('click', 'a[data-action="show-more-album"]', function (e) {
            var _this = $(this);
            _this.prop('disabled',true);
            var group = _this.data('group');
//          var offset = _this.attr("data-offset");
            if(typeof Group[group] === 'undefined'){
                Group[group] = settings;
                Group[group].groupId = group;
                Group[group].offset = 1;
            }
//        showLoading();
            $.post(baseurl + '/album/show-more', Group[group], function (response) {
                _this.prop('disabled',false);
                Group[group].offset = response.offset;
                if (!response.showMore )
                    _this.hide();
                if ($.trim(response.html) != '') {

                    _this.attr("data-offset", response.offset);
                    _this.parents('.contain-photos').find('[data-item="lst-album"]').append($('<div/>').html(response.html).text());

                }

            }, 'json');
        });
//

//  scrolling to get more Group
        $(window).scroll(function () {
// Check the user is at the bottom of the element
            if ($(window).scrollTop() + $(window).height() > $('.photowrapper').height() && !busy) {
// Now we are working, so busy is true
                busy = true;
// Run the function to fetch the data inside a delay This is useful if you have content in a footer you want the user to see.
                setTimeout(function () {
                    getMoreGroup();
                }, settings.delay);

            }
        });

        function getMoreGroup() {
            busy = true;
            return;

//            var containAlbum = $('.contain-album');
//            var lastContainAlbum = containAlbum.eq(containAlbum.length - 1);
//
//            $.post(baseurl + '/group/group-album', {offset: settings.offsetGroupAlbum}, function (response) {
//                if (response.html!='') {
//                    busy = false;
//                    settings.offsetGroupAlbum = response.offset;
////      console.log(settings.offsetGroupAlbum);
//                    $.each(response.html, function (index, value) {
//                        lastContainAlbum.after($('<div/>').html(value).text());
//                    });
//                } else {
//                    busy = true;
//                }
//            }, 'json');

        }
    });

</script>
<?= $this->render('popup_post_photo.phtml');?>
<div class="md-overlay hidden"></div>             
<nav id="cbp-spmenu-s2" data-item="form-add-album" class="contain-add-album cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right project-panel hidden">
  <div class="rmv-pushright pull-right">
    <i class="fa fa-times"></i>
  </div>
  <h3>Create Album</h3>

  <div class="form-group">
    <label for="album-name">Album name</label>
    <input type="text" class="form-control" id="album_name" name="album_name" value="">
  </div>
  <div class="form-group">
    <label for="album-desc">Description</label>
    <textarea rows="1" type="text" class="form-control" id="desc" name="desc" style="resize:none;"></textarea>
  </div>
  <div class="form-group">
    <div id="drop">
      <form id="upload" method="post" action="<?= BASE_URL;?>/upload/upload5" enctype="multipart/form-data">
        <input type="file" name="upl" multiple />
      </form>
    </div>
  </div>
  <div class="img-add-album">
    <ul id="imageUploadList" class="clearfix">
    </ul>
  </div>
  <div class="button-group share fr">
    <select name="team_id_to" id="team_id_to">
      <?php
      foreach ($this->arrGroupMember as $group) {
          if (Core_Common::checkShowGroupCompany($group) && $group['group_name'] != Group::$AllGianty) {
              ?>
              <option value="<?= $group['group_id'];?>"><?= $group['group_name'];?></option>
          <?php }
      }
      ?>
    </select>
    <button type="button" class="btn btn-primary" name="post" value="Post" id="post">Post</button>
    <button class="btn btn-default clear-data-upload"><i class="fa fa-trash"></i></button>
  </div>

</nav>
<!-- <link rel="stylesheet" type="text/css" href="<?= $this->static->frontend->css . '/upload_style_base.css'; ?>" media="screen">
  <link rel="stylesheet" type="text/css" href="<?= $this->static->frontend->css . '/upload_style_image.css'; ?>" media="screen"> -->

  <script type="text/javascript" src="<?= $this->static->frontend->js . '/jquery.knob.js'; ?>"></script>
  <script type="text/javascript" src="<?= $this->static->frontend->js . '/jquery.ui.widget.js'; ?>"></script>
  <script type="text/javascript" src="<?= $this->static->frontend->js . '/jquery.iframe-transport.js'; ?>"></script>
  <script type="text/javascript" src="<?= $this->static->frontend->js . '/jquery.fileupload.js'; ?>"></script>
  <script type="text/javascript" src="<?= $this->static->frontend->js . '/jquery.upload.script.js'; ?>"></script>


<script type="text/javascript">
    var images = [];
    var descs = [];
    var addAlbumEle = $('[data-item="form-add-album"]');


  $(document).ready(function(){

  //show popup create album
  $(".create-album-btn").click(function(){
      $(".md-overlay").addClass("md-show");
      $("#cbp-spmenu-s2").addClass("cbp-spmenu-open");
  });


//hide popup create album
  $(".md-overlay").click(function(){
      $(this).removeClass("md-show");
      $("#cbp-spmenu-s2").removeClass("cbp-spmenu-open");
  });

  $(".rmv-pushright").click(function(){
      images = [];
      descs = [];
      $(".md-overlay").removeClass("md-show");
      $("#cbp-spmenu-s2").removeClass("cbp-spmenu-open");
  });

  $('body').on("click", "#post", function(e){
        //loop images
        getImageFile();
        if(images.length > 0){
          var photos = {};
          photos['name'] = addAlbumEle.find("#album_name").val();
          photos['desc'] = addAlbumEle.find("#desc").val();
          photos['team_id_to'] = addAlbumEle.find("#team_id_to").val();
          photos['teamName'] =  addAlbumEle.find('#team_id_to option:selected').text();
          photos['images'] = images;
          photos['descImages'] = descs;

          $.post(baseurl + "/photo/createalbum",{
            data:JSON.stringify(photos)
          }, function(data){

            if(data.error == 0){
              window.location.href = baseurl + '/photo';
              $(".md-overlay").removeClass("md-show");
              $("#cbp-spmenu-s2").removeClass("cbp-spmenu-open");
            }else{
              AlertFail(data.message);
            }
          },'json');
}else{
  alert('please select a Photo');
}
});
    function getImageFile(){
        images = [];
      $( "#imageUploadList li" ).each(function( index ) {
        var imageName = $(this).find('img').attr('data-f');
        var originalName = $(this).find('img').attr('data-original-name');
        var desc = $(this).find('textarea').val();
          if(typeof imageName === 'undefined')
            return;

        images.push({name:imageName, original_name:originalName});
        descs.push(desc);
      });
    }
  });

//remove image upload
$(document).on('click','.center-img-album i', function(){
  $(this).closest('li').remove();
});
// clear form upload
$(document).on('click','.clear-data-upload', function(){
  $("input[name='album_name']").val('');
  $("#desc").val('');
  $(".img-add-album").empty();
});

if($(window).width() < 415){
  $('.cbp-spmenu-vertical').css({
    'width' : '100%'
  });  
}

</script>