<section class="photo-slider">
       <?php
         if(!empty($this->paginator))
         {
                $index=0;
                foreach ($this->paginator as $value)
                {
                     $classColumn ='';
                      if($index==0)
                      {
                         $classColumn= 'class="first-child"';
                      }

                      $sImageUrl = (!empty($value['image_url'])) ? PATH_NEWS_URL .'/'. $value['image_url'] : '';
                 ?>

                   <article  <?php echo $classColumn;?> style="background-image:url(<?php echo $sImageUrl;?>);">
                        <a href="<?php echo BASE_URL; ?>/photo/list/id/<?php echo $value['album_id']; ?>">
                                <span class="footer">
                                        <span class="name"><?php echo $value['name']; ?></span>
                                        <span class="position">

                                           <?php
                                            if(!empty($value['event_date']) && $value['event_date']>0)
                                            {
                                                  echo date('m/d/Y', $value['event_date']);
                                            } 
                                           ?>
                                        </span>
                                </span>
                        </a>
                    </article>

                <?php
                    $index++;

                }
                ?>

             <script language=javascript">        
               $('.photo-slider').bxSlider({
                        slideWidth: 280,
                        useCSS : false,
                        minSlides: 3,
                        maxSlides: 3,
                        moveSlides: 0,
                        slideMargin: 0,
                        pager : false,
                        infiniteLoop: false,
                        hideControlOnEnd: true
                });
              </script>
        <?php
         }
         ?>
</section>
