<?php
$photos = $this->photos;
$photoIds = $this->photoIds;
?>
<?php
if(!empty($photos)) {
    foreach ($photos as $photo) {
        $photo = Core_Common::photoProcess($photo);
        $likeStatus = ($photo['isLike']) ? 'active' : '';
        ?>
        <div class="item  work-masonry-thumb " data-item="photo">
            <a class="ajaxify" data-photoids="<?= $photoIds ?>"
               href="<?= BASE_URL . '/photo2feed/detail?photo_id=' . $photo['photo_id'] . '&feed_id=' . $photo['feed_id']; ?>">
                <img class="img-responsive" src="<?= $photo['image_tag']; ?>" alt="">

            </a>

            <div class="option-photo">
                <ul>
                    <li  data-action="like-photo" data-value="<?= $photo['photo_id'];?>">
                        <a class="<?= $likeStatus; ?>" href="javascript:void(0);">
                            <i id="like-Click"  class="fa fa-heart"></i>
                        </a>
                        <input type="hidden" data-item="isLike" value="<?= $photo['isLike']; ?>"/>
                    </li>
                    <li><a href="#"><i class="fa fa-share"></i></a></li>
                    <li><a href="#"><i class="fa fa-comment"></i></a></li>
                </ul>
            </div>
            <?php if($photo['isOwner'] || Core_Common::checkOwnerOfObject($this->album, $this->arrLogin['accountID'])){?>
                <i data-value="<?= $photo['photo_id']; ?>" data-item="delete-photo" class="fa fa-times fa-deletePhoto" style="position:absolute; top:0; right:0;background:#fff;padding:5px;cursor:pointer;"></i>
            <?php } ?>
        </div>
    <?php
    }
}
?>