<?php if (!empty($this->arrAccountInfo)): ?>
        <div class="asideCont clearfix" id="_jsListUser">
            <div class="bgTitlef9f9f9 titleReport">ACCOUNT DETAIL
                <div class="floatright clear">
                    <a href="javascript:void(0)" onClick="window.history.back();" class="button gray">[Back]</a>
                </div>
            </div>
            <div class="width100Pec floatleft clear  ">
                <div class="floatright mBot5 mTop5 padLefRig20" style="padding-right:15px;">
                    <a href="<?php echo BASE_ADMIN_URL; ?>/index/upd?id=<?php echo $this->arrAccountInfo['account_id']; ?>&update=1" class="button gray">UPDATE</a>
                    <a href="javascript:void(0);" class="button gray" id="btnDelete" rel="<?php echo $this->arrAccountInfo['account_id']; ?>">DELETE</a>
                </div>
            </div>
            <table width="100%" cellspacing="0" cellpadding="0" border="1" class="tblComm tblListCont">
                <tbody>
                     <tr>
                            <th align="left">Name</th> 
                            <td align="left"><?php echo $this->arrAccountInfo['name']; ?></td>
                        </tr>
                        <tr>
                            <th align="left">Email</th> 
                            <td align="left"><?php echo $this->arrAccountInfo['email']; ?></td>
                        </tr>
                        <tr>
                            <th align="left">GNT ID</th> 
                            <td align="left"><?php echo $this->arrAccountInfo['id']; ?></td>
                        </tr>
                        <tr>
                            <th align="left">Skype (Account/Password)</th> 
                            <td align="left"><?php echo $this->arrAccountInfo['skype_account']; ?></td>
                        </tr>
                      
                        
                        
                         <?php $sImageUrl = (!empty($this->arrAccountInfo['picture'])) ? PATH_AVATAR_URL .'/'. $this->arrAccountInfo['picture'] : ''; ?>
                        <tr>
                            <th align="left">Picture</th>
                            <td align="left">
                                <?php if(!empty($sImageUrl)): ?>
                                    <img src="<?php echo $sImageUrl; ?>" border="0" />
                                <?php else: ?>
                                <img src="<?php echo PATH_AVATAR_URL;?>/avatar_default.jpg" width="75px" />
                                <?php endif; ?>
                            </td>
                        </tr>
                        <tr> 
                            <th align="left">Position</th>
                            <td align="left"><?php echo isset($this->arrGeneralAttHash[$this->arrAccountInfo['position']])?$this->arrGeneralAttHash[$this->arrAccountInfo['position']]:'';?></td>
                        </tr>
                        <tr> 
                            <th align="left">Team</th>
                            <td align="left"><?php echo isset($this->arrGroupName[$this->arrAccountInfo['team_id']]['group_name'])?$this->arrGroupName[$this->arrAccountInfo['team_id']]['group_name']:'';?></td>
                        </tr>
                          <tr> 
                            <th align="left">Leader</th>
                            <td align="left">
                                <?php 
                                if(!empty($this->arrAccountManager[$this->arrAccountInfo['leader_id']]['name']))
                                {
                                 ?>
                                   <a href="<?php echo BASE_ADMIN_URL; ?>/index/detail?id=<?php echo $this->arrAccountInfo['leader_id'];?>"><?php echo  $this->arrAccountManager[$this->arrAccountInfo['leader_id']]['name'];?></a>
                                <?php
                                }
                          
                               ?></td>
                        </tr>
                       
                        <tr> 
                            <th align="left">Manager</th>
                            <td align="left">
                                <?php 
                                if(!empty($this->arrAccountManager[$this->arrAccountInfo['manager_id']]['name']))
                                {
                                 ?>
                                   <a href="<?php echo BASE_ADMIN_URL; ?>/index/detail?id=<?php echo $this->arrAccountInfo['manager_id'];?>"><?php echo  $this->arrAccountManager[$this->arrAccountInfo['manager_id']]['name'];?></a>
                                <?php
                                }
                          
                               ?></td>
                        </tr>
                        
                        <tr> 
                            <th align="left">Direct Manager</th>
                            <td align="left">
                                <?php 
                                if(!empty($this->arrAccountManager[$this->arrAccountInfo['manager_id']]['name']))
                                {
                                 ?>
                                   <a href="<?php echo BASE_ADMIN_URL; ?>/index/detail?id=<?php echo $this->arrAccountInfo['manager_id'];?>"><?php echo  $this->arrAccountManager[$this->arrAccountInfo['manager_id']]['name'];?></a>
                                <?php
                                }
                          
                               ?></td>
                        </tr>
                      
                        <tr> 
                            <th align="left">Birthday</th>
                            <td align="left"><?php echo $this->arrAccountInfo['birthday'];?></td>
                        </tr>
                         <tr> 
                            <th align="left">Phone</th>
                            <td align="left"><?php echo $this->arrAccountInfo['phone'];?></td>
                        </tr>
                       
                        <tr> 
                            <th align="left">Tax Code</th>
                            <td align="left"><?php echo $this->arrAccountInfo['tax_code'];?></td>
                        </tr>
                     
                      
                      
                        <tr> 
                            <th align="left">Contract Type</th>
                            <td align="left"><?php echo isset($this->arrGeneralAttHash[$this->arrAccountInfo['contract_type']])?$this->arrGeneralAttHash[$this->arrAccountInfo['contract_type']]:'';?></td>
                        </tr>
                        <tr> 
                            <th align="left">Contract Sign Date</th>
                            <td align="left"><?php echo $this->arrAccountInfo['contract_sign_date'];?></td>
                        </tr>
                        <tr> 
                            <th align="left">Start Date</th>
                            <td align="left"><?php echo $this->arrAccountInfo['start_date'];?></td>
                        </tr>
                        
                         <tr> 
                            <th align="left">Address</th>
                            <td align="left"><?php echo $this->arrAccountInfo['address'];?></td>
                        </tr>
                        
                        <tr> 
                            <th align="left">Country</th>
                            <td align="left"><?php echo isset($this->arrCountry[$this->arrAccountInfo['country_id']])?$this->arrCountry[$this->arrAccountInfo['country_id']]:'';?></td>
                        </tr>
                        <tr> 
                            <th align="left">About me</th>
                            <td align="left"><?php echo $this->arrAccountInfo['description'];?></td>
                        </tr>
                        <?php
                          if(!empty($this->arrAccountExtra))
                          {
                              foreach($this->arrAccountExtra as $value)
                              {
                              ?>
                        
                                <tr> 
                                   <th align="left"><?php echo $value['attribute_name'];?></th>
                                   <td align="left"><?php echo $value['attribute_value'];?></td>
                               </tr>
                        
                              <?php
                              }
                              
                          }
                          ?>

                </tbody>
            </table>
        </div>
        <script type="text/javascript">
            function popupwindow(url, title, w, h) {
                var left = (screen.width/2)-(w/2);
                var top = (screen.height/2)-(h/2);
                return window.open(url, title, 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);
            }
            
            $("#btnDelete").click(function() {
                var id = $(this).attr('rel');

                if(id)
                {
                    if(confirm('Are you sure want to delete this account?'))
                    {
                        $.post("<?php echo BASE_ADMIN_URL; ?>/index/delete",{ id: id },function(result){
                            if(result.error == 0)
                            {
                                 window.location= '<?php echo BASE_ADMIN_URL; ?>/index/index/page/<?php echo $this->iPage;?>';
                            }
                            else
                            {
                                alert(result.message);
                            }
                        },'json');
                    }
                }
            });
        </script>
    <?php else: ?>
       
    <?php endif; ?>
