<style>
    .addname-admin{
        list-style: none;
        margin: 10px;
    }
    
    .row-new-group .member-new-group {
        width: 300px;
        text-align: left;
        margin-left: 250px;
        margin-top: 5px;
    }
</style>
<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-group"></i>
        <span class="capitalize">Admin</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <div class="title-content bg-blue clearfix">
        <h5 class="white bold pull-left capitalize">Add Admin</h5>
    </div><!-- title-content -->
    <div class="widget-content">
        <form method="post" id="frmAddAdmin">
            <div id="general" class="general">
                <ul>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Name</h6>
                        <input type="text" name="user_name" value="" class="w500" data-autocomplete="member" id="user_name">
                        <div id="member-display" style="display:none;" data-autocomplete="result-member">
                            <ul class="tags-staff popup-new-group" >
                            </ul>
                            <div class="member-add-group">
                            </div>
                        </div>
                        
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">ID</h6>
                        <input type="text" name="id" value="" class="w500"  id="account_id">
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Mail</h6>
                        <input type="text" name="mail" value="" class="w500"  id="account_mail">
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Team</h6>
                        <div class="combobox w500 pull-left">
                            <span class="arrow"></span>
                            <select name="team_id" class="combobox-group bor-raduis4" id="team_id">
                                <?php foreach($this->arrGroup['data'] as $group){
                                    ?>
                                <option value="<?php echo $group['group_id']; ?>" ><?php echo $group['group_name']; ?></option>
                                <?php } ?>
                            </select>
                        </div><!-- bombobox -->
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Role</h6>
                        <div class="combobox w500 pull-left">
                            <span class="arrow"></span>
                            <select name="role_id" class="combobox-group bor-raduis4">
                                <?php foreach ($this->arrRolesList as $role):?>
                                <option value="<?php echo $role['_id']->{'$id'} ?>" ><?php echo $role['name'] ?></option>
                                <?php endforeach;?>
                            </select>
                        </div><!-- bombobox -->
                    </li>
                    
                </ul>
                <div class="footer-btn-tab clearfix">
                    <a href="javascript:void(0);" class="back grey bor-raduis4" data-action="back-page">Back</a>
                    <a href="javascript:void(0);" class="save white bor-raduis4 bg-blue" onclick="submitAddAdminForm(); return false;">Add</a>
                </div><!--footer-btn-tab-->
            </div><!-- add group -->
        </form>
    </div><!-- widget-content -->
</div><!-- container-content -->
<script>
    var lgAccountIds = []; //list account id
    $(function(event) {
        var container = $("#member-display");
        $('body').click(function(e) {
            if (!container.is(event.target) // if the target of the click isn't the container...
                && container.has(event.target).length === 0) // ... nor a descendant of the container
            {
                container.hide();
            }
        });


        $('body').on('input propertychange paste', '[data-autocomplete="member"]', function(e) {
            var _this = $(this);
            var _val = $.trim($(this).val());

            var _html = '<li class="clearfix">No Data</li>';
            var resultPlace = _this.parent().find('[data-autocomplete="result-member"]');

            if (_val == '') {
                resultPlace.hide();
                return;
            }
            var params = {};
            params['key'] = _val;
            params['team'] = '';

            $.post("<?php echo BASE_ADMIN_URL.'/user/searchuser'; ?>", {
                data: JSON.stringify(params)
            }, function(data) {
                if (data.total > 0) {
                    _html = '';
                    $.each(data['data'], function(index, account) {
                        _html += suggesstionLI(account, 'add-user-to-admin');
                    });
                }
                resultPlace.find('ul').html(_html);
                resultPlace.show();

            }, 'json');
        });

        //set user info to form
        $('body').on('click', '.add-user-to-admin', function(e) {

            var account_id = $(this).attr('data-aId');
            var name = $(this).attr('data-name');
            var email = $(this).attr('data-email');
            var team_id = $(this).attr('data-team-id');

            $('#user_name').val(name);
            $('#account_id').val(account_id);
            $('#account_mail').val(email);

            //call ajax to set team_id to team list
            $.ajax({
                  method: "POST",
                  url: "<?php echo BASE_ADMIN_URL.'/admin/get-team-name-by-team-id'; ?>",
                  data: { "team-id": team_id}
                })
                  .done(function( response ) {
                      var objResponse = jQuery.parseJSON(response);
                      if (objResponse.total > 0){
                        $('#team_id').val(objResponse.data.group_id);
                     }
                  });
              
        });

        function suggesstionLI(account, class_name) {

            var li = '<li class="' + class_name + '" data-aId="' + account.account_id + '" data-name="' + account.name + '"'
                     + ' data-email ="' + account.email + '" data-team-id ="' + account.team_id + '">' +
                '<a href="javascript:void(0);">' +
                '<div class="inform-tags-members clearfix">' +
                '<div class="img-tags-members mg10 fl">' +
                '<img alt="'+ account.name +'" width="36" src="' + account.image_tag + '">' +
                ' <strong> ' + account.name + ' </strong> ' +
                ' <span> ' + account.position_name + ' </span> ' +
                '</div>' +
                '</div>' +
                '</a>' +
                '</li>';
            return li;
        }

        function removeArray(arr, number) {
            for (var i = arr.length - 1; i >= 0; i--) {
                if (arr[i] === number) {
                    arr.splice(i, 1);
                }
            }
            return arr;
        }

        function checkExistsArray(arr, value) {
            for (var i = arr.length - 1; i >= 0; i--) {
                if (arr[i] === value) {
                    return true;
                }
            }
            return false;
        }
    });
    
    function submitAddAdminForm() {
        $('#frmAddAdmin').submit();
    }
</script>