
<style>
    .addname-admin{
        list-style: none;
        margin: 10px;
    }
    ul.tags-staff, .cmt ul.tags-staff {
        position: absolute;
        left: 341px;
        background-color: #fff;
        border: 1px solid #999;
        margin: 2px 0;
        z-index: 9999;
        width:  498px;
    }
    .row-new-group .member-new-group {
        width: 300px;
        text-align: left;
        margin-left: 250px;
        margin-top: 5px;
    }
</style>
<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-group"></i>
        <span class="capitalize">Admin</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <div class="title-content bg-blue clearfix">
        <h5 class="white bold pull-left capitalize">Create Role</h5>
    </div><!-- title-content -->
    <div class="widget-content">
        <form action="<?php echo BASE_ADMIN_URL; ?>/admin/create-role" method="post">
            <div id="general" class="general">
                <ul>
                	<li class="clearfix">
                        <div class="bold">
                        	<?php echo $this->sError;?>
                        	<?php echo $this->sSuccess;?>
                        </div>

                    </li>
                    
                    <li class="clearfix">
                        <h6 class="bold pull-left">Role Name</h6>
                        <input type="text" name="name" value="<?php echo $this->sName;?>" class="w500">
                    </li>
                   

                    <li class="clearfix">
                        <h6 class="bold pull-left">Active</h6>
                        <div class="checkbox">
                            <label> Yes <input type="radio" name="active" class="" value="1" <?php echo "checked";?>></label>
                            <label> No <input type="radio" name="active" class="" value="0"></label>
                        </div>

                    </li>
                </ul>
                
                <div>
 
                    <fieldset>
                        <?php
                        foreach ($this->arrFullPermission as $controller => $value) {

                                if (!empty($value['action'])) {
                                    ?>
                                    <div class="input_div">
                                        <input id="permission_<?php echo $controller; ?>" class="per_title" style="display: none;" type="checkbox">
                                        <label for="permission_<?php echo $controller; ?>" style="cursor: pointer; font-weight: bolder;"><?php echo $value['name'] ?></label>

                                        <table style="border:none; border-collapse: collapse">
                                            <?php
                                            $keys = array();
                                            foreach ($value['action'] as $action => $per) {

                                                $key = $per['value'];

                                                if (!in_array($key, $keys)) {
                                                    array_push($keys, $key);

                                                    $checked = isset($this->arrPermission[$controller]) && ($this->arrPermission[$controller] & $key) ? "checked" : "";
                                                    ?>
                                                    <tr>
                                                        <td valign="middle" style="border-width: 0px;">
                                                            <input style="width: 20px" id="permission_<?php echo $controller . ':' . $action; ?>" class="input_data" type="checkbox" name="<?php echo $controller ?>[]" value="<?php echo $key ?>"  <?php echo $checked ?>  >
                                                        </td>
                                                        <td valign="middle" style="border-width: 0px;">
                                                            <label for="permission_<?php echo $controller . ':' . $action; ?>" style="margin-left: 10px; cursor: pointer"><?php echo $per['name'] ?></label>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </table>            
                                    </div>
                                    <?php
                                }
                            
                        }
                        ?>
                    </fieldset>
				
        		</div>
                
                <div class="footer-btn-tab clearfix">
                    <a href="javascript:void(0);" class="back grey bor-raduis4" data-action="back-page">Back</a>
                    <a href="javascript:void(0);" class="save white bor-raduis4 bg-blue" onclick="submitForm(); return false;">Save change</a>
                </div><!--footer-btn-tab-->
            </div><!-- add group -->
        </form>
    </div><!-- widget-content -->
</div><!-- container-content -->

<script type="text/javascript">
    
function submitForm(){
    $('form').submit();
}
</script>
