<style>
    .addname-admin{
        list-style: none;
        margin: 10px;
    }
    ul.tags-staff, .cmt ul.tags-staff {
        position: absolute;
        left: 341px;
        background-color: #fff;
        border: 1px solid #999;
        margin: 2px 0;
        z-index: 9999;
        width:  498px;
    }
    .row-new-group .member-new-group {
        width: 300px;
        text-align: left;
        margin-left: 250px;
        margin-top: 5px;
    }
</style>
<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-group"></i>
        <span class="capitalize">Admin</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <div class="title-content bg-blue clearfix">
        <h5 class="white bold pull-left capitalize">Update Admin</h5>
    </div><!-- title-content -->
    <div class="widget-content">
        <form action="<?php echo BASE_ADMIN_URL; ?>/admin/edit" method="post">
            <div id="general" class="general">
                <ul>
                	<li class="clearfix">
                        <div class="bold">
                        	<?php echo $this->sError;?>
                        </div>

                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Name</h6>
                        <input type="text" readonly name="user_name" value="<?php echo $this->arrAccountInfo['name'];?>" class="w500" data-autocomplete="member" id="user_name">
                        <div id="member-display" style="display:none;min-height: 700px;" data-autocomplete="result-member">
                            <ul class="tags-staff popup-new-group" >
                            </ul>
                            <div class="member-add-group">
                            </div>
                        </div>
                        
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">ID</h6>
                        <input type="text" readonly name="id" value="<?php echo $this->arrAccountInfo['id'];?>" class="w500"  id="account_id">
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Mail</h6>
                        <input type="text" readonly name="email" value="<?php echo $this->arrAccountInfo['email'];?>" class="w500"  id="account_mail">
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Team</h6>
                        <input type="text" readonly name="team_name" value="<?php echo $this->arrAccountInfo['team_name'];?>" class="w500"  id="team_name">
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Role</h6>
                        <div class="combobox w500 pull-left">
                            <select id="role" class="combobox-group bor-raduis4" name="role">
                            <?php
                            $checked = '';
                             foreach ($this->arrRole as $role){
								 if($role['_id'] == $this->arrAdmin['role_id']){
								 	$checked = 'selected';
                                 }else{
									$checked = '';	
								 }?>
                                    <option value="<?php echo $role['_id'];?>" <?php echo $checked;?>><?php echo $role['name'];?></option>
                           <?php }?>                                        
                           </select>
                        </div><!-- bombobox -->
                    </li>
                    
                </ul>
                <div class="footer-btn-tab clearfix">
                    <a href="javascript:void(0);" class="back grey bor-raduis4" data-action="back-page">Back</a>
                    <a href="javascript:void(0);" class="save white bor-raduis4 bg-blue" onclick="submitForm(); return false;">Save change</a>
                </div><!--footer-btn-tab-->
            </div><!-- add group -->
            <input type="hidden" value="<?php echo $this->arrAdmin['admin_id'];?>" id="admin_id" name="admin_id">
        </form>
    </div><!-- widget-content -->
</div><!-- container-content -->
<script>
    

    function submitForm(){
        $('form').submit();
    }

    
</script>