<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-user"></i>
        <span class="capitalize">User</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <div class="title-content bg-blue clearfix">
        <h5 class="white bold pull-left capitalize">User List</h5>
        <ul class="function-header pull-right">
            <li>
                <a href="<?php echo BASE_ADMIN_URL.'/user/exporttoexcel'?>">
                    <i class="fa fa-file-text-o"></i>
                    <span class="capitalize">export</span>
                </a>
            </li>
            <li>
                <a href="<?php echo BASE_ADMIN_URL.'/admin/add-admin'?>">
                    <i class="fa fa-plus"></i>
                    <span class="capitalize">add new</span>
                </a>
            </li>
            <li>
                <a href="<?php echo BASE_ADMIN_URL.'/admin/manage-role'?>">
                    <i class="fa fa-plus"></i>
                    <span class="capitalize">manage role</span>
                </a>
            </li>
        </ul>
    </div><!-- title-content -->
    <div class="widget-content">
        <div class="container-table">
            <div class="table-responsive">
                <table id="table-content" class="display responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th width="7%">ID</th>
                        <th>Family name</th>
                        <th>Name</th>
                        <th>Mail</th>
                        <th>Avatar</th>
                        <th>Team</th>
                        <th>Role Name</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
    
                    </tbody>
                </table>
            </div><!-- table-responsive -->
        </div><!-- container-table -->
    </div><!-- widget-content -->
</div><!-- container-content -->

<div data-hidden="role-type" style="display: none;">
    <select data-action="search-by-type" name="role-type">
        <option value="">---------</option>
        <?php foreach($this->arrRole as $id => $name) { ?>
            <option value="<?php echo $id?>"><?php echo $name?></option>
        <?php } ?>
    </select>
</div>

<script>
    $(document).ready(function() {

        $('#table-content tbody').on('click', 'td', function(e){
            if($(this).index() != 7)
            {
                var action = $(this).parent('tr').find('td').eq(1).find('a');
                if(typeof action.attr('href') !== 'undefined');
                {
                    hrefRedirect(action);
                }
            }

        });

    	var groupTable  = $('#table-content').DataTable( {
    		"dom": '<"top"<"margin-10 pull-left delete-ids">l <"margin-10 role-type"> pf <"clear">>rt<"bottom"ip<"clear">>',
            "lengthChange": false,
            "processing": true,
            "serverSide": true,
            "bSort":      false,
            "ajax": "<?php echo BASE_ADMIN_URL."/admin/list"; ?>",
            "columns": [
                { "data": "id" },
                { "data": "firstName" },
                { "data": "lastName" },
                { "data": "email" },
                { "data": "avatar" },
                { "data": "team" },
                { "data": "roleName" },
                { "data": "actions" }
            ]
        } );

    	$("div.role-type").prepend($('[data-hidden="role-type"]').html());
        $('[role-hidden="role-type"]').remove();
        

     // Apply the search
        groupTable.columns(0).every( function () {
            var that = this;
            $( '[data-action="search-by-type"]').on( 'change', function () {
                //console.log(that);
                that
                    .search(this.value)
                    .draw();
            } );
        } );

        //delete admin
        $('body').on('click','[data-action="group-delete"]', function(){
            if(confirm('Do you want to delete ?'))
            {

                var _this = $(this);
                var id = _this.attr('data-value');
                $.post("<?php  echo BASE_ADMIN_URL.'/admin/delete'; ?>",{'admin_id':id}, function(data){
                    if(data.error)
                    {
                        alert(data.message);
                    }
                    else{
                        groupTable
                            .row( _this.parents('tr') )
                            .remove()
                            .draw();
                    }

                },'json');
            }
        });

    });
</script>