<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';


$GLOBALS['gnt_mobion_feed_E_GroupType'] = array(
  'Friends' => 0,
  'Followings' => 1,
  'Followers' => 2,
  'FollowAll' => 3,
);

final class GroupType {
  const Friends = 0;
  const Followings = 1;
  const Followers = 2;
  const FollowAll = 3;
  static public $__names = array(
    0 => 'Friends',
    1 => 'Followings',
    2 => 'Followers',
    3 => 'FollowAll',
  );
}

$GLOBALS['gnt_mobion_feed_E_AppType'] = array(
  'MbSNS' => 0,
  'MbForum' => 1,
  'MbMusic' => 2,
);

final class AppType {
  const MbSNS = 0;
  const MbForum = 1;
  const MbMusic = 2;
  static public $__names = array(
    0 => 'MbSNS',
    1 => 'MbForum',
    2 => 'MbMusic',
  );
}

?>
