<div class="profile-settingwrapper">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#sectionA" style="border-radius:0px;"><?= $this->locales->profileSetting->profileSetting ?></a></li>
    </ul>
    <div class="tab-content">
        <div id="sectionA" class="tab-pane fade in active">
            <form method="post">
                <input type="hidden" name="tab" value="profile-setting" />
                <h4><?= $this->locales->profileSetting->language ?></h4>
                <div class="radio">
                    <input type="radio" value="<?= LANGUAGE_VI ?>" name="language" id="lang-vi"<?= Core_Helper::getSelectedLanguage($this->language, LANGUAGE_VI) ?>><label for="lang-vi"><?= $this->locales->profileSetting->vietnamese ?></label>
                </div>
                <div class="radio">
                    <input type="radio" value="<?= LANGUAGE_EN ?>" name="language" id="lang-en"<?= Core_Helper::getSelectedLanguage($this->language, LANGUAGE_EN) ?>><label for="lang-en"><?= $this->locales->profileSetting->english ?></label>
                </div>
                <div class="radio">
                    <input type="radio" value="<?= LANGUAGE_JP ?>" name="language" id="lang-ja"<?= Core_Helper::getSelectedLanguage($this->language, LANGUAGE_JP) ?>><label for="lang-ja"><?= $this->locales->profileSetting->japanese ?></label>
                </div>
                <hr>
                <h4><?= $this->locales->profileSetting->timezone ?></h4>
                <div class="radio">
                    <input type="radio" value="<?= TIMEZONE_VI ?>" name="timezone" id="timezone-vi"<?= Core_Helper::getSelectedTimezone($this->timezone, TIMEZONE_VI) ?>><label for="timezone-vi"><?= $this->locales->profileSetting->timezoneVi ?></label>
                </div>
                <div class="radio">
                    <input type="radio" value="<?= TIMEZONE_EN ?>" name="timezone" id="timezone-en"<?= Core_Helper::getSelectedTimezone($this->timezone, TIMEZONE_EN) ?>><label for="timezone-en"><?= $this->locales->profileSetting->timezoneEn ?></label>
                </div>
                <div class="radio">
                    <input type="radio" value="<?= TIMEZONE_JA ?>" name="timezone" id="timezone-ja"<?= Core_Helper::getSelectedTimezone($this->timezone, TIMEZONE_JA) ?>><label for="timezone-ja"><?= $this->locales->profileSetting->timezoneJa ?></label>
                </div>
                <input type="submit" class="btn btn-primary" name="save-profile-setting" value="<?= $this->locales->button->save ?>"/>
            </form>
        </div>
    </div>
</div>