<?php 
if ($this->pageCount)
{
?>
<div class="boxPaging">
        <div class="showPage">&nbsp;</div>
        <div class="pagAct">
            <?php if($this->current != 1): ?>
                <a href="javascript:void(0);" rel="<?php echo 1 ?>" class="button gray btnPage">&laquo;&laquo;</a>
            <?php endif; ?>
           
            <?php if($this->current > 1): ?>
                <a href="javascript:void(0);" rel="<?php echo $this->current - 1; ?>" class="button gray btnPage">&laquo;</a>
            <?php endif; ?>
            
            <label>Page</label>
            <span class="button gray"><?php echo $this->current; ?></span>
            <label>of <?php  echo $this->pageCount;?></label> 
            
            <?php if($this->current < $this->pageCount): ?>
                <a href="javascript:void(0);" rel="<?php echo $this->current + 1; ?>" class="button gray btnPage">&raquo;</a>
            <?php endif; ?>

            <?php if($this->current != $this->pageCount): ?>
                <a href="javascript:void(0);" rel="<?php echo $this->pageCount; ?>" class="button gray btnPage">&raquo;&raquo;</a>
            <?php endif; ?>
        </div>
    </div>
<?php
}
?>
