<!-- begin right form-->
<div class="md-overlay"></div>
<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right project-panel"  id="cbp-spmenu-s2" z-index="10000">
    <div class="rmv-pushright pull-right"><i class="fa fa-times"></i></div>
    <h3 id="right-popup-header"><?= $this->locales->calendarEvent->rightPopupHearAddEvent ?></h3>
    <form id="calendarEventFrm" name="calendarEventFrm" method="post" enctype="multipart/form-data">
        <input type="hidden" name="event-fromdate" value="" id="event-fromdate">
        <input type="hidden" name="event-todate" value="" id="event-todate">
        <input type="hidden" name="event-id" value="" id="event-id">
        <div class="form-group">
            <label for="event-title"><?= $this->locales->calendarEvent->eventTitle ?> <span class="required"> *</span></label>
            <input type="text" name="event-title" value="" class="form-control" id="event-title">
        </div>
        <div class="form-group">
            <label for="event-title"><?= $this->locales->calendarEvent->description ?></label>
            <input type="text" name="event-description" value="" class="form-control" id="event-description">
        </div>
        <div class="form-group">
            <label for="event-title"><?= $this->locales->calendarEvent->location ?></label>
            <input type="text" name="event-location" value="" class="form-control" id="event-location">
        </div>
        <div class="form-group category-group">
            <label for="event-cate"><?= $this->locales->calendarEvent->category ?><span class="required"> *</span></label>
            <select class="form-select" name="event-cate" id="event-cate">
                <option value=""><?= $this->locales->calendarEvent->dropdownTitle ?></option>
                <?php if ($this->isAdmin): ?>
                <option value="<?= EVENT_DEFAULT_GROUP ?>"><?= $this->locales->calendarEvent->defaultGroup ?></option>
                <?php endif; ?>
                <option value="<?= EVENT_TEAM ?>"><?= $this->locales->calendarEvent->team ?></option>
                <option value="<?= EVENT_PROJECT ?>"><?= $this->locales->calendarEvent->project ?></option>
                <option value="<?= EVENT_OTHER_GROUP ?>"><?= $this->locales->calendarEvent->otherGroup ?></option>
                <option value="<?= EVENT_PERSONAL ?>"><?= $this->locales->calendarEvent->personal ?></option>
            </select>
        </div>
        <div class="form-group subcategory-group">
            <label for="event-subcate"><?= $this->locales->calendarEvent->subCategory ?></label>
            <select class="form-select" id="event-subcate" name="event-subcate">
            </select>
        </div>
        <div class="form-group ">
            <label for="event-priority"><?= $this->locales->calendarEvent->priority ?><span class="required"> *</span></label>
            <select class="form-select" id="event-priority" name="event-priority">
                <option value=""><?= $this->locales->calendarEvent->dropdownTitle ?></option>
                <option value="<?= EVENT_LOW_PRIORITY ?>"><?= $this->locales->calendarEvent->lowPriority ?></option>
                <option value="<?= EVENT_NORMAL_PRIORITY ?>"><?= $this->locales->calendarEvent->normalPriority ?></option>
                <option value="<?= EVENT_HEIGH_PRIORITY ?>"><?= $this->locales->calendarEvent->heighPriority ?></option>
            </select>
        </div>
        <div class="form-group from-date">
            <label style="display:block;"><?= $this->locales->calendarEvent->date ?><span class="required"> *</span></label>
            <input type="text" class="form-control pull-left" placeholder="<?= $this->locales->calendarEvent->fromDate ?>" name="event-fromdate-datepicker" id="event-fromdate-datepicker" style="width:45%;">
            <input type="text" class="form-control pull-right" placeholder="<?= $this->locales->calendarEvent->toDate ?>" name="event-todate-datepicker" id="event-todate-datepicker" style="width:45%;">
        </div>
        <div class="clearfix"></div>
        <div class="form-group from-time" style="margin-top:1rem;">
            <label  style="display:block;width:100%;"><?= $this->locales->calendarEvent->time ?></label>
            <input name="event-fromtime" id="event-fromtime" class="form-control pull-left" placeholder="<?= $this->locales->calendarEvent->fromTime ?>" data-scroll-default="8:00" autocomplete="off" style="width:45%;">
            <input name="event-totime" id="event-totime" class="form-control pull-right" placeholder="<?= $this->locales->calendarEvent->toTime ?>" data-scroll-default="9:00" autocomplete="off" style="width:45%;">
        </div>
        <div class="checkbox" style="clear:both;margin-top:1rem;">
            <label><input name="allday" id="allday" type="checkbox" value="<?= EVENT_ALLDAY ?>"><?= $this->locales->calendarEvent->allday ?></label>
        </div>
        <!--<div class="checkbox action-repeat">
            <label><?= $this->locales->calendarEvent->repeat ?><input type="checkbox" name="event-repeat" id="event-repeat" value="<?= EVENT_REPEAT ?>"></label>
            <div class="repeat-rst"><small></small></div>
            <div class="popup-check-repeat">
                <h3>Lặp lại</h3>
                        <span style="padding:8px;">Lần lặp lại:</span>
                        <select id="check-repeat-option">
                               <option value="1">
                                   Hàng ngày
                               </option>
                               <option value="2">
                                   Mọi ngày trong tuần
                               </option>
                                <option value="3">
                                    Thứ hai, thứ tư, thứ sáu hàng tuần
                               </option>
                                <option value="4">
                                    Mỗi thứ 3 và thứ 5
                               </option>
                               <option value="5" selected>
                                    Hàng tuần
                               </option>
                               <option value="6">
                                    Hàng tháng
                               </option>
                               <option value="7">
                                    Hàng năm
                               </option>
                           </select>
                <table class="table table-repeat table-week">
                   <tr>
                       <td>Lặp lại mỗi:</td>
                       <td>
                           <select>
                              <option>1</option>
                              <option>2</option>
                              <option>3</option>
                              <option>4</option>
                              <option>5</option>
                              <option>6</option>
                              <option>7</option>
                              <option>8</option>
                              <option>9</option>
                              <option>10</option>
                              <option>11</option>
                              <option>12</option>
                              <option>13</option>
                              <option>14</option>
                              <option>15</option>
                              <option>16</option>
                              <option>17</option>
                              <option>18</option>
                           </select>
                       </td>
                   </tr>
                   <tr>
                       <td>Lặp lại vào:</td>
                       <td>
                           <label class="checkbox-inline">
                              <input type="checkbox" id="inlineCheckboxt2" value="optiont2"> t2
                            </label>
                            <label class="checkbox-inline">
                              <input type="checkbox" id="inlineCheckboxt3" value="optiont3"> t3
                            </label>
                            <label class="checkbox-inline">
                              <input type="checkbox" id="inlineCheckboxt4" value="optiont4"> t4
                            </label>
                            <label class="checkbox-inline">
                              <input type="checkbox" id="inlineCheckboxt5" value="optiont5"> t5
                            </label>
                            <label class="checkbox-inline">
                              <input type="checkbox" id="inlineCheckboxt6" value="optiont6"> t6
                            </label>
                            <label class="checkbox-inline">
                              <input type="checkbox" id="inlineCheckboxt7" value="optiont7"> t7
                            </label>
                            <label class="checkbox-inline">
                              <input type="checkbox" id="inlineCheckboxt8" value="optioncn"> cn
                            </label>
                       </td>
                   </tr>
                   <tr>
                       <td>Bắt đầu vào:</td>
                       <td><input type="text" class="form-control" value="3/11/2015"></td>
                   </tr>
                   <tr>
                       <td>Kết thúc</td>
                       <td>
                           <ul>
                               <li>
                                   <span class="ep-rec-ends-opt"><input id=":2m.endson_never" name="endson" type="radio" aria-label="Không bao giờ kết thúc" title="Không bao giờ kết thúc"><label for=":2m.endson_never" title="Không bao giờ kết thúc">Chưa bao giờ</label></span>
                               </li>
                               <li>
                               </li><span class="ep-rec-ends-opt"><input id=":2m.endson_count" name="endson" type="radio" aria-label="Kết thúc sau một số lần lặp lại" title="Kết thúc sau một số lần lặp lại"><label for=":2m.endson_count" title="Kết thúc sau một số lần lặp lại">Sau <input id=":2m.endson_count_input" size="3" value="" disabled="disabled" title="Số lần lặp lại"> lần xuất hiện</label></span></li>
                               <li>
                                    <span class="ep-rec-ends-opt"><input id=":2m.endson_until" name="endson" type="radio" checked="checked" aria-label="Kết thúc vào ngày được chỉ định" title="Kết thúc vào ngày được chỉ định"><label for=":2m.endson_until" title="Kết thúc vào ngày được chỉ định">Vào <input id=":2m.endson_until_input" size="10" value="8/12/2015" title="Ngày được chỉ định" autocomplete="off"></label></span>
                               </li>
                           </ul>
                       </td>
                   </tr>
                   <tr tabindex="0" id=":2m.recsummary"><td>Bảng tóm tắt:</td><td class="ep-rec-summary"><strong>Hàng tuần vào thứ ba, cho tới 8 thg 12, 2015</strong></td></tr>
                   <tr>
                       <td><span class="btn btn-default btn_ok_repeat">Xong</span></td>
                       <td><span class="btn btn-default btn_cancel_repeat">Hủy</span></td>
                   </tr>
                </table>
                
                <table class="table table-repeat table-day">
                   <tr>
                       <td>Lặp lại mỗi:</td>
                       <td>
                           <select>
                              <option>1</option>
                              <option>2</option>
                              <option>3</option>
                              <option>4</option>
                              <option>5</option>
                              <option>6</option>
                              <option>7</option>
                              <option>8</option>
                              <option>9</option>
                              <option>10</option>
                              <option>11</option>
                              <option>12</option>
                              <option>13</option>
                              <option>14</option>
                              <option>15</option>
                              <option>16</option>
                              <option>17</option>
                              <option>19</option>
                              <option>20</option>
                              <option>21</option>
                              <option>22</option>
                              <option>23</option>
                              <option>24</option>
                              <option>25</option>
                              <option>26</option>
                              <option>27</option>
                              <option>28</option>
                              <option>29</option>
                              <option>30</option>
                           </select>ngày
                       </td>
                   </tr>
                   <tr>
                       <td>Bắt đầu vào:</td>
                       <td><input type="text" class="form-control" value="17/11/2015"></td>
                   </tr>
                   <tr>
                       <td>Kết thúc</td>
                       <td>
                           <ul>
                               <li>
                                   <span class="ep-rec-ends-opt"><input id=":2m.endson_never" name="endson" type="radio" aria-label="Không bao giờ kết thúc" title="Không bao giờ kết thúc"><label for=":2m.endson_never" title="Không bao giờ kết thúc">Chưa bao giờ</label></span>
                               </li>
                               <li>
                               </li><span class="ep-rec-ends-opt"><input id=":2m.endson_count" name="endson" type="radio" aria-label="Kết thúc sau một số lần lặp lại" title="Kết thúc sau một số lần lặp lại"><label for=":2m.endson_count" title="Kết thúc sau một số lần lặp lại">Sau <input id=":2m.endson_count_input" size="3" value="" disabled="disabled" title="Số lần lặp lại"> lần xuất hiện</label></span></li>
                               <li>
                                    <span class="ep-rec-ends-opt"><input id=":2m.endson_until" name="endson" type="radio" checked="checked" aria-label="Kết thúc vào ngày được chỉ định" title="Kết thúc vào ngày được chỉ định"><label for=":2m.endson_until" title="Kết thúc vào ngày được chỉ định">Vào <input id=":2m.endson_until_input" size="10" value="8/12/2015" title="Ngày được chỉ định" autocomplete="off"></label></span>
                               </li>
                           </ul>
                       </td>
                   </tr>
                   <tr tabindex="0" id=":2m.recsummary"><td>Bảng tóm tắt:</td><td class="ep-rec-summary"><strong>Hàng ngày</strong></td></tr>
                   <tr>
                       <td><span class="btn btn-default btn_ok_repeat">Xong</span></td>
                       <td><span class="btn btn-default btn_cancel_repeat">Hủy</span></td>
                   </tr>
                </table>

                <table class="table table-repeat table-month-repeat">
                   <tr>
                       <td>Lặp lại mỗi:</td>
                       <td>
                           <select>
                              <option>1</option>
                              <option>2</option>
                              <option>3</option>
                              <option>4</option>
                              <option>5</option>
                              <option>6</option>
                              <option>7</option>
                              <option>8</option>
                              <option>9</option>
                              <option>10</option>
                              <option>11</option>
                              <option>12</option>
                              <option>13</option>
                              <option>14</option>
                              <option>15</option>
                              <option>16</option>
                              <option>17</option>
                              <option>19</option>
                              <option>20</option>
                              <option>21</option>
                              <option>22</option>
                              <option>23</option>
                              <option>24</option>
                              <option>25</option>
                              <option>26</option>
                              <option>27</option>
                              <option>28</option>
                              <option>29</option>
                              <option>30</option>
                           </select>tháng
                       </td>
                   </tr>
                   <tr><th>Lặp lại theo:</th><td><span class=""><input id=":4m.domrepeat" name="repeatby" type="radio" checked="checked" aria-label="Lặp lại theo ngày trong tháng" title="Lặp lại theo ngày trong tháng"><label for=":4m.domrepeat" title="Lặp lại theo ngày trong tháng">ngày trong tháng</label></span><span class=""><input id=":4m.dowrepeat" name="repeatby" type="radio" aria-label="Lặp lại theo ngày trong tuần" title="Lặp lại theo ngày trong tuần"><label for=":4m.dowrepeat" title="Lặp lại theo ngày trong tuần">ngày trong tuần</label></span></td></tr>
                   <tr>
                       <td>Bắt đầu vào:</td>
                       <td><input type="text" class="form-control" value="17/11/2015"></td>
                   </tr>
                   <tr>
                       <td>Kết thúc</td>
                       <td>
                           <ul>
                               <li>
                                   <span class="ep-rec-ends-opt"><input id=":2m.endson_never" name="endson" type="radio" aria-label="Không bao giờ kết thúc" title="Không bao giờ kết thúc"><label for=":2m.endson_never" title="Không bao giờ kết thúc">Chưa bao giờ</label></span>
                               </li>
                               <li>
                               </li><span class="ep-rec-ends-opt"><input id=":2m.endson_count" name="endson" type="radio" aria-label="Kết thúc sau một số lần lặp lại" title="Kết thúc sau một số lần lặp lại"><label for=":2m.endson_count" title="Kết thúc sau một số lần lặp lại">Sau <input id=":2m.endson_count_input" size="3" value="" disabled="disabled" title="Số lần lặp lại"> lần xuất hiện</label></span></li>
                               <li>
                                    <span class="ep-rec-ends-opt"><input id=":2m.endson_until" name="endson" type="radio" checked="checked" aria-label="Kết thúc vào ngày được chỉ định" title="Kết thúc vào ngày được chỉ định"><label for=":2m.endson_until" title="Kết thúc vào ngày được chỉ định">Vào <input id=":2m.endson_until_input" size="10" value="8/12/2015" title="Ngày được chỉ định" autocomplete="off"></label></span>
                               </li>
                           </ul>
                       </td>
                   </tr>
                   <tr tabindex="0" id=":2m.recsummary"><td>Bảng tóm tắt:</td><td class="ep-rec-summary"><strong>Hàng ngày vào ngày 17</strong></td></tr>
                   <tr>
                       <td><span class="btn btn-default btn_ok_repeat">Xong</span></td>
                       <td><span class="btn btn-default btn_cancel_repeat">Hủy</span></td>
                   </tr>
                </table>
            </div>
            </td>
            </tr>
            </table>
        </div>-->
        <!--Attendees-->
        <div class="form-group groupAttendessWrapper">
            <label for="attde"><i class="fa fa-fw fa-user"></i><?= $this->locales->calendarEvent->attendees ?></label>
            <div class="group-tag-name">
            </div>
            <button class="btn btn-default btn-addmore-attendees"><span class="glyphicon glyphicon-plus"></span><?= $this->locales->calendarEvent->addMore ?></button>
            <div class="popup-search-tagname">
                <div class="search">
                    <input type="search" id="text-search-user-attend" name="text-search-user-attend" autocomplete="off">
                    <i class="fa fa-search"></i>
                </div>
                <select name="attend-search-type" id="attend-search-type">
                    <option value="<?= EVENT_SEARCH_USER_BY_NAME ?>"><?= $this->locales->calendarEvent->name ?></option>
                    <option value="<?= EVENT_SEARCH_USER_BY_EMAIL ?>"><?= $this->locales->calendarEvent->email ?></option>
                </select>
                <span id="user-list-placeholder">
                </span>
                <div class="text-right">
                    <button class="btn btn-success btn-save-attendees"><?= $this->locales->calendarEvent->btnOk ?></button>
                    <button class="btn btn-default btn-cancel-attendees"><?= $this->locales->calendarEvent->btnCancel ?></button>
                </div>

            </div>
        </div>
        <!--End Attendees-->
        <input type="hidden" name="account-id-list" id="account-id-list" value="" >
        <div class="form-group">
            <label for="sel1"><?= $this->locales->calendarEvent->reminder ?></label>
            <select class="form-select" id="event-reminder" name="event-reminder">
                <?php foreach (range(15, 60, 15) as $time): ?>
                    <option value="<?= $time ?>"><?= $time ?> <?= $this->locales->calendarEvent->minute ?></option>
                <?php endforeach; ?>
            </select>
            <?= $this->locales->calendarEvent->remimderWarning ?>
        </div>
        <div class="form-group attach">
	    <span id="file-upload-placeholder"></span>
            <label for="sel1"><?= $this->locales->calendarEvent->attachments ?></label>
            <input type="file" name="attach-file" id="attach-file" data-buttonText="Attach" class="filestyle" data-input="false" data-iconName="glyphicon glyphicon-paperclip">
        </div>
        <hr/>
        <div class="button-group pull-right">
            <button class="btn btn-primary" id="btn-save"><?= $this->locales->calendarEvent->btnSave ?></button>
            <button class="btn btn-default" id="btn-delete"><span class="glyphicon glyphicon-trash"></span></button>
        </div>
    </form>
    <div class="popup_delete_option">
        <div class="content_popup">
          <i class="fa fa-times" style="position:absolute;top:10px;right:15px;"></i>
          <h4>Xóa sự kiện định kỳ</h4>
          <p  style="padding-top:1rem;">Bạn muốn chỉ xóa sự kiện này, tất cả các sự kiện trong chuỗi, hay sự kiện này và tất cả những sự kiện tương lai trong chuỗi không?</p>
          <ul>
            <li><button class="btn btn-default btn-sm" id="justThis">Chỉ trường hợp này</button>&nbsp;Tất cả các sự kiện khác trong chuỗi sự kiện sẽ vẫn giữ nguyên.</li>
            <li><button class="btn btn-default btn-sm" id="allEvent">Tất cả đi kèm</button>&nbsp;Sự kiện này và tất cả các sự kiện sau đều sẽ bị xóa.</li>
            <li><button class="btn btn-default btn-sm" id="allEventString">Tất cả sự kiện trong chuỗi</button>&nbsp;Tất cả các sự kiện trong chuỗi sự kiện đều sẽ bị xóa.</li>
          </ul>
          <div class="text-right">
            <button class="btn btn-default" id="btn_delete_option"><strong>Hủy thay đổi này</strong></button>
          </div>
        </div>
    </div>
</nav>
<script type="text/javascript">
  $('#check-repeat-option').change(function(){
      var value = $(this).val();
      if(value == 1){
        $('.table-day').show();
        $('.table-week').hide();
        $('.table-month-repeat').hide();
      }
      if(value == 5){
        $('.table-week').show();
        $('.table-day').hide();
        $('.table-month-repeat').hide();
      }

      if(value == 6){
        $('.table-month-repeat').show();
        $('.table-day').hide();
        $('.table-week').hide();
      }
  });
</script>
<!-- end right form-->
