
<div class="asideCont borPaddNon clearfix" id="newproduct">
    <table width="100%" cellspacing="0" cellpadding="0" border="1" class="tblComm">
        <tbody>
            <tr>
                <th align="left" colspan="2">UPDATE ATTRIBUTE</th>
            </tr>
          
            <tr>
                <td valign="top">
                    <div class="padLefRig20">
                        
                        <ul class="ulListIfSch">
                             <li>
                                <p class="titleDes"><label>Name</label></p>
                                <input type="text" id="gName" name="gName" placeholder="Enter name" value="<?php echo $this->arrAttribute['attribute_name'];?>">
                                <p class="error" id="gNameError" ></p>
                            </li>
                            <li>                        
                                <p class="titleDes"><label>Type</label></p>
                                <select id="gType" name="gType" class="seleComm width270">
                                    <?php 
                                     foreach ($this->arrAttributeType as $key => $value):
                                         
                                         $selected = '';
                                         if($this->arrAttribute['attribute_type'] == $key)
                                         {
                                             $selected ='selected="selected"';
                                         }
                                     ?>
                                    <option value="<?php echo $key; ?>"  <?php echo $selected;?>><?php echo $value; ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <p class="error" id="gTypeError" ></p>
                            </li>
                           
                            <li>
                                <p class="titleDes"><label>Sort Order</label></p>
                                <input type="text" id="gSort" name="gSort" placeholder="Sort order" value="<?php echo $this->arrAttribute['sort_order'];?>">
                                <p class="error" id="gSortError" ></p>
                            </li>
                            
                            <?php
                             $check1='checked';
                             $check2='';
                             
                             if($this->arrAttribute['active'] ==0)
                             {
                                  $check1='';
                                  $check2='checked';
                             }
                             
                             ?>
                            <li>                        
                                <p class="titleDes"><label>Active</label></p>
                                <div class="product-display">
                                    <label class="radio">
                                        <input type="radio" name="gDisplay" value="1" <?php echo $check1;?>>Yes
                                    </label>
                                    <label class="radio">
                                        <input type="radio" name="gDisplay" value="0" <?php echo $check2;?>>No
                                    </label>
                                </div>
                                <p class="error" id="eventDisplayError" ></p>
                            </li>
                            
                        </ul>
                    </div>
                </td>
                
            </tr>                  

            <tr>
                <td valign="top" colspan="2">
                    <div class="floatleft mLeft10 mTop10">
                        <a href="javascript:void(0)"  id="btnAdd1" class="button green">Update</a>
                        <input  type="hidden" name="attribute_id" id="attribute_id" value="<?php echo $this->arrAttribute['attribute_id'];?>" />
                    </div>                    
                </td>                    
            </tr>
        </tbody>
    </table>
</div>
<div style="height: 30px"></div>

<div id="toTop">^ Back to Top</div> 
<script type="text/javascript">
    
    $(function() {
	$(window).scroll(function() {
            if($(this).scrollTop() != 0) {
                    $('#toTop').fadeIn();	
            } else {
                    $('#toTop').fadeOut();
            }
	});
 
	$('#toTop').click(function() {
		$('body,html').animate({scrollTop:0},800);
	});	
    });
    
    
    $('#btnAdd1').click(function() {
        var name  = $('#gName').val(); 
        var gSort  = $('#gSort').val(); 
        var gType  = $('#gType').val(); 
        var active = $("input:radio[name='gDisplay']:checked").val();
        var id  = $('#attribute_id').val(); 
        
        if (name =='') {
            alert('Please input Name!');
            return;
        }


        var params = {
            active:active,
            sort: gSort,
            type: gType,
            name:name,
            id: id
        };

        $.post("<?php echo BASE_ADMIN_URL; ?>/attribute/add", params, function(result){
            if(result.error == 0)
            {
                window.location= '<?php echo BASE_ADMIN_URL; ?>/attribute/index/page/<?php echo $this->iPage;?>';
            }
            else
            {
                alert(result.message);
            }
        },'json');
    });
  
   
</script>