<?php
 if(!empty($this->paginator))
 {
    $index=0;
    foreach ($this->paginator as $value)
    {
         $classColum= '';

          if($index%3==0)
          {
              $classColum = 'first';

           ?>
               <li class="product-item">
                     <ul class="product-row">
            <?php  
          }

          if($index%3==2)
          {
               $classColum = 'last';
          }

          $sImageUrl = (!empty($value['image_url'])) ? PATH_NEWS_URL .'/'. $value['image_url'] : '';

          ?>


            <li class="product <?php echo $classColum;?>">
                    <a class="imgs" href="<?php echo BASE_URL; ?>/product/detail/id/<?php echo $value['product_id']; ?>">
                        
                        <img src="<?php echo $sImageUrl;?>" />
                         <span class="footer">
                            <span class="position">
                                     <?php
                                         if(($value['device_type']&1)>0)
                                         {
                                          ?>
                                              <i class="icon icon-apple-xs"></i>
                                         <?php
                                         }


                                         if(($value['device_type']&2)>0)
                                         {
                                          ?>
                                               <i class="icon icon-android-xs"></i>
                                         <?php
                                         }

                                         if(($value['device_type']&4)>0)
                                         {
                                          ?>
                                               <i class="icon icon-windowphone-xs"></i>
                                         <?php
                                         }


                                         if(($value['device_type']&4)>0)
                                         {
                                          ?>
                                              <i class="icon icon-computer-xs"></i>
                                         <?php
                                         }

                                         ?>

                            </span>
                    </span>
                    
                   </a>
                    <a class="name" href="<?php echo BASE_URL; ?>/product/detail/id/<?php echo $value['product_id']; ?>"><?php echo Core_Common::SubFullStrings($value['name'], 0,10); ?></a>
                    <div class="ver"><?php echo isset($this->arrProductType[$value['type']])?$this->arrProductType[$value['type']]:'';?></div>
                    <div class="info"><?php echo Core_Common::SubFullStrings(strip_tags($value['content']), 0, 80);?></div>
            </li>
          <?php

          $index++;

          if($index%3==0 || $this->iTotal<= $index)
          {
              ?>

                     </ul>
               </li>

              <?php
          }

    }
 }
 ?> 
