<div class="opt-editfile">
	<a href="#" data-toggle="modal" data-target="#modalRename" ng-click="renameFunc(info)"><i class="fa fa-pencil-square-o fa-fw m-r-10" aria-hidden="true"></i>Rename</a>
	<a ng-href="{{info.downloadURL}}" target="_blank"><i class="fa fa-cloud-download fa-fw m-r-10" aria-hidden="true"></i>Download</a>
	<a href="#" ng-click="shareFile(info)"><i class="fa fa-share-alt fa-fw m-r-10" aria-hidden="true"></i>Share</a>
	<a href="#"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
</div>