<script src="<?= $this->static->frontend->js ;?>/v2/contextMenu.js"></script>
<?php
$new = $this->arrNews;
?>
<?php
if(empty($new)){
    echo '<div class="content-news-detail alert alert-danger text-center">Data not found</div>';
}else{
?>
<link rel="stylesheet" href="<?= $this->static->frontend->css .'/v2/news.css'?>">
<script src="<?= $this->static->frontend->js ;?>/v2/ng-tags-input.min.js"></script>
<div class="content-news-detail">
    <div class="content-news">
        <h3><?php echo $this->arrNews['title']; ?></h3>
        <p>
            <?php echo $this->arrNews['content']; ?>
        </p>
    </div>
    <div class="function-news clearfix">
        <div class="date-news cols_5">
            <span>
            <?php echo date('H:i', $this->arrNews['create_date']); ?> - <?php echo date('Y-m-d', $this->arrNews['create_date']); ?></span>
        </div>
    </div>
    <!-- end function-news-->
    <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit ipsam quibusdam asperiores et porro, modi esse doloremque veritatis animi odit fugit expedita hic, doloribus nemo molestias, unde quisquam repudiandae fuga!</div>
</div><!-- end content news detail -->
<div class="contain-news">
    <div class="title-page">
        <h4><?php echo $this->locales->news->related; ?></h4>
    </div>
    <div class="all-news clearfix">
        <?php
        if (!empty($this->arrHotNews)) {
            $k = 0;
            foreach ($this->arrHotNews as $value) {
                if ($value['news_id'] != $this->arrNews['news_id']) {
                    $titleCSS = 'normal-news-title';
                    $contentCSS = 'normal-news';
                    if ($value['ishot'] == 1) {
                        $contentCSS = 'hot-news';
                        $titleCSS = 'hot-news-title';
                    }
                    $k++;
                    $sImageUrl = (!empty($value['image_url'])) ? PATH_NEWS_URL . '/' . $value['image_url'] : '';
                    ?>
                    <div class="cols_4">
                        <div class="news">
                            <div class="news-title">
                                <a href="<?php echo BASE_URL; ?>/news/detail/id/<?php echo $value['news_id']; ?>"
                                   class="<?php echo $titleCSS;?>">
                                   <span>
                                       <?php echo Core_Common::SubFullStrings($value['title'], 0, 50);?>
                                   </span>
                                </a>
                            </div>
                            <div class="<?php echo $contentCSS;?>">
                                <div class="content-news">
                                    <?php
                                    if (!empty($sImageUrl)) {
                                        ?>
                                        <a href="<?php echo BASE_URL; ?>/news/detail/id/<?php echo $value['news_id']; ?>">

                                        </a>

                                    <?php
                                    }
                                    ?>
                                </div>
                                <div class="function-news clearfix">
                                    <div class="date-news  text-grey">
                                        <small><?php echo date('H:i', $value['create_date']);?>
                                            - <?php echo date('Y-m-d', $value['create_date']);?></small>
                                    </div>
                                </div>
                                <!-- end function-news-->
                            </div>
                            <!-- hot news -->
                        </div>
                        <!-- end news -->
                    </div><!-- end cols_4 -->
                <?php
                }
                if ($k >= 3) {
                    break;
                }
            }
        }
        ?>
    </div>
    <!-- all news -->
</div><!-- end contain news -->
<?php } ?>
<!-- <p style="height:110px;">
    <?php echo Core_Common::SubFullStrings(strip_tags($value['content']), 0, 200);;?>
</p> -->
<!-- <img src="<?php echo $sImageUrl;?>" alt="" height="200px;"> -->

