<link rel="stylesheet" href="<?= $this->static->frontend->css .'/v2/news.css'?>">
<script src="<?= $this->static->frontend->js ;?>/v2/ng-tags-input.min.js"></script>
<script src="<?= $this->static->frontend->js ;?>/v2/contextMenu.js"></script>
<div class="_xksolit">
        <div class="title-page">
            <h4><?php echo $this->locales->news->news_list;?></h4>
        </div>
        <div>
            <div class="masonry">
            <?php
            foreach ($this->paginator as $value)
            {
                $titleCSS ='normal-news-title';
                $contentCSS ='normal-news';
                if($value['ishot'] ==1)
                {
                    $contentCSS ='hot-news';
                    $titleCSS ='hot-news-title';
                }
                $sImageUrl = (!empty($value['image_url'])) ? PATH_NEWS_URL .'/'. $value['image_url'] : '';
                ?>

                <div class="item">
                        <div class="<?php echo $contentCSS;?>" >
                            <div class="content-news">
                                <?php
                                if(!empty($sImageUrl))
                                {
                                    ?>
                                    <a href="<?php echo BASE_URL; ?>/news/detail/id/<?php echo $value['news_id']; ?>">
                                        <img class="img-responsive" src="<?php echo $sImageUrl;?>">
                                    </a>

                                    <?php
                                }
                                ?>
                                <!-- <p>
                                    // <?php echo Core_Common::SubFullStrings(strip_tags($value['content']), 0, 200);;?>
                                <!--</p>-->
                            </div>
                            <div class="_tt">
                                <a href="<?php echo BASE_URL; ?>/news/detail/id/<?php echo $value['news_id']; ?>" class="<?php echo $titleCSS;?>">
                                    <?php echo Core_Common::SubFullStrings($value['title'], 0, 120);?>
                                </a>
                            </div>
                            <div class="_tm">
                                <span><?php echo date('H:i',$value['create_date']);?> <?php echo date('Y-m-d',$value['create_date']);?></span>
                                <i class="fa fa-share-alt"></i>
                            </div><!-- end function-news-->
                    </div><!-- end news -->
                </div><!-- end cols_4 -->  
                <?php
            }
            ?>
            <div id="news-main"></div>
            <div class="clear"></div>
            <div class="more-news">
<input type="hidden" name="page" id="page" value="<?php echo ($this->iPage +1);?>">
<input type="hidden" name="more" id="more" value="<?php echo $this->iMore;?>">
</div>
</div><!-- all news -->
</div>
</div><!-- end contain news -->
<script language="javascript">
    $(document).ready(function() {
        $(window).scroll(function() {
            if($(window).scrollTop() == $(document).height() - $(window).height()) {
                var  page = $('#page').val();
                var more = $('#more').val();
                if(more==1)
                {
                    $.get("<?php echo BASE_URL;?>/news/index",{page:page},function(result){
                        $("#news-main").append(result.data);
                        if(result.more ==0)
                        {
                            $('#more').val(0);
                        }
                        else
                        {
                            $('#page').val(result.page);
                        }


                    }, 'json');

                }


            }
        })
    });
</script>




