    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 col-left-login">
      <form class="form" method="post" action="" >        
        <input id="sid" name="sid" type="hidden" value="<?= $this->token ?>" />        
        <input id="returnUrl" name="returnUrl" type="hidden" value="<?= $this->redirectPage ?>" />
        <input id="callbackUrl" name="callbackUrl" type="hidden" value="https://muaban.net/trang-ca-nhan/SignInCallback" />
        <div class="col-md-12 content">
          <div class="button-social button-google" onclick="javascript:goSocial('google')">
              <span class="icon-google-plus fa fa-google-plus fa-2x"></span>
              Đăng ký bằng Google
          </div>
          <div class="button-space"></div>
          <div class="button-social button-facebook" onclick="javascript: goSocial('facebook')">
              <span class="icon-facebook fa fa-facebook-official fa-2x"></span>
              Đăng ký bằng Facebook
          </div>
          <div class="button-space"></div>
          <div class="button-social button-yahoo" onclick="javascript: goSocial('yahoo')">
              <span class="icon-yahoo fa fa-yahoo fa-2x"></span>
              Đăng ký bằng Yahoo
          </div>
          <div class="button-space"></div>
          <div class="divider">
              <hr class="left" />Hoặc Đăng ký bằng Email <hr class="right" />
          </div>
          <?php if(isset($this->message) && $this->message != ''): ?>
            <div class="field-validation-error">
              <?= $this->message; ?>
            </div>
          <?php endif; ?>
          <div class="form-group">
              <input ng-model="username" class="form-control" id="UserName" maxlength="256" name="username" placeholder="Ten đăng nhập *" type="text" value="<?= $this->username ?>" />
              <span class="field-validation-valid"></span>
              <span class="field-validation-error hide">Bạn vui lòng nhập tên đăng nhập</span>
          </div>
          <div class="form-group">
              <input ng-model="email" class="form-control" id="Email" maxlength="256" name="email" placeholder="Email *" type="text" value="<?= $this->email ?>" />
              <span class="field-validation-valid"></span>
              <span class="field-validation-error hide">Bạn vui lòng nhập tên đăng nhập</span>
          </div>
          <div class="form-group">
              <input ng-model="password" class="form-control" id="Password" maxlength="51" name="password" placeholder="Mật khẩu *" type="password" />
              <span class="field-validation-valid"></span>
              <span class="field-validation-error hide" id="Error_password" >Bạn vui lòng nhập Mật khẩu</span>
          </div>
          <div class="form-group">
              <input ng-model="confirmpassword" class="form-control" id="ConfirmPassword" maxlength="51" name="confirmpassword" placeholder="Xac nhan mật khẩu *" type="password" />
              <span class="field-validation-valid"></span>
              <span class="field-validation-error hide" id="Error_Repassword">Không trùng khớp, bạn vui lòng nhập Mật khẩu</span>
          </div>          
          <div class="form-group">
                <input ng-model="fullname" class="form-control" id="FullName" maxlength="80" name="fullname" placeholder="Họ và tên" type="text" value="<?= $this->fullname ?>">
                <span class="field-validation-valid"></span>
                <span class="field-validation-error hide" id="Error_FullName">Bạn vui lòng nhập Họ và tên</span>
          </div>
          <?php if($this->iSubmitTime >= 3){ ?>
            <div id="html_element"></div>
          <?php } ?>          
          <div class="form-group">
              <div class="btn-submit">
                  <div id="errorSummary">                
                  </div>
                  <input type="submit" value="Đăng ký" class="button" />&nbsp;&nbsp;<a href="javascript:void(0);" onclick="javascript:goForgot();">Quên mật khẩu</a>?
              </div>
          </div>
          <div class="form-group">
              <input checked="checked" id="RememberMe" name="rememberme" type="checkbox" value="true" />
              <label for="RememberMe" style="color: #555555; font-weight: normal;">Lưu đăng nhập trên máy này</label>
          </div>
        </div>
      </form>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12 col-right-login">
      <h4>Thithien.com - Tạo tài khoản</h4>
      <p>Tạo tài khoản trên Thithien.com để tham gia cộng đồng mua bán hàng đầu.</p>
      <ul>
        <li class="fa fa-check-square-o fa-2x">
          <span>Đăng tin miễn phí</span>
        </li>
        <li class="fa fa-check-square-o fa-2x">
          <span>Hỗ trợ liên tục</span>
        </li>
        <li class="fa fa-check-square-o fa-2x">
          <span>Nổi bật tin đặc biệt</span>
        </li>
        <li class="fa fa-check-square-o fa-2x">
          <span>Mua của người chán, bán cho người cần</span>
        </li>
        <li class="fa fa-check-square-o fa-2x">
          <span>Quảng cáo liên tục và dài hạn</span>
        </li>
      </ul>
    </div>