<div class="wrapper people-detail">
    <?php 
        $defaultAvatar = $this->static->frontend->images.'/avatar_default.jpg';
        
        if (!empty($this->arrAccountInfo))   
        {
              $sImageUrl = Core_Common::avatarProcess($this->arrAccountInfo['picture']);
        ?>
                     
	<div class="inner">
                 <?php 
                    echo $this->render('partials/slogan.phtml');
                 ?>
            
		<h2 class="page-title"><i class="icon"></i><span class="txt">People</span></h2>
		<div class="person-info">
			<div class="avatar-wrapper"><div class="avatar"><img src="<?php echo $sImageUrl;?>"></div></div>
			<div class="info">	
				<div class="name"><?php echo $this->arrAccountInfo['name']; ?></div>
				<div class="position">
                                  <?php echo isset($this->arrGeneralAttHash[$this->arrAccountInfo['position']])?$this->arrGeneralAttHash[$this->arrAccountInfo['position']]:'';?>
 
                                </div>
				<div class="about">
					<div class="title"><i class="icon-about"></i><span>About <?php echo $this->arrAccountInfo['name']; ?></span></div>
					<div class="content"> 
                                            <?php 
                                                 if(!empty($this->arrAccountInfo['description']))
                                                 {
                                                      echo $this->arrAccountInfo['description'].' <a class="showmore" href="#"><span>Show more</span><i class="icon-showmore"></i></a>';
                                                 }
                                                 ?>
                                         </div>
				</div>
				<div class="private-info">
					<ul>
						<li class="first">
							<div class="title"><i class="icon-birth"></i><span>Date of Birth</span></div>
							<div class="content"><?php echo $this->arrAccountInfo['birthday'];?></div>
						</li>
						<li>
							<div class="title"><i class="icon-dept"></i><span>Department</span></div>
							<div class="content"><?php echo isset($this->arrGeneralAttHash[$this->arrAccountInfo['department_id']])?$this->arrGeneralAttHash[$this->arrAccountInfo['department_id']]:'';?></div>
						</li>
						<li class="last">
							<div class="title"><i class="icon-contact"></i><span>Contact</span></div>
							<div class="content">
								<ul class="contact">
                                                                        <?php
                                                                          if(!empty($this->arrAccountInfo['phone']))
                                                                          {
                                                                              ?>
                                                                    
                                                                                <li class="phone"><i class="icon-phone"></i><?php echo $this->arrAccountInfo['phone']; ?></li>
                                                                          <?php
                                                                          }
                                                                          ?>
									
                                       
									<li class="email"><i class="icon-email"></i><?php echo $this->arrAccountInfo['email']; ?></li>
						
                                                                    <?php
                                                                          if(!empty($this->arrAccountInfo['skype_account']))
                                                                          {
                                                                              ?>
                                                                    
                                                                                <li class="skype"><i class="icon-skype"></i><?php echo $this->arrAccountInfo['skype_account']; ?></li>
                                                                          <?php
                                                                          }
                                                                          ?>
                                                                                <?php
                                                                          if(!empty($this->arrAccountInfo['mobion_account']))
                                                                          {
                                                                              ?>
                                                                    
                                                                               <li class="mobion"><i class="icon-mobion"></i><?php echo $this->arrAccountInfo['mobion_account']; ?></li>
                                                                          <?php
                                                                          }
                                                                          ?>
									
									
								</ul>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="content-wrapper">
			<div class="content-wrap">
				<div class="content-inner">
					<div class="relationship-to">
						<div class="people-suggest">
							<span class="page-slogan">Relationship to <?php echo Core_Common::SubFullStrings($this->arrAccountInfo['name'], 0, 6);?></span>
							<div class="people-search">
                                                                <button type="button" class="seach_people">Search</button>
                                                                <div class="combobox-wrapper team">
                                                                        <select class="select" name="teamid"  id="teamid" title="Team">
                                                                            <option value="0">Team</option>
                                                                            <?php
                                                                              if(!empty($this->arrGeneral['team']))
                                                                              {
                                                                                    foreach($this->arrGeneral['team'] as $value)
                                                                                    {
                                                                                          $selected='';

                                                                                          if($this->arrAccountInfo['team_id'] == $value['id'])
                                                                                          {
                                                                                              $selected='selected="selected"';
                                                                                          }
                                                                                  ?>
                                                                                        <option value="<?php echo $value['id'];?>" <?php echo $selected;?>><?php echo $value['name'];?></option>
                                                                              <?php
                                                                                    }
                                                                              }
                                                                              ?>

                                                                        </select>
                                                                </div>
                                                                <div class="combobox-wrapper department">
                                                                        <select class="select" name="departmentid"  id="departmentid"  title="Department">
                                                                                 <option value="0">Department</option>
                                                                                <?php
                                                                              if(!empty($this->arrGeneral['department']))
                                                                              {
                                                                                    foreach($this->arrGeneral['department'] as $value)
                                                                                    {

                                                                                          $selected='';

                                                                                          if($this->arrAccountInfo['department_id'] == $value['id'])
                                                                                          {
                                                                                              $selected='selected="selected"';
                                                                                          }
                                                                                  ?>
                                                                                        <option value="<?php echo $value['id'];?>" <?php echo $selected;?>><?php echo $value['name'];?></option>
                                                                              <?php
                                                                                    }
                                                                              }
                                                                              ?>
                                                                        </select>
                                                                </div>
                                                                <div class="search-box">
                                                                        <input type="text" name="name" placeholder="Search" id="name" value="<?php echo $this->arrSearch['name'];?>"></input>
                                                                        <i class="icon-search"></i>
                                                                </div>
                                                        </div>
						</div>
						<div class="friends-slider-wrapper">
                                                    
                                                        <span id="relationship_people">
                                                            
                                                        </span>
						</div>
					</div>
				</div>
			</div>
        </div>
    </div>
     <?php
        }
      ?>
</div><!-- end wrapper -->

 <?php 
  /*  if(!empty($this->arrAccountManager))
    {
     ?>
       <a href="<?php echo BASE_URL; ?>/user/detail?id=<?php echo $this->arrAccountManager['account_id'];?>"><?php echo  $this->arrAccountManager['name'];?></a>
    <?php
    }*/
 ?>

<script language="javascript">
function getRelationPeople(name, teamid, departmentid, userid)
{
      $.get("<?php echo BASE_URL;?>/user/search",{name:name,teamid:teamid,departmentid:departmentid,userid:userid},function(result){

       $('#relationship_people').html(result);
   });
}
getRelationPeople('', '<?php echo $this->arrAccountInfo['team_id'];?>', 0, '<?php echo $this->arrAccountInfo['account_id'];?>');


/* Search  Relationship to user*/
 $(".seach_people").click(function(){
         
      var  departmentid = $('#departmentid').val();
      var  teamid = $('#teamid').val();
      var  name = $('#name').val();
      
      getRelationPeople(name, teamid, departmentid, 0);
         
  });
  
  $('#name').keypress(function(event){
 
	var keycode = (event.keyCode ? event.keyCode : event.which);
	if(keycode == '13'){
            
            var  departmentid = $('#departmentid').val();
            var  teamid = $('#teamid').val();
            var  name = $('#name').val();

            getRelationPeople(name, teamid, departmentid);
	 }
	
     });
   
   /* End Search */
    
</script>
                          