 <?php
    $index=0;

    if(!empty($this->arrResult))
    {
    ?>
    <section class="friends-slider">
        
     <?php
        foreach ($this->arrResult as $value)
        {
            
             if($this->iAccountID != $value['account_id'])
             {
                    $classColumn ='';

                    if($index==0)
                    {
                        $classColumn = 'class="first-child"';
                    }
                    $sImageUrl = Core_Common::avatarProcess($value['picture']);



                  ?>

                  <article <?php echo $classColumn;?>  style="background-image:url(<?php echo $sImageUrl;?>);">
                          <a href="<?php echo BASE_URL; ?>/user/detail/id/<?php echo $value['account_id']; ?>">
                                  <span class="footer">
                                          <span class="name"><?php echo $value['name']; ?></span>
                                          <span class="position"><?php echo isset($this->arrGeneralAttHash[$value['position']])?$this->arrGeneralAttHash[$value['position']]:''; ?></span>
                                  </span>
                          </a>
                  </article>


              <?php
                  $index++;
             }
        }
        ?>
        </section>


        <?php
           if($index>0)
           {
            ?>
                <script language=javascript">        
                $('.friends-slider').bxSlider({
                                slideWidth: 175,
                                useCSS : false,
                                minSlides: 9,
                                maxSlides: 9,
                                moveSlides: 0,
                                slideMargin: 0,
                                pager : false,
                                infiniteLoop: false,
                                hideControlOnEnd: true
                        });
                </script>
       <?php
           }
    }
?>
