<div class="user-guide-option">
        <div class="close-user-guide" style="position:absolute; right:0; top:0; padding:5px 10px; cursor:pointer; border:none;background:orange;color:#fff;">
            <i class="fa fa-times "></i>
        </div>
       <h3 class="text-center" style="font-weight:700">User guide</h3>

       <span class="btn-backlist pull-left" style="display:none;cursor:pointer;text-decoration:underline;margin-top:1rem;">Back to menu</span>
       <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
    <ul class="list-group" id="menu-check">
        <li class="list-group-item"><a href="#" class="link-chapter-1">Chapter 1.Getting started<i class="fa fa-plus-square fa-fw"></i></a>
                <ul class="hidden-item-userguide hidden-item-chapter-1">
                    <li><a href="#gianty-portalhomepage" class="gianty-homepage">1.1 Gianty portal homepage</a></li>
                    <li><a href="#activate-stream" class="activity-stream-link">1.2 Using the activity stream</a>
                        <ul class="sub-item-hidden">
                            <li><a href="#update-status" class="activity-stream-link">1.2.1 Update status</a></li>
                            <li><a href="#mention-someone" class="activity-stream-link">1.2.2 Mention(tag) someone</a></li>
                            <li><a href="#share-lfp" class="activity-stream-link">1.2.3 Share a link/file/photo</a>
                                <ul class="sub-item-hidden">
                                    <li><a href="#share-link" class="activity-stream-link">Share a link</a></li>
                                    <li><a href="#share-file" class="activity-stream-link">Share a file</a></li>
                                    <li><a href="#share-photo" class="activity-stream-link">Share a photo</a></li>
                                </ul>
                            </li>
                            <li><a href="#edit-deleteactive" class="activity-stream-link">1.2.4 Edit/Delete activities</a>
                                <ul class="sub-item-hidden">
                                    <li><a href="#edit-active" class="activity-stream-link">Edit activities</a></li>
                                    <li><a href="#delete-active" class="activity-stream-link">Delete activities</a></li>
                                </ul>
                            </li>
                            <li><a href="#edit-deletecmt" class="activity-stream-link">1.2.5.Comment on activities and edit/delete comment</a>
                                <ul class="sub-item-hidden">
                                    <li><a href="#comment-active" class="activity-stream-link">Comment on activities</a></li>
                                    <li><a href="#edit-deletcmt" class="activity-stream-link">Edit/Delete comments</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
        </li>
        <li class="list-group-item"><a href="#" class="link-chapter-2">Chapter 2.Working with groups<i class="fa fa-plus-square fa-fw"></i></a>
                 <ul class="hidden-item-userguide hidden-item-chapter-2">
                    <li><a href="#access-group" class="working-group-link">2.1. Access a group</a></li>
                    <li><a href="#create-group" class="working-group-link">2.2. Create a group</a> </li>
                    <li><a href="#join-leave-group" class="working-group-link">2.3. Join/ Leave a group</a>
                        <ul class="sub-item-hidden">
                            <li><a href="#join-group"  class="working-group-link">2.3.1. Join a group</a></li>
                            <li><a href="#leave-group"  class="working-group-link">2.3.2. Leave a group</a></li>
                        </ul>
                    </li>
                    <li><a href="#edit-delete-group" class="working-group-link">2.4. Edit/ Delete a group</a>
                        <ul>
                            <li><a href="#edit-group" class="working-group-link">2.4.1.Edit a group information</a></li>
                            <li><a href="#delete-group" class="working-group-link">2.4.2.Delete a group</a></li>
                        </ul>
                    </li>
                    <li><a href="#accept-ignore" class="working-group-link">2.5. Accept/ Ignore an invitation</a></li>
                    <li>
                        <a href="#approve-deny-request" class="working-group-link">2.6. Approve/ Deny a request to join group</a>
                    </li>
                    <li><a href="#group-app" class="working-group-link">2.7. Group’s applications </a>  
                        <ul class="sub-item-hidden">
                            <li><a href="#activity-stream" class="working-group-link">2.7.1.Activity stream</a></li>
                            <li><a href="#document" class="working-group-link">2.7.2.Document</a>
                                 <ul class="sub-item-hidden">
                                    <li><a href="#create-folder" class="working-group-link">Create a folder</a></li>
                                    <li><a href="#upload-file" class="working-group-link">Upload files</a></li>
                                    <li><a href="#delete-file" class="working-group-link">Delete a file</a></li>
                                    <li><a href="#download-file" class="working-group-link"> Download a file</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#calendar" class="working-group-link">2.7.3.Calendar</a></li>
                    <li><a href="#members" class="working-group-link">2.7.4.Members</a></li>
                    <li><a href="#settings" class="working-group-link">2.7.5.Settings</a>
                        <ul class="sub-item-hidden">
                            <li><a href="#manage-group" class="working-group-link">Manage group information</a></li>
                            <li><a href="#manage-member" class="working-group-link">Manage member</a></li>
                        </ul>
                    </li>
                </ul>
        </li>
        <li class="list-group-item"><a href="#" class="link-chapter-3  working-with-new-link">Chapter 3.Working with news<i class="fa fa-plus-square fa-fw"></i></a></li>
        <li class="list-group-item"><a href="#" class="link-chapter-4">Chapter 4.Working with photos<i class="fa fa-plus-square fa-fw"></i></a>
                <ul class="hidden-item-userguide hidden-item-chapter-4">
                    <li><a href="#create-album" class="working-with-photos-link">4.1. Create album</a></li>
                    <li><a href="#add-photo" class="working-with-photos-link">4.2. Add photo</a></li>
                </ul>
        </li>
        <li class="list-group-item"><a href="#" class="link-chapter-5">Chapter 5.Working with email<i class="fa fa-plus-square fa-fw"></i></a>
                <ul class="hidden-item-userguide hidden-item-chapter-5">
                    <li><a href="#check-inbox" class="working-with-mail-link">5.1. Check inbox</a></li>
                    <li><a href="#compose-email" class="working-with-mail-link">5.2. Compose an email</a></li>
                    <li><a href="#reply-email" class="working-with-mail-link">5.3. Reply an email</a></li>
                </ul>
        </li>
        <li class="list-group-item"><a href="#" class="link-chapter-6">Chapter 6.Working with calendar<i class="fa fa-plus-square fa-fw"></i></a>
                <ul class="hidden-item-userguide hidden-item-chapter-6">
                    <li><a href="#calendar-interface" class="working-with-calendar-link">6.1. Calendar interface</a></li>
                    <li><a href="#create-calendar" class="working-with-calendar-link">6.2. Create a calendar</a>
                        <ul class="sub-item-hidden">
                            <li><a href="#create-group-calendar" class="working-with-calendar-link">6.2.1. Create a group related calendar</a></li>
                            <li><a href="#create-personal" class="working-with-calendar-link">6.2.2. Create a personal calendar</a></li>
                        </ul>
                    </li>
                    <li><a href="#edit-delete-event" class="working-with-calendar-link">6.3. Edit/ Delete an event</a>
                        <ul class="sub-item-hidden">
                            <li><a href="#edit-event" class="working-with-calendar-link">6.3.1. Edit an event</a></li>
                            <li><a href="#delete-event" class="working-with-calendar-link">6.3.2. Delete an event</a></li>
                        </ul>
                    </li>
                </ul>
        </li>
        <li class="list-group-item"><a href="#" class="link-chapter-7">Chapter 7.Working with absence<i class="fa fa-plus-square fa-fw"></i></a>
            <ul class="hidden-item-userguide hidden-item-chapter-7">
                <li><a href="#absence-page" class="working-with-absence-link">7.1. Absence page interface</a></li>
                <li><a href="#create-absence" class="working-with-absence-link">7.2. Create an Absence request</a></li>
                <li><a href="#cancel-absence" class="working-with-absence-link">7.3. Cancel a request   </a></li>
                <li><a href="#review-approve-request" class="working-with-absence-link">7.4. Review/ Approve requests   </a></li>
                <li><a href="#confirm-request" class="working-with-absence-link">7.5. Confirm requests</a></li>
            </ul>
        </li>
        <li class="list-group-item"><a href="#" class="link-chapter-8">Chapter 8.Working with Check in/out<i class="fa fa-plus-square fa-fw"></i></a>
            <ul class="hidden-item-userguide hidden-item-chapter-8">
                <li><a href="#general-information" class="working-with-checkinout-link">8.1. General information</li></a>
                <li><a href="#check-inout" class="working-with-checkinout-link">8.2. Check in/out</li></a>
                <li><a href="#absence" class="working-with-checkinout-link">8.3. Absence</li></a>
                <li><a href="#late" class="working-with-checkinout-link">8.4. Late</li></a>
                <li><a href="#overtime" class="working-with-checkinout-link">8.5. Overtime</li></a>
            </ul>
        </li>
    </ul>
    <div class="chapter-content">
    <div class="chapter-content-item chapter-1-content gianty-portal-hompage">
        <h4>Chapter 1. Getting Started</h4>
        <p id="gianty-portalhomepage"><strong>1.1 Gianty portal homepage</strong></p>
        <p><strong>1.1.1.  Log in Gianty Portal</strong></p>
        <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1.png';?>" alt="" class="center-block img-responsive">
        <p>Use the user name and password that you use to login you PC to login Gianty Portal </p>
        <strong>1.1.2.  Gianty Portal Homepage</strong>
        <p>
            After signing in your account successfully, you are redirected to the homepage, the starting point for exploring Gianty Portal. This homepage provides you a perfect overview of all social and collaboration activities available in Gianty Portal 
            Gianty Portal Homepage</p>
            <div class="text-center">Gianty Portal Homepage</div>
            <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1.1.png';?>" alt="" class="center-block img-responsive">
            <p>
                <strong>①   Top navigation:</strong> Take common actions via the following menus (From left to right) <br>
                <ul>
                    <li>1. <strong>Company name:</strong></li>
                    <li>2. <strong>Quick create button:</strong> Quickly create content (topics, calendar events, tasks, groups, upload files/ photo) from any places. (Coming soon)</li>
                    <li>3. <strong>Search:</strong> Search for people, documents and more. (Coming soon)</li>
                    <li>4. <strong>Notification:</strong> Inform you of new activities from colleagues, task notifications, new comments, likes, calendar events etc.,</li>
                    <li>5. <strong>User profile and avatar:</strong> User’s name and default avatar, Log out.</li>
                    <li>6. <strong>Language option:</strong> English, Vietnamese, Japanese</li>
                </ul>
            </p>

            <p><strong>②   Left navigation</strong>: Main menu providing access to all the portal pages and tools. The Company sections can be collapsed to make the menu smaller if required</p>
            <p><strong>1. Company:</strong><br>
                a. News: All the company’s important announcements, news as well as useful information and hot news from all over the world will be posted here. <br>
                b. Photos: All the photo uploaded by user will be stored and displayed in this page.</p>
                <p><strong>2. Workspace:</strong><br>
                    a. Feed: Come back to the homepage from any places.<br>
                    b. Mail: Outlook email inbox are connected to the portal so you can check your inbox as well as composing email as you need.</p>
                    <p><strong>c. Calendar:</strong><br> Allow you to schedule appointments and meetings, establish recurring activities, create multiple calendars and share calendars with others. With Calendar, it is easy to keep track of all important events/tasks and collaborate with other people, all in one place.</p>
                    d. Check in/out: Allow you to check your check in/ out time, absence or late.

                    <p><strong>3. Tools:</strong><br>
                        a. Absence: You can submit a new Absence request via the Absence request form and follow up on your Absence. Beside, you can approve or reject any Absence requests of your subordinates (depending on your position)<br>
                        b. Expense: coming soon</p>
                        <p><strong>4. Workgroups:</strong><br>
                            a. The workgroup is a virtual community of users created for discussing and solving of defined issues, goals and tasks. <br>
                            b. All the communications, tasks and data inside the group can be viewed by members only. <br>
                            c. There are default groups created by team leader/ project manager/ admin, or any kind of informal groups created by individuals depending on needs.</p>
                            <p>
                                ③   Activity composer:  You can update your status, upload and share your document or photos.<br>
                                ④   Activity stream: You can follow activities of your colleagues, teams or groups; create your own activities (liking or commenting).
                            </p> 
                            <div class="note-wrapper-content">
                                <strong style="text-decoration:underline;">Note: </strong>
                                • You can change your portal background by clicking <img src="<?= $this->static->frontend->images .'/user-guide/chapter-1.1.2.jpg';?>" width="32" height="32" alt=""> on  the right screen
                            </div>
                        </div>

                        <div class="chapter-content-item chapter-1-content activity-stream">
                            <h4 id="activate-stream">1.2 Using the activity stream</h4>
                            <p id="update-status"><strong>1.2.1. Update status</strong></p>
                            By entering your status message, you can tell people what you are doing on or sharing information. Thereafter, your colleagues who are connected with you can see your updates in their connections. <br>
                            &#9830; On your Activity Stream page, enter your current status in the Activity composer. 
                            <p>
                                <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2.png';?>" alt="" class="img-responsive center-block"><br>
                            </p>
                            <p>
                                &#9830;  Select the group you want to share status with. <br>
                                &#9830;  Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-4.jpg';?>" alt="">    to accept sharing your status.
                            </p>
                            <div class="note-wrapper-content">
                                <strong style="text-decoration:underline;">Note:</strong><br>
                                &#9830; Your status will be seen by the group you has selected to share. <br>
                                &#9830; You can see your status in Feed/ Activity stream and Group/ Activity stream.
                            </div>
                            <strong id="mention-someone">1.2.2. Mention (tag) someone</strong><br>
                             &#9830; Type the "@" symbol into your activity composer, then type the person name you want to mention. A suggestion list that contains matching characters will appear. 
                            <p>
                                <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1.1.3.jpg';?>" alt="" class="img-responsive center-block">
                            </p>
                            <p>
                               &#9830; Go through the suggestion list by moving your cursor over it, then click a person. <br>
                               &#9830; After being validated, "@" and following characters will be replaced with Full name which is wrapped in a label. <br>You can click [x] in the label to dismiss it.
                            </p>
                            <div class="note-wrapper-content">
                                <strong style="text-decoration:underline;">Note</strong><br>
                                • Only one person can be selected at one time. <br>
                                •  You can do the same steps above to mention someone in your comments. <br>
                                •  The person you mention also sees the post in his/her Activity Stream. 
                            </div>
                            <p>
                                <strong id="share-lfp">1.2.3. Share a link/ file/ photo</strong>
                            </p>
                            <strong id="share-link">&#9830; Share a link:</strong>
                            You can share media links, such as web articles, slides, videos, websites and more in your status. <br>
                            • Simply enter the link into the activity composer. <br>
                            • Click  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-4.jpg';?>" alt="" width="57" height="30">  to share your status with the link. <br>
                            
                            <p><strong id="share-file">&#9830; Share a file</strong>
                                1. Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-5-btn-file.png'?>" alt="">  in the Activity composer to open the Select File form <br>
                                <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-5.jpg';?>" class="img-responsive center-block"  alt=""><br>
                            </p>
                            2. Browse a file from a drive or upload it from your local device. <br>
                            <strong>a.  The first way:</strong> Browsing files from a folder in your groups’ document and sharing <br>
                            i. Select a file by a simple clicking, then validating the selection by clicking on Select. <br>
                            <p><img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-7.png';?>" class="img-responsive center-block"  alt=""></p>

                            ii. Repeat the steps for whatever files you want to share. <br>
                            <p><img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-8.png';?>" class="img-responsive center-block"  alt=""></p>

                            iii. Click <img  src="<?= $this->static->frontend->images.'/user-guide/btn-cancel.png';?>" alt="" width="64" height="31">  to validate the file browsing <br>

                            b. The second way: Uploading files and sharing <br>
                            i. Select the folder where you want to store the file. You can also click <img src="<?= $this->static->frontend->images.'/user-guide/btn-newfolder.png';?>" alt="" width="85" height="25">   to create a new folder to store the file.
                            <img src="<?= $this->static->frontend->images.'/user-guide/upload-file.png';?>" class="img-responsive center-block"  alt=""><br>    
                            ii. Click   <img src="<?= $this->static->frontend->images.'/user-guide/btn-upload.jpg';?>" alt="" width="64" height="31">  , a popup window will appear to let you select a file from your computer. <br>
                            iii. Select the file and validate the selection by clicking on <img src="<?= $this->static->frontend->images.'/user-guide/btn-select.jpg';?>" alt="" width="44" height="21"> . The file will be uploaded to the server after selecting it.
                            3. Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-4.jpg';?>" alt="" >  to share your status with the attachment.
                            <div class="note-wrapper-content">
                                <strong style="text-decoration:underline;">Note:</strong> <br>
                                • To remove your uploaded file, simply click  <img  src="<?= $this->static->frontend->images.'/user-guide/close.png'?>" alt=""> next to it. <br>
                                <p><img src="<?= $this->static->frontend->images.'/user-guide/remove-upload.png';?>" alt="" class="img-responsive center-block"></p>

                                • Others can download the attachment to their local devices <br>
                                • You can check the file in the Document application of the relevant Group. See <strong>Working with Groups </strong> > <strong> Group’s application </strong> > <strong>Document</strong> for more details. 
                                <p><img src="<?= $this->static->frontend->images.'/user-guide/group-document.jpg';?>" alt="" class="img-responsive center-block"> </p>
                            </div> 
                            <p>
                                <strong id="share-photo">* Share a photo: </strong><br>
                                1. Click  <img src="<?= $this->static->frontend->images.'/user-guide/btn-camera.png'?>" alt="">  in the Activity composer to open a File upload window.  <br>
                                2. Browse and select your desired photo, then click Open to start uploading your selected photo. <br>
                                3. Repeat the steps for more photos you want to share. <br>
                                <p><img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-9.png';?>" alt="" class="img-responsive center-block"></p>
                                Click   <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-4.jpg'?>" alt=""> to share your status with the photos 
                            </p>
                            
                            <p><strong id="edit-deleteactive">1.2.4. Edit/ Delete activities</strong></p>
                            <p>
                                You are allowed to edit or delete your activities that you created <br>
                                <strong id="edit-active">* Edit activities </strong><br>
                                1. Click  <img src="<?= $this->static->frontend->images.'/user-guide/edit-active.png'?>" alt=""> in the activity you want to Edit. <br>
                                2. Select <img src="<?= $this->static->frontend->images.'/user-guide/edit-post.jpg'?>"  alt=""> <br>
                                <img src="<?= $this->static->frontend->images.'/user-guide/edit-active-1.jpg'?>" alt="" class="img-responsive center-block"> <br>
                                3. Change your status and click <img  src="<?= $this->static->frontend->images.'/user-guide/done-editing.jpg'?>" alt="">   <br>
                                <p><img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-11.jpg'?>" class="img-responsive center-block" alt=""></p>
                            </p>
                            <div class="note-wrapper-content">
                                <strong style="text-decoration:underline;">Note: </strong>
                                • You can only edit your text, you cannot edit your shared files or photos. 
                            </div>
                            <strong id="delete-active">* Delete activities</strong><br>
                            1. Click <img src="<?= $this->static->frontend->images.'/user-guide/edit-active.png';?>" alt=""> icon in the activity you want to delete. <br>
                            <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-12.jpg';?>" alt=""></p>
                            2. Select  <img src="<?= $this->static->frontend->images.'/user-guide/delete-post.jpg';?>" alt="">
                            <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/delete-post-2.jpg';?>" alt=""></p>
                            3. Click  <img src="<?= $this->static->frontend->images.'/user-guide/button-deleteit.jpg';?>" alt=""> in the confirmation message to accept your deletion.
                            <p>
                                <p><strong  id="edit-deletecmt">1.2.5. Comment on activities and Edit/ Delete comments </strong></p>
                                <strong id="comment-active">&#9830; Comment on activities </strong> 
                                <p>
                                    1. Enter your comment into the Comment box and enter. Your comment will be displayed below the activity. <br>
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-13.jpg';?>" alt=""></p> 
                                    2. When there are more than two comments on activity, 2 latest comments will be displayed below the activity.  <br>
                                    3. You can click <strong> View previous comments </strong> on the top of the comment part to view more.
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-14.jpg';?>" alt=""></p>
                                    <div class="note-wrapper-content">
                                        <strong style="text-decoration:underline;">Note: </strong>
                                        You can mention people in your comment by "@" symbol into your activity composer, then type the person name you want to mention. See Mention (tag) someone for more details.
                                    </div>
                                </p>
                            </p>
                            <strong id="edit-deletcmt">&#9830; Edit/ Delete comments</strong><br>
                            
                            <strong id="edit-cmt">1. Edit comments</strong><br>
                            You are allowed to edit your own comments
                            a. Click  <img src="<?= $this->static->frontend->images.'/user-guide/edit-comments.jpg';?>" alt=""> icon in the comment you want to Edit. <br>
                            <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-15.jpg';?>" alt=""> </p>
                            b. Select <img  src="<?= $this->static->frontend->images.'/user-guide/edit-post-2.jpg';?>" alt=""> <br>
                            c. Enter your comment into the Comment box and enter. 
                            <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-16.jpg';?>" alt=""> <br></p>
                            <p><strong id="delete-cmt">2.Delete comments</strong></p>
                            You are allowed delete your own comments and those in your activities
                            <ul>
                                <li>
                                    a. Click <img src="<?= $this->static->frontend->images.'/user-guide/edit-comments.jpg';?>" alt="">  icon in the comment you want to delete. <br>
                                    <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-17.jpg';?>" alt="" class="img-responsive center-block">        
                                </li>
                                <li>
                                    <p>b. Select  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-18.jpg';?>"> </p>
                                </li>
                                <li>
                                    Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-19.jpg';?>" alt=""> in the confirmation message to accept your deletion.
                                </li>
                            </ul>                            
                            <p class="clearfix" style="margin-bottom:10rem;">
                                <img src="<?= $this->static->frontend->images.'/user-guide/chapter-1-2-20.jpg';?>" class="img-responsive center-block" alt="" >
                            </p>
                        </div>

                        <div class="chapter-content-item chapter-2-content working-group">
                            <h4>Chapter 2 Working with group</h4>
                            <p>
                                The workgroup is a virtual community of users created for discussing and solving of defined issues, goals and tasks.
                                By uniting users into workgroups for collaboration and projects, all the communications and data related to a given project or team is organized in a single place. All tasks inside the group can be viewed in relation to each other and access to information can be shared to users outside the group if needed. 
                            </p>
                            <strong id="access-group">2.1. Access a group: </strong>
                            <p>
                            After logging in Gianty portal successfully, you will see a list of your groups under WORKGROUPS on the left pane of the page. Find your desired group and click on a group of your choice to access.
                            </p>
                            <img class="img-responsive center-block"  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-1.png'?>" alt="" class="center-block img-responsive">
                            <p>There are 3 ways to find a group</p>
                            <ul>
                                <li><strong>① Search box:</strong> allows you to quickly search for a group from your group list.</li>
                                <li><strong>② Group list:</strong> The list of groups where you are a member or manager. </li>
                            </ul>
                            There are 4 main type of group:
                            <ul>
                                <li><span style="text-decoration:underline;">i.  Company (All Gianty):</span> by default, includes all staff of the company</li>
                                <li><span style="text-decoration:underline;">ii. Team (department) related Groups:</span> by default, includes staffs of that Team (department) </li>
                                <li><span style="text-decoration:underline;">iii.    Project related Groups:</span> includes members of the project. Project manager can add or remove members per needed.</li>
                                <li><span style="text-decoration:underline;">iv. Other Groups:</span> groups created by personals for a certain purpose.</li>
                            </ul>
                            <p>
                            ③ <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-2.png'?>"  alt="">  : Allows you to access the Group management page which displays all the groups in the portal. Here, you can quickly join a group, create a group, or search for your desired group. 
                            </p>
                            <div class="text-center"><strong>Group management page</strong></div>
                            
                            <p><img class="img-responsive center-block"  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-3.png'?>" alt=""></p>

                            <p><strong>The Group management page includes the following tabs:</strong></p>
                            <ul>
                                <li><span style="text-decoration:underline;">i.Suggestion groups:</span> displays all groups where you are not a member or manager.</li>
                                <li><span style="text-decoration:underline;">ii.My groups:</span> Groups where you are a member or manager.</li>
                                <li><span style="text-decoration:underline;">iii.Invitations received:</span> Groups where you are invited to become members by Group managers.</li>
                                <li><span style="text-decoration:underline;">iv.Request received:</span> The list of all requests for joining in groups where you are a manager.</li>
                            </ul>

                            <p><strong id="create-group">2.2. Create a group:</strong></p>

                            After going to the Group page, you can add a new group so that you and your colleagues can work together or discuss specific topics as follows: 
                            <ul>
                                <li>&#9830; Click <img   src="<?= $this->static->frontend->images.'/user-guide/chapter-2-2.png'?>" alt="">  to access the Group management page</li>
                                <li>&#9830; Click <img   src="<?= $this->static->frontend->images.'/user-guide/chapter-2-4.png'?>" alt="">  at the top left corner to open the Add new group form. 
                                <img class="img-responsive center-block"  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-5.png'?>" alt="">
                                </li>
                                <li>&#9830; Enter a group name (required and from 4 to 30 characters) and description (from 0 to 255 characters),</li>
                                <li>
                            <p><strong>&#9830; Select members to invite to your group. </strong></p>
                            <ul>
                                <li>+ Input name of a person you want to add.</li>
                                <li>+ Go through the suggestion list by moving your cursor over it, then click a person.</li>
                            </ul>
                            <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-6.png'?>" alt="">
                                </li>
                                <li>
                                    &#9830; Select <strong>privacy:</strong>
                                    <ul>
                                        <li>• <strong>Public:</strong> Anyone can see and join the group</li>
                                        <li>• <strong>Private:</strong> Anyone can find the group and need an approval to join</li>
                                    </ul>
                                </li>
                                <li>
                                &#9830; Upload Group image: upload an image for your group or using default image.        
                                </li>
                                <li>
                                    &#9830; Click <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-7.png'?>" alt=""> to finish adding your new group
                                </li>
                            </ul>
                            <p><strong id="join-leave-group">2.3. Join/ Leave a group</strong></p>
                            <p><strong id="join-group">2.3.1. Join a group</strong></p>
                            <ul>
                                <li>&#9830; Click    <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-2.png'?>" alt="">   to access the Group management page</li>
                                <li>&#9830; At the Suggestion groups tab, you can see all groups where you are not a member or manager. 
                                    <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-11.png'?>" alt="" class="center-block img-responsive">
                                </li>
                            </ul>
                            <p>&#9830; There are 2 case to join a group</p>
                            <ul>
                                <li><strong>• Public group:</strong> Groups without approval required. You just click    <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-9.png'?>" alt="">  to immediately join the group.</li>
                                <li>
                                 <strong>• Private group:</strong> Groups with approval required. Click      <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-9.png'?>" alt="">  and waiting for approval from the manager or admin of the group.         
                                </li>
                            </ul>
                            <p><strong id="leave-group">2.3.2.  Leave a group</strong></p>
                            <ul>
                                <li>&#9830; Click <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-9.png'?>">   to access the Group management page</li>
                                <li>&#9830; Select <strong>My groups</strong> tab</li>
                                <li>&#9830; To leave a group, simply click <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-10.png'?>"></li>
                            </ul>
                            <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-11.png'?>"></p>
                            <div class="note-wrapper-content">
                            <strong>Note:</strong>
                            <p>
                                You cannot leave Default groups (Company group, Team group) and group that you are Manager
                            </p>
                            </div>
                            <p>
                            <strong id="edit-delete-group">2.4. Edit/ Delete a group</strong> <br>
                            <strong id="edit-group">2.4.1.  Edit a group information</strong>
                            </p>
                            Only the group managers have permission to Edit their groups
                            <ul>
                                <li>&#9830; Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-2.png'?>">  to access the Group management page</li>
                                <li>&#9830; Select <strong>My groups tab</strong></li>
                                <li>&#9830; Click <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-12.png'?>">  under the group name which you want to delete. 
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-13.png'?>"> </p>
                                </li>
                                <li>
                                    &#9830; An Edit group form will open. Enter the information you want to change.
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-14.png'?>"> </p>
                                </li>
                                <li>
                                    &#9830; Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-15.png'?>">   in the confirmation message to accept deleting the group.         
                                </li>
                            </ul>
                            <strong id="delete-group">2.4.2.  Delete a group</strong> <br>
                            <p>Only the group managers have permission to delete their groups.</p>
                            <ul>
                                <li>&#9830; Click  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-2.png'?>">  to access the Group management page</li>
                                <li>&#9830; Select <strong>My groups</strong> tab</li>
                                <li>&#9830; Click  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-16.png'?>">  under the group name which you want to delete.</li>
                            </ul>

                            <p>&#9830; Click <strong>OK</strong> in the confirmation message to accept deleting the group.</p>
                            
                            <p>
                            <strong id="accept-ignore">2.5.  Accept/ Ignore an invitation</strong>
                            </p>
                            <ul>
                                <li>• Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-2.png'?>"> to access the Group management page</li>
                                <li>• Select <strong>Invitations</strong> received tab</li>
                                <li>• Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-20.png'?>"> / <img src="<?= $this->static->frontend->images.'/user-guide/btn-cancel.png'?>">to accept/deny joining the group respectively.</li>
                            </ul>
                            
                            <p><strong id="approve-deny-request">2.6.  Approve/ Deny a request to join group</strong></p>
                            <ul>
                                <li>• Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-2.png'?>">to access the Group management page</li>
                                <li>• Select <strong>Requests</strong> received tab</li>
                                <li><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-17.png'?>"> </li>
                                <li>• Click Approve icon <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-22.png'?>"> / Deny icon <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-23.png'?>"> to approve/deny the request to join your groups respectively.</li>
                            </ul>
                            <p><strong id="group-app">2.7.  Group’s applications</strong></p>

                            After accessing a specific group, by default, you will see the Group’s application pages on the Group navigation bar. Simply click each application to use its functions.

                            <p><strong id="activity-stream">2.7.1.  Activity stream:</strong></p>

                            Displays changes on the group information and all the activities of group members. See Using the Activity Stream for more details.

                            <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-24.png'?>">  

                            <p><strong id="document">2.7.2.  Document</strong></p>
                            Allows group members to work on the same documents, such as editing a document in the group. 
                            reate a folder
                            <p>
                                <strong>&#9830; Create a folder</strong>
                            </p>
                            <p>
                                To make your content management neat and easy to find, you should create appropriate folders to store them.
                            </p>
                            <ul>
                                <li>
                                    a.  Go to the location that you want to create a folder. 
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-25.png'?>"> </p>
                                </li>
                                <li>
                                    b. Select <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-27.png'?>" width="72" height="32"> to open the New Folder form.        
                                </li>
                                <li>
                                    c. Enter a folder name, then click  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-28.png'?>" width="72" height="32"> to finish.        
                                    <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-29.png'?>">
                                </li>
                            </ul>
                            <p><strong id="upload-file">&#9830; Upload files</strong></p>
                            <ul>
                                <li>
                                    a. Go to the folder that you want to upload files
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-30.png'?>"></p>
                                </li>
                                <li>
                                    b. Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-31.png'?>" width="72" height="32">  to open the File Upload window.
                                </li>
                                <li>
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-32.png'?>"></p>
                                    c. Browse and select your desired document, then click Open to start uploading your selected files.        
                                </li>
                            </ul>
                            
                            <p><strong id="delete-file">&#9830; Delete a file</strong></p>
                                <ul>
                                    <li>
                                        a. Hover your cursor over the file you want to delete, then click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-12.png'?>">
                                        <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-33.png'?>"></p>
                                    </li>
                                    <li>
                                        b. Click OK in the confirmation message to accept your deletion.
                                        <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-34.png'?>"></p>
                                    </li>
                                </ul>
                            <p><strong id="download-file">Download a file</strong></p>
                            <ul>
                                <li>d. Hover your cursor over the file you want to download, then click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-43.jpg'?>"></li>
                                <li>e. A window will open to confirm download and click OK to start download the selected file.
                                    <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-35.png'?>">
                                </li>
                            </ul>
                            
                            <p> <strong id="calendar">2.7.3.  Calendar:</strong> Allows group members to create/edit the same events/tasks in the group calendar. (Coming soon)</p>

                            <p> <strong id="members">2.7.4.  Members:</strong> Displays the list of group members.</p>

                            <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-36.png'?>">
                            
                            <p><strong id="settings">2.7.5.  Settings</strong></p>

                            <p>Allows the group manager/ administrator only to edit the group. </p>
                            <strong id="manage-group">&#9830; Manage group information:</strong>
                            <p>
                            Group manager/ administrator can change group information such as: Group name, description, image, privacy.
                                <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-37.png'?>"></p>
                            </p>
                            
                            <p> <strong id="manage-member">&#9830; Manage member</strong> <br>
                            Group manager/ administrator can invite new members to join group.
                            </p>
                            <ul>
                                <li>
                                    • Input name of a person you want to add.
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-38.png'?>"></p>
                                </li>
                                <li>
                                    • Go through the suggestion list by moving your cursor over it, then click a person.
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-39.png'?>"></p>
                                </li>
                                <li>
                                    • Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-2-40.png'?>">  to send invitation.        
                                </li>
                                <li>
                                    • List of invitation will be shown as below.                                    
                                </li>
                            </ul>
                            <p>
                                <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-2-41.png'?>">
                            </p>
                            <div class="note-wrapper-content">
                            <span class="text-decoration:underline;"><strong>Note:</strong></span>
                            <p>
                                Before the invitation is accepted by user, you can cancel the invitation by simply clicking <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-2-42.png'?>">
                            </p>
                            </div>
                            <div style="margin-bottom:10rem;">
                                &nbsp;
                            </div>
                        </div>
                        <div class="chapter-content-item chapter-3-content working-with-news">
                            <h4>Chapter 3. Working with News</h4>
                            <p>
                            Company’s important news will be announced here. Besides, you can get news and hot trends all over the world by accessing the News page in the Company section. </p>
                            <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-3.png';?>" alt="">
                        </div>
                        <div class="chapter-content-item chapter-4-content working-with-photos">
                            <h4> Working with photos</h4>
                            
                            <p>
                                All the photo uploaded by you and your groups in activity stream will be displayed in Photos page. <br>
                                See <strong>Using the activity stream > Share a link/ file/ photo > Share a photo </strong> for how to share a photo on activity stream.
                            </p>
                            <ul>
                                <li>• Photos uploaded by admin will be displayed in Company area.</li>
                                <li>• Photos uploaded by you and member of your groups will be displayed in relevant groups.
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-4-1.png'?>"></p>
                                </li>
                            </ul>
                            <strong id="create-album">4.1. Create album</strong>
                            <ul>
                                <li>&#9830; Click  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-4.png'?>"> to open the Create Album form.
                                <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-4-2.png'?>"></p>
                                </li>
                                <li>&#9830; Enter Album name, description then browse photos to be uploaded.</li>
                                <li>&#9830; Select a group you want to share photo with.</li>
                                <li>&#9830; Click  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-4-3.png'?>"> to start uploading photo.</li>
                            </ul>
                           
                            <p>Your new created album will be displayed the area of the selected group </p>
                            <div class="note-wrapper-content">
                            <strong>Note: </strong>
                            <p>
                                Albums that created in this page will be displayed in your activity stream and activity stream of the selected groups.
                            </p>
                            </div>
                            <strong id="add-photo">4.2. Add photo</strong>
                            <p>
                                You can add photos without creating new album. Photos uploaded will be displayed in Other album.
                            </p>
                            <ul>
                                <li>
                                    • Click  <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-4-5.png'?>">  to start adding photo. An Add photo popup will appear. 
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-4-4.png'?>"></p>
                                </li>
                                <li>
                                    • Click  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-4-7.png'?>">   to add photo.
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-4-6.png'?>"></p>
                                </li>
                                <li>&#9830; Select a group you want to share the photos.</li>
                                <li>&#9830; Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-4-9.png'?>">  to start uploading photo.</li>
                            </ul>
                            <div style="margin-bottom:10rem;">
                                &nbsp;
                            </div>
                        </div>

                        <div class="chapter-content-item chapter-5-content working-with-mail">
                            <p><h4>Working with email</h4></p>
                            Outlook email inbox are connected to the portal so you can check your inbox as well as composing email as you need.
                            <p><strong id="check-inbox">5.1. Check inbox</strong></p>
                            Simply click on the email you want to read.
                            <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-5.png'?>"></p>
                            <p><strong id="compose-email">5.2. Compose an email</strong></p>
                            <ul>
                                <li>• Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-5-1.png'?>"> to open compose mail form.</li>
                                <li><img  class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-5-2.png'?>"></li>
                                <li>• Fill in the form and click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-5-3.png'?>"> to send email.</li>
                            </ul>
                            <p><strong id="reply-email">5.3. Reply an email.</strong></p>
                            <ul>
                                <li>• Click on the email you want to reply</li>
                                <li>• The reply box is displayed below the email.</li>
                                <li>• Compose your reply to that email.
                                    <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-5-2.png'?>"></p>
                                </li>
                                <li>• Click <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-5-5.png'?>"> to send the reply.</li>
                                <li>• Click  <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-5-6.png'?>"> to cancel and back to inbox</li>
                            </ul>    
                            <div style="margin-bottom:10rem;">
                                &nbsp;
                            </div>              
                        </div>
                        <div class="chapter-content-item chapter-6-content working-with-calendar">
                            <p><h4>Chapter 6: Working with Calendar</h4></p>
                                <h4>6.1.    Calendar interface</h4>
                                <p>
                                    The Calendar interface has basic components.
                                </p>
                                <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-6.png'?>">
                                <p>
                                In which: 
                                <ul>
                                    <li>① The Toolbar contains most of actions in Calendar, such as adding an event/task, switching between view modes (Day, Week, Month, Work week) and more. </li>
                                    <li>
                                    ② The Mini calendar where you can go backward/forward months by clicking  /  . Also, you can jump to your desired date by directly clicking that date.         
                                    </li>
                                    <li>
                                     ③ The Calendar View pane where you can create tasks/events quickly and view your own tasks/events.    
                                    </li>
                                    <li>
                                     ④ The Calendars pane which includes 5 types of calendar:   
                                    </li>
                                    <li>
                                        <strong>• Default group:</strong> company calendar
                                    </li>
                                    <li><strong>• Team Calendar:</strong> Calendars of your team.</li>
                                    <li><strong>• Project Calendar:</strong> Calendar of projects in which you are a member</li>
                                    <li><strong>• Other Group Calendars:</strong> Calendars of groups in which you are a member.</li>
                                    <li><strong>• Personal Calendars:</strong> Your private calendars.</li>
                                </ul>
                                </p>
                                
                                <p><strong id="create-calendar">6.2. Create a calendar</strong></p>

                                <strong id="create-group-calendar">6.2.1. Create a group related calendar</strong>
                                <p>
                                You can create a personal calendar or group calendar that can be shared with specific users or groups to your desires.
                                </p>
                                <ul>
                                    <li>&#9830; Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-14.jpg'?>"> to open the Calendar creating form.</li>
                                    <li>&#9830; Fill in fields of the form.</li>
                                </ul>
                                <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-6-1.png'?>"> </p>
                                <ul>
                                    <li><strong>• Event title:</strong> The name of the event</li>
                                    <li><strong>• Description:</strong> The description of the event</li>
                                    <li><strong>• Location:</strong> The location where the event will take place</li>
                                    <li><strong>• Category:</strong> The calendar types (team/ project/ group/ personal) which includes the event.</li>
                                    <li><strong>• Sub Category:</strong> The child of the calendar types which includes the task.</li>
                                    <li><strong>• Priority:</strong> Select the priority level of this event, including Low, Normal, High.</li>
                                    <li><strong>• Date:</strong> The starting and ending date of the event.</li>
                                    <li><strong>• Time:</strong> The starting and ending time of the event.</li>
                                    <li><strong>• All day:</strong> Ticks the checkbox to set the task duration to be all day. If check this option, the starting date/time and ending date/time will be disable.</li>
                                    <li><strong>• Repeat:</strong>  </li>
                                    <li>o Tick the Repeat checkbox if you want to create a recurring event.</li>
                                    <li>+ Repeat: Select the type for your repeating event, including daily, weekly, monthly</li>
                                    <li>+ Times: number of times the event will recur.</li>
                                    <li>o Click OK to finish repeat setting.</li>
                                    <li>• Reminder: Remind users of upcoming events</li>
                                    <li>• Attachments: Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-2.png'?>">  to attach any files
                                    <p>&#9830; Click  <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-6-3.png'?>">  to finish creating your new event; or click  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-4.png'?>">  to cancel.
                                    </p>
                                    </li>
                                </ul> 
                               
                                <div class="note-wrapper-content">
                                <p><strong>Note:</strong></p>
                                • Hover your cursors over the calendar to view summarized information of it.
                                </div>
                                <p><strong id="create-personal">6.2.2. Create a personal calendar.</strong></p>

                                For personal calendar, you may add attendees. 
                                <ul>
                                    <li>&#9830; Do the same steps with creating a group related calendar described above. </li>
                                    <li>&#9830; In the Category field, when you select Personal, then button <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-5.png'?>">                            will appear.</li>
                                </ul>                                
                                <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-6-6.png'?>"> </p>
                                <ul>
                                    <li>
                                        &#9830; Click on the button then a search box will appear, you can search member by name or email. 
                                        <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-7.png'?>" class="img-responsive center-block">  
                                    </li>
                                    <li>
                                        &#9830; Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-8.png'?>"> to validate the Add more option.        
                                    </li>
                                    <li>
                                        &#9830; Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-9.png'?>"> to finish creating your new event; or click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-10.png'?>"> to cancel        
                                    </li>
                                </ul>
                                <p>
                                <strong id="edit-delete-event">6.3. Edit/ Delete an event</strong> <br>
                                <strong id="edit-event">6.3.1. Edit an event</strong>
                                </p>
                                <ul>
                                    <li>&#9830; Access Calendar page</li>
                                    <li>&#9830; Click on the event which you want to edit to open the Add new Calendar form</li>
                                    <li>With the Month view, hover your cursors over the event you want to edit, then click on it to open the Add new Calendar form</li>
                                    <li>&#9830; Make changes on the calendar, then click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-11.png'?>"> to accept your changes.</li>
                                </ul>
                                <div class="note-wrapper-content">
                                <p><strong>Note:</strong></p>
                                Click on the screen outside the form to cancel the editing.
                                </div>

                                <p><strong id="delete-event">6.3.2.  Delete an event</strong></p>

                                <ul>
                                    <li>&#9830; Access Calendar page</li>
                                    <li>&#9830; Click on the event which you want to edit to open the Add new Calendar form</li>
                                    <li>&#9830; With the Month view, hover your cursors over the event you want to edit, then click on it to open the Add new Calendar form</li>
                                    <li>&#9830; Click<img src="<?= $this->static->frontend->images.'/user-guide/chapter-6-13.png'?>"> delete event.</li>
                                </ul>
                            <div style="margin-bottom:10rem;">
                                &nbsp;
                            </div>
                        </div>
                        <div class="chapter-content-item chapter-7-content working-with-absence">
                            <p><h4>Chapter 7: Working with Absence</h4></p>
                            
                                The Absence tool enables you to request Absence electronically for review and approval by your line leader/ manager, view previous Absence records and remaining balances at a glance. The managerial level staff can also approve request of your staff promptly.

                                <p><strong id="absence-page">7.1. Absence page interface</strong></p>

                                <p>
                                    <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-7-0.jpg'?>"> 
                                </p>
                                <div><strong>&#9830;Total days</strong></div>
                                <ul>
                                    <li>Total days =  Annual leave (a) + Overtime (b) + Un-used leave (c)</li>
                                    <li>a. Annual leave: Annual leave regulated by Viet Nam labour law</li>
                                    <li>b. Overtime:  Overtime that has been confirmed and added by HR </li>
                                    <li>c. Un-used leave: Un-used leave of previous year</li>
                                </ul>
                                <div><strong>&#9830;Used days</strong></div>
                                <ul>
                                    <li>Total days =  Annual leave (a) + Overtime (b) + Un-used leave (c)</li>
                                    <li>Used days are Absence dates that have been Approved by Manager/ Deputy Manager and those absence dates are within the current month</li>
                                </ul>
                                 <div class="note-wrapper-content">
                                <p><strong>Note:</strong>Special leave days are not included in Used days.</p>
                                </div>
                                <div><strong>&#9830;Remaining  days</strong></div>
                                <ul>
                                    <li>Remaining days = Total days - Used days</li>
                                </ul>
                                <div class="note-wrapper-content">
                                <p><strong>Note:</strong></p>
                                <ul>
                                    <li>
                                    • Absence request is officially approved only by Manager/ Deputy Manager.
                                    </li>
                                    <li>
                                    • Reviewer’s approval is only a reference information for Manager/ Deputy Manager     
                                    </li>
                                </ul>
                                </div>
                                <p><strong id="create-absence">7.2. Create an Absence request.</strong></p>
                                <p>
                                Your Absence request will be sent automatically to your Leader/ Subleader for review and Manager/ Deputy manager for approval.</p>
                                <p>
                                <ul>
                                    <li> &#9830; Access Absence page, then click  <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-7-1.png'?>" width="70" height="30"> 
                                    <p>
                                        <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-7-2.png'?>" class="img-responsive"> 
                                    </p>
                                    </li>
                                    <li>
                                       &#9830; Select Date (From, To) 
                                    </li>
                                    <li>
                                        &#9830; Click  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-7-3.png'?>"> to add more days in case of Absence date is not continuous days or haft a day
                                        <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-7-4.png'?>"> </p>
                                    </li>
                                    <li>
                                        &#9830; Select a <strong>Special leave:</strong>
                                        Special leaves are an paid Absence days
                                        <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-7-5.png'?>">
                                    </li>
                                    <li>&#9830; Enter <strong>Reason</strong> for Absence</li>
                                    <li>&#9830; Choose a <strong>Reviewer</strong> (Subleader and/or Leader name will be listed for your ease of chosen)</li>
                                    <li>&#9830; Attach a file (if any)</li>
                                    <li>&#9830; Click  <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-7-6.png'?>"> to send request</li>
                                    <li>&#9830; After submitting the request, you can follow up your Absence request by accessing Absence page
                                        <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-7-7.png'?>"> 
                                    </li>
                                </ul>
                                </p>          
                                <p><strong id="cancel-absence">7.3. Cancel a request</strong></p>
                                You are allowed to cancel a Absence request that has not been approved by Manager/ Deputy manager.
                                <ul>
                                    <li>&#9830; Access Absence page</li>
                                    <li>&#9830; Simply click <i class="fa fa-trash fa-fw"></i> to cancel request.</li>
                                </ul>
                                <p><strong id="review-approve-request">7.4. Review/ Approve requests</strong></p>
                                <p>Leader/ Sub-leader can review the request</p>
                                Manager/ Deputy manager can approve the request
                                <ul>
                                    <li>&#9830; Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-7-8.png'?>"> to leave the request pending.</li>
                                    <li>&#9830; Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-7-9.png'?>"> to reject the request.</li>
                                    <li>&#9830; Click <img src="<?= $this->static->frontend->images.'/user-guide/chapter-7-10.png'?>"> to approve the request.
                                        <img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-7-11.png'?>"> 
                                    </li>
                                    <li>
                                        &#9830; You can quickly Review/ Approve many requests at a time by selecting as many requests as you want then click  <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-7-8.png'?>">  or  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-7-9.png'?>">  or  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-7-10.png'?>"> to pending/ approve or reject the requests.
                                        <p><img class="img-responsive center-block" src="<?= $this->static->frontend->images.'/user-guide/chapter-7-12.png'?>"></p>
                                    </li>
                                    <li>
                                        &#9830; Click on the request to view details of request. Then you can validate the requests in the details page by clicking  <img src="<?= $this->static->frontend->images.'/user-guide/chapter-7-13.png'?>">  or click <img  src="<?= $this->static->frontend->images.'/user-guide/chapter-7-14.png'?>">  to cancel your action.  
                                    </li>
                                </ul> 
                                    <p><strong id="confirm-request">7.5. Confirm requests</strong></p>
                                    <p>
                                    HR will confirm the requests that approved by Manager/ Deputy manager
                                    </p>
                                    <div style="margin-bottom:10rem;">
                                        &nbsp;
                                    </div>
                        </div>
                        <div class="chapter-content-item chapter-8-content working-with-checkinout">
                            <p><h4>Working with check in|out</h4></p>
                            
                                This page allow you to check your “Check-in/out” status, your Absence status. Besides, you can quickly add new Absence request from this page
                            <ul>
                                <li>
                                    <p><strong id="general-information">1.  General information:</strong></p>
                                    <img src="<?= $this->static->frontend->images.'/user-guide/chapter-8.png'?>" class="img-responsive center-block">
                                     <div><strong>&#9830;Total days</strong></div>
                                        <ul>
                                            <li>Total days =  Annual leave (a) + Overtime (b) + Un-used leave (c)</li>
                                            <li>a. Annual leave: Annual leave regulated by Viet Nam labour law</li>
                                            <li>b. Overtime:  Overtime that has been confirmed and added by HR </li>
                                            <li>c. Un-used leave: Un-used leave of previous year</li>
                                        </ul>
                                        <div><strong>&#9830;Used days</strong></div>
                                        <ul>
                                            <li>Total days =  Annual leave (a) + Overtime (b) + Un-used leave (c)</li>
                                            <li>Used days are Absence dates that have been Approved by Manager/ Deputy Manager and those absence dates are within the current month.</li>
                                        </ul>
                                         <div class="note-wrapper-content">
                                        <p><strong>Note:</strong>Special leave days are not included in Used days.</p>
                                        </div>
                                        <div><strong>&#9830;Remaining  days</strong></div>
                                        <ul>
                                            <li>Remaining days = Total days - Used days</li>
                                        </ul>
                                        <div><strong>&#9830; Late:</strong></div>
                                        <ul>
                                            <li>Total late calculated from Jan 1st of the current year up to current date.</li>
                                        </ul>
                                </li>

                                <li>
                                    <p><strong id="check-inout">2.  Check in/out:</strong> Your check-in and check-out time will be listed here.</p>
                                    <ul>
                                        <li><strong>Check-in time from 8:01 AM </strong> will be considered as Late</li>
                                        <!-- <li><strong>Check-in time from 10:01 AM to 12:00 AM</strong> will be considered as Absence haft day (AM), you have to submit an Absence request form per company policy</li>
                                        <li><strong>Check-out time from 13:00 PM to 15:00PM</strong> will be considered as Absence haft day (PM), you have to submit an Absence request form per company policy</li> -->
                                        <li>
                                            <strong>No check-in/ check-out time:</strong> You have to contact HR to confirm your check-in/out status and reason or submit an Absence request form        
                                        </li>
                                    </ul>
                                    <div class="note-wrapper-content">
                                        •   Note: Please contact your direct Manager or HR for any special circumstances.
                                    </div>
                                </li>
                                <li>
                                    <p><strong id="absence">3.Absence:</strong> Your Absence information will be listed here. </p>
                                    <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/chapter-8-12.png'?>" alt="">In case you forgot to check in/out or took day(s) off without absence request, you will see this icon.  Simply a) click on this icon to submit new absence request or b) contact HR to confirm check in/out status.
                                    <p>
                                        <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/chapter-8-1.png'?>" alt=""> <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/chapter-8-3.png'?>" alt="">  <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/PM-3.png'?>" alt=""> Absence request has been <strong>Submitted</strong> or
                                            It has been switched to Pending status by Manager     
                                    </p>
                                    <p>
                                        <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/chapter-8-4.png'?>" alt="">  <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/chapter-8-5.png'?>" alt=""> <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/PM-1.png'?>" alt=""> Absence request has been <strong>Approved</strong> by Manager    
                                    </p>
                                    <p>
                                        <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/chapter-8-7.png'?>" alt=""> <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/chapter-8-8.png'?>" alt=""> <img width="32" height="32" src="<?= $this->static->frontend->images.'/user-guide/PM-2.png'?>" alt=""> Absence request has been <strong>Rejected</strong> by Manager
                                    </p>
                                    <div class="note-wrapper-content">
                                    • <strong>Note:</strong> Simply clicking on these icon for your Absence information.
                                    </div>
                                </li>
                            </ul>
                            <p><strong id="late">4.  Late:</strong></p>
                            <ul>
                                <li>
                                    <img src="<?= $this->static->frontend->images.'/user-guide/chapter-8-10.png'?>" width="32" height="32" alt=""> Late without approval from Manager. Please contact HR in case you have got approval from Manager         
                                </li>
                                <li>
                                    <img src="<?= $this->static->frontend->images.'/user-guide/chapter-8-11.png'?>" width="32" height="32" alt=""> Late with approval from Manager.          
                                </li>
                            </ul>
                             <p><strong id="overtime">5.  Overtime:</strong></p>
                            <ul>
                                <li>Overtime that added by HR after receiving List of OT staffs from Managers</li>
                                <li>Full: Overtime is full working day. </li>
                                <li>AM: Overtime is AM (haft day)</li>
                                <li>PM: Overtime is PM (haft day)</li>
                            </ul>
                        <div style="margin-bottom:10rem;">&nbsp;</div>
                    </div>
                </div>
<script>
            $('.chapter-content').css({
                        'height': $(window).height() - 100
            });      

            $('.link-chapter-1').on('click', function (e) {
                $('.hidden-item-chapter-1').slideToggle();
                e.preventDefault();
               var check = $(this).find('.fa');
                if(check.hasClass('fa-plus-square')){
                    $(this).find('.fa').addClass('fa-minus-square');
                    $(this).find('.fa-plus-square').removeClass('fa-plus-square');    
                }else{
                    $(this).find('.fa-minus-square').removeClass('fa-minus-square');
                    $(this).find('.fa').addClass('fa-plus-square');
                }
            });

            $('.link-chapter-2').on('click', function (e) {
                $('.hidden-item-chapter-2').slideToggle();
                e.preventDefault();
                 var check = $(this).find('.fa');
                if(check.hasClass('fa-plus-square')){
                    $(this).find('.fa').addClass('fa-minus-square');
                    $(this).find('.fa-plus-square').removeClass('fa-plus-square');    
                }else{
                    $(this).find('.fa-minus-square').removeClass('fa-minus-square');
                    $(this).find('.fa').addClass('fa-plus-square');
                }
            });

            $('.link-chapter-4').on('click', function (e) {
                $('.hidden-item-chapter-4').slideToggle();
                e.preventDefault();
                 var check = $(this).find('.fa');
                if(check.hasClass('fa-plus-square')){
                    $(this).find('.fa').addClass('fa-minus-square');
                    $(this).find('.fa-plus-square').removeClass('fa-plus-square');    
                }else{
                    $(this).find('.fa-minus-square').removeClass('fa-minus-square');
                    $(this).find('.fa').addClass('fa-plus-square');
                }
            });

            $('.link-chapter-5').on('click', function (e) {
                $('.hidden-item-chapter-5').slideToggle();
                e.preventDefault();
                 var check = $(this).find('.fa');
                if(check.hasClass('fa-plus-square')){
                    $(this).find('.fa').addClass('fa-minus-square');
                    $(this).find('.fa-plus-square').removeClass('fa-plus-square');    
                }else{
                    $(this).find('.fa-minus-square').removeClass('fa-minus-square');
                    $(this).find('.fa').addClass('fa-plus-square');
                }
            });
            
            $('.link-chapter-6').on('click', function (e) {
                $('.hidden-item-chapter-6').slideToggle();
                
                e.preventDefault();
                 var check = $(this).find('.fa');
                if(check.hasClass('fa-plus-square')){
                    $(this).find('.fa').addClass('fa-minus-square');
                    $(this).find('.fa-plus-square').removeClass('fa-plus-square');    
                }else{
                    $(this).find('.fa-minus').removeClass('fa-minus-square');
                    $(this).find('.fa').addClass('fa-plus-square');
                }
            });

            $('.link-chapter-7').on('click', function (e) {
                $('.hidden-item-chapter-7').slideToggle();
                
                e.preventDefault();
                var check = $(this).find('.fa');
                if(check.hasClass('fa-plus-square')){
                    $(this).find('.fa').addClass('fa-minus-square');
                    $(this).find('.fa-plus-square').removeClass('fa-plus-square');    
                }else{
                    $(this).find('.fa-minus-square').removeClass('fa-minus-square');
                    $(this).find('.fa').addClass('fa-plus-square');
                }
            });

            $('.link-chapter-8').on('click', function (e) {
                $('.hidden-item-chapter-8').slideToggle();
                
                e.preventDefault();
                var check = $(this).find('.fa');
                if(check.hasClass('fa-plus-square')){
                    $(this).find('.fa').addClass('fa-minus-square');
                    $(this).find('.fa-plus-square').removeClass('fa-plus-square');    
                }else{
                    $(this).find('.fa-minus-square').removeClass('fa-minus-square');
                    $(this).find('.fa').addClass('fa-plus-square');
                }
            });

            $('.gianty-homepage').on('click', function (e) {
                $('.chapter-content').show();
                
                $('.user-guide-wrapper-content .list-group').hide();
                $('.chapter-content').find('.active').removeClass('active');
                $('.gianty-portal-hompage').addClass('active');
                $('.btn-backlist').show();
                e.preventDefault();

                $('.user-guide-wrapper-content').css({
                    'overflow-y': 'visible'
                });

                $('.chapter-content').scrollTop(9);
            });

            $('.activity-stream-link').on('click', function (e) {
                $('.chapter-content').show();
                
                $('.user-guide-wrapper-content .list-group').hide();
                $('.chapter-content').find('.active').removeClass('active');
                $('.activity-stream').addClass('active');
                $('.btn-backlist').show();
                 $('.user-guide-wrapper-content').css({
                    'overflow-y': 'visible'
                });
            });

            $('.working-group-link').on('click', function (e) {
                $('.chapter-content').show();
                
                $('.user-guide-wrapper-content .list-group').hide();
                $('.chapter-content').find('.active').removeClass('active');
                $('.working-group').addClass('active');
                $('.btn-backlist').show();
                 $('.user-guide-wrapper-content').css({
                    'overflow-y': 'visible'
                });
            });

            $('.working-with-new-link').on('click', function (e) {
                $('.chapter-content').show();
                
                $('.user-guide-wrapper-content .list-group').hide();
                $('.chapter-content').find('.active').removeClass('active');
                $('.working-with-news').addClass('active');
                $('.btn-backlist').show();
                 $('.user-guide-wrapper-content').css({
                    'overflow-y': 'visible'
                });
            });
            
            $('.working-with-photos-link').on('click', function (e) {
                $('.chapter-content').show();
                
                $('.user-guide-wrapper-content .list-group').hide();
                $('.chapter-content').find('.active').removeClass('active');
                $('.working-with-photos').addClass('active');
                $('.btn-backlist').show();
                 $('.user-guide-wrapper-content').css({
                    'overflow-y': 'visible'
                });
            });

            $('.working-with-mail-link').on('click', function (e) {
                $('.chapter-content').show();
                
                $('.user-guide-wrapper-content .list-group').hide();
                $('.chapter-content').find('.active').removeClass('active');
                $('.working-with-mail').addClass('active');
                $('.btn-backlist').show();
                 $('.user-guide-wrapper-content').css({
                    'overflow-y': 'visible'
                });
            });

            $('.working-with-calendar-link').on('click', function (e) {
                $('.chapter-content').show();
                
                $('.user-guide-wrapper-content .list-group').hide();
                $('.chapter-content').find('.active').removeClass('active');
                $('.working-with-calendar').addClass('active');
                $('.btn-backlist').show();
                 $('.user-guide-wrapper-content').css({
                    'overflow-y': 'visible'
                });
            });

            $('.working-with-absence-link').on('click', function (e) {
                $('.chapter-content').show();
                $('.user-guide-wrapper-content .list-group').hide();
                $('.chapter-content').find('.active').removeClass('active');
                $('.working-with-absence').addClass('active');
                $('.btn-backlist').show();
                 $('.user-guide-wrapper-content').css({
                    'overflow-y': 'visible'
                });
            });

            $('.working-with-checkinout-link').on('click', function (e) {
                $('.chapter-content').show();
                $('.user-guide-wrapper-content .list-group').hide();
                $('.chapter-content').find('.active').removeClass('active');
                $('.working-with-checkinout').addClass('active');
                $('.btn-backlist').show();
                 $('.user-guide-wrapper-content').css({
                    'overflow-y': 'visible'
                });
            });

            $('.btn-backlist').on('click', function(e){
                $('.user-guide-wrapper-content .list-group').show();
                $('.chapter-content').find('.active').removeClass('active');
                $('.btn-backlist').hide();
                $('.user-guide-wrapper-content').css({
                    'overflow-y': 'scroll'
                });
                $('.chapter-content').hide();
            });

            $('.close-chapter-content').on('click', function (e) {
                $('.chapter-content').find('.active').removeClass('active');
                $('.user-guide-wrapper-content').removeClass('open');
                $('.chapter-content').hide();
            });

            $('.close-user-guide').on('click', function (eve) {
                if(!$(eve.target).is('.user-guide-wrapper-content', '.user-guide-wrapper-content *', '.user-guide', '.user-guide *')) {
                    $(".user-guide-wrapper-content").removeClass('open');
                }
            });
</script>