<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <meta http-equiv="X-Frame-Options" content="allow"> 
    <title>Thi Thien a <?php echo $this->abc; ?> <?= $this->redirectPage; ?> </title>    
    <link href="<?= $this->static->frontend->css ;?>/bootstrap.min.css" rel="stylesheet" type='text/css'>
    <link href="<?= $this->static->frontend->css ;?>/thithien.css" rel="stylesheet" type='text/css'>
    <link href="<?= $this->static->frontend->css ;?>/font-awesome.min.css" rel="stylesheet" type='text/css'>
    <script src="<?= $this->static->frontend->js ;?>/jquery.min.js"></script>
    <script src="<?= $this->static->frontend->js ;?>/bootstrap.min.js"></script>    
    <script src="<?= $this->static->frontend->js ;?>/thithien.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-route.min.js"></script>
    <script src="<?= $this->static->frontend->js ;?>/banners.js"></script>
    <script src="<?= $this->static->frontend->js ;?>/category.js"></script>
    <script src="<?= $this->static->frontend->js ;?>/app.js"></script>
    <script type="text/javascript">
        /*var sessionAccountId = "<?php echo $this->arrLogin['accountID']; ?>"; */ 
    </script>
</head>
<body ng-app="TTApp">
<!-- navbar -->
<div class="navbar-tt clearfix" id="navbar-tt">
  <nav class="navbar navbar-tt navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <!-- menu mobile -->
        <div class="visible-xs text-right">
          <div class="navbar-dropdown-mobile">
            <a onclick="openNav();" href="javascript:void(0)">
            <span class="fa fa-bars fa-2x"></span></a>            
          </div>  
          <span class="logo-w">
            <a href="/">              
              <img src="<?= $this->static->frontend->images ?>/logo.png" width="140" height="30" alt="Bao mua ban rao vat" title="Báo mua bán rao vặt" />
            </a>
          </span>
          <span class="top-search-mobile">
                <a href="/tim-kiem-di-dong"><i class="fa fa-search fa-2x"></i></a>
          </span>          
        </div>
        <!-- end menu mobile -->
        <div class="logo-tt">
          <a class="logo hidden-xs" href="/">
            <h1><img src="<?= $this->static->frontend->images ?>/logo.pnga" alt="Bao mua ban rao vat" title="Báo mua bán rao vặt" width="190" height="43" /></h1>
          </a>
          <a href="https://muaban.net/app?source=mbn-banner-top" class="banner-top-qc visible-lg">
              <img src="<?= $this->static->frontend->images ?>/banner/top.gif" />
          </a>          
        </div>        
      </div>
      <ul class="nav navbar-nav navbar-right hidden-xs">
        <li class="active"><a href="#">Dang Nhap</a></li>
        <li class="dropdown navbar-dropdown-right">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span class="fa fa-bars fa-2x"></span></a>
          <ul class="dropdown-menu dropdown-menu-tt " style="left:0px;top:45px">
            <li ng-repeat="item in danhmuc"><a href="#">{{item.name}}</a></li>
          </ul>
        </li>
        <li>
          <a href="/dang-tin"><span class="nav-post-news text"><i class="fa fa-newspaper-o" style="color:#ffffff;"></i>&nbsp;ĐĂNG TIN MIỄN PHÍ</span></a>
        </li> 
      </ul>
    </div>
  </nav>
</div>  
<!-- end header decktop -->
<!-- start header mobile -->
<div id="slidemenumobile" class="visible-sm visible-xs">
  <ul class="nav navbar-nav navbar-right">
    <li class="col-sm-12 col-xm-12 menu-home">
        <a href="/">
            <i class="fa fa-home"></i> Trang chủ
        </a>
    </li>
    <li class="col-sm-12 col-xm-12 menu-home">
        <a href="/tim-kiem-di-dong">
            <i class="fa fa-search"></i> Tìm kiếm
        </a>
    </li>
    <li class="col-sm-12 col-xm-12 menu-home">
        <a href="/dang-tin">
            <i class="icon icon-laptop60"></i> Đăng tin miễn phí
        </a>
    </li>

    <li class="col-sm-12 col-xm-12 menu-home">
        <a href="/trang-ca-nhan/MyFavorite">
            <i class="icon icon-common_star_favorite_bookmark_" style="font-size:18px;"></i> Tin yêu thích
        </a>
    </li>
    <li class="menu-line"></li>
    <li class="col-sm-12 col-xm-12">
      <a href="/trang-ca-nhan/SignIn">Đăng nhập</a></li>
    <li class="col-sm-12 col-xm-12">
      <a href="/trang-ca-nhan/SignUp">Đăng ký</a></li>
  </ul>
</div>
<!-- End header mobile -->
<!-- end navbar -->

<!-- Start Body Contentner -->
<div class="main-container">            
  <!-- Start page_content clearfix -->
  <div id="pageContent" class="clearfix">
        <?= $this->layout()->content;?>  
  </div>
</div>


<!-- Start Body bottom -->
<div class="tt-bottom">
  <div class="tt-bottom-contact text-center">
    <div class="container">
      <div class="contact-info col-md-12 col-sm-12 col-xs-12">
        <div class="social-icon">
          <a href="https://www.facebook.com/thithien"><span class="fa fa-facebook fa-x2"></span></a>
          <a href="http://youtube.com/c/thithien"><span class="fa fa-youtube fa-x2"></span></a>
          <a href="https://twitter.com/thithien"><span class="fa  fa-twitter fa-x2"></span></a>
          <div class="clearfix"></div>
        </div>
        <div> <span style="font-weight:bold"> CTY TNHH TM DV THI THIÊN SHALOM</span>. MST: 0313684679. SĐT: 08-xxxxxxxx</div>
        <div><span style="font-weight:bold">10 Lê Quốc Trinh, Phú Thọ Hòa, Tân Phú, Hcm</div>
        <div><span style="font-weight:bold">Giấy phép hoạt động số</span> XX/GXN-TTĐT do Bộ VHTT cấp xx/xx/xxxx.</div>
        <div>thithien.com có trách nhiệm chuyển tải thông tin. Không chịu bất kỳ trách nhiệm nào từ các tin này. <a href="#"> xem chi tiết</a> </div>
      </div>
    </div>
  </div>
</div>
<!-- end body bottom -->

<script>

function openNav() {
    document.getElementById("slidemenumobile").style.width = "250px";
}

function closeNav() {
    document.getElementById("slidemenumobile").style.width = "0";
}
</script>
<?php if($this->controllerName == "dang-ky" && $this->iSubmitTime >= 3){ ?>
<script type="text/javascript">
    var onloadCallback = function() {
        grecaptcha.render('html_element', {
          'sitekey' : '6Lc8Ww4UAAAAADex6QFz4YTmWdUW9nB6a6AQTY8z'
        });
    };
    $(document).ready(function(){
      $('.checkbox').on('click', function(){
        $(this).toggleClass('checked');
        var checkBoxes = $('.checkbox input[type="checkbox"]');
        checkBoxes.prop("checked", !checkBoxes.prop("checked"));
      });
    })
</script>
 <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
        async defer></script>
<?php } ?>

</body>
</html>