<?php
$specialDay = $this->specialDay;
$types      = $this->types;
$type       = $specialDay['type'];
$title  =   ($specialDay['type'] == 1) ? 'Holiday' : 'Compensation';
$title  =   ($specialDay['type'] == 3) ? 'Paid leave' : $title;
?>

<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-group"></i>
        <span class="capitalize"><?php echo $title; ?></span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <ul id="myTab" class="nav nav-tabs" role="tablist">
        <li class="<?php if($type ==1 ) echo 'active';?>"><a href="<?php echo BASE_ADMIN_URL.'/specialday?type=1'; ?>"  >Holiday</a></li>
        <li class="<?php if($type ==2 ) echo 'active';?>"><a href="<?php echo BASE_ADMIN_URL.'/specialday?type=2'; ?>"  >Compensation</a></li>
        <li class="<?php if($type ==3 ) echo 'active';?>"><a href="<?php echo BASE_ADMIN_URL.'/specialday?type=3'; ?>"  >Paid leave</a></li>
    </ul>
    <div class="tab-content">
        <div class="title-content bg-blue clearfix">
        <h5 class="white bold pull-left capitalize">Edit <?php echo $title; ?></h5>
    </div><!-- title-content -->
        <div class="widget-content">
        <form method="post">
            <div id="general" class="general">
                <ul>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Name</h6>
                        <input type="text" name="name" value="<?php echo $specialDay['name']; ?>" class="w500">
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Type</h6>
                        <input class="w500" disabled type="text"  value="<?php echo $types[$specialDay['type']]; ?>" >
                        <input   type="hidden"  name="type" value="<?php echo $specialDay['type']; ?>">
                    </li>

                    <?php if($type == 3 ){?>
                        <li class="clearfix">
                            <h6 class="bold pull-left">No date</h6>
                            <input class="w500" name="no_date"  type="text"  value="<?php echo $specialDay['no_date']; ?>" >
                        </li>
                    <?php } else{?>
                        <li class="clearfix">
                            <h6 class="bold pull-left">Date from</h6>
                            <input class="date_time_picker"  onkeypress="return false" type="text"  name="date_from" value="<?php echo Core_Common::formatDateTime($specialDay['date_from']); ?>" class="w500">
                        </li>

                        <li class="clearfix">
                            <h6 class="bold pull-left">Date to</h6>
                            <input class="date_time_picker"  onkeypress="return false" type="text"  name="date_to" value="<?php echo Core_Common::formatDateTime($specialDay['date_to']); ?>" class="w500">
                        </li>
                    <?php }?>

                    <li class="clearfix">
                        <h6 class="bold pull-left">Description</h6>
                        <textarea name="description" class="w500"><?php echo $specialDay['description']; ?></textarea>
                    </li>


                </ul>
                <div class="footer-btn-tab clearfix">
                    <a href="javascript:void(0);" class="back grey bor-raduis4" data-action="back-page">Back</a>
                    <a href="javascript:void(0);" class="save white bor-raduis4 bg-blue" onclick="submitForm(); return false;">Save change</a>
                </div><!--footer-btn-tab-->
            </div><!-- add group -->
        </form>
    </div><!-- widget-content -->
    </div>
</div><!-- container-content -->
<script type="text/javascript">
    $(function() {
        $('.error-report').remove();

        <?php
        if(!empty($this->arrError)) {
            foreach ($this->arrError as $error) {
                ?>
        var html = '';
        html = '<span class="margin-10 red error-report"><?php echo $error['message']; ?></span>';
        $('[name="<?php echo $error['field']; ?>"]').after(html);
        <?php
            }
        }
    ?>
    });
    function submitForm()
    {
        $('form').submit();
    }


</script>