<?php
$type   = $this->type;
$title  =   ($type == 1) ? 'Holiday' : 'Compensation';
$title  =   ($type == 3) ? 'Paid leave' : $title;

?>
<div class="title-page mar-bot15">
    <h4>
       <i class="fa fa-gift"></i>
        <span class="capitalize"><?php echo $title; ?></span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <ul id="myTab" class="nav nav-tabs" role="tablist">
        <li class="<?php if($type ==1 ) echo 'active';?>"><a href="<?php echo BASE_ADMIN_URL.'/specialday?type=1'; ?>"  >Holiday</a></li>
        <li class="<?php if($type ==2 ) echo 'active';?>"><a href="<?php echo BASE_ADMIN_URL.'/specialday?type=2'; ?>"  >Compensation</a></li>
        <li class="<?php if($type ==3 ) echo 'active';?>"><a href="<?php echo BASE_ADMIN_URL.'/specialday?type=3'; ?>"  >Paid leave</a></li>
    </ul>
    <div class="tab-content">
        <div class="title-content bg-blue clearfix">
        <!-- <h5 class="white bold pull-left capitalize"> <?php echo $title; ?></h5> -->
        <ul class="function-header pull-right">
            <li>
                <a href="<?php echo BASE_ADMIN_URL.'/specialday/add?type='.$this->type;?>">
                    <i class="fa fa-plus"></i>
                    <span class="capitalize">add new</span>
                </a>
            </li>
        </ul>
    </div><!-- title-content -->
        <div class="widget-content">
        <div class="container-table">
            <div class="table-responsive">
                <table id="table-content" class="display responsive nowrap table table-hover table-condensed" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th width="7%"><div class="checkbox-custom checkbox-primary"><input type="checkbox" id="inputUnchecked" data-action="check-all"/><label for="inputUnchecked"></label></div></th>
                        <th width="7%">No.</th>
                        <th>Name</th>
                        <?php if($type != 3 ){?>
                            <th>Date from</th>
                            <th>Date to</th>
                        <?php }?>
                        <th>No date</th>
                        <th>Description</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div><!-- table-responsive -->
        </div><!-- container-table -->
    </div><!-- widget-content -->
    </div>
</div><!-- container-content -->

<script>
    $(document).ready(function() {

        $('#table-content tbody').on('click', 'td', function(e){
            if($(this).index() > 0  && $(this).index() != 7)
            {
                var action = $(this).parent('tr').find('td').eq(2).find('a');
                hrefRedirect(action);
            }

        });

        $('body').on('click','[data-action="check-all"]',function(){
            var _this = $(this);
            var checkboxItems = $( '[data-action="check-delete"]');
            if(_this.is(':checked'))
                doChecked(checkboxItems,true);
            else
                doChecked(checkboxItems,false);
        });
        var DataTable  = $('#table-content').DataTable( {
            "dom": '<"top"<"margin-10 pull-left delete-ids">l <"margin-10 group-type"> pf <"clear">>rt<"bottom"ip<"clear">>',
            "processing": true,
            "serverSide": true,
            "bSort":      false,
            "ajax": "<?php echo BASE_ADMIN_URL."/specialday/lstspecialday"; ?>",
            "columns": [
                { "data": "checkbox_delete" },
                { "data": "id" },
                { "data": "name" },
                <?php if($type != 3 ){?>
                { "data": "date_from" },
                { "data": "date_to" },
                <?php }?>
                { "data": "no_date" },
                { "data": "description" },
                { "data": "actions" }
            ]
        } );

        $("div.delete-ids").prepend('<a href="javascript:void(0);"><i data-action="specials-day--delete" class="fa fa-trash fa-lg"></i><a>');
        // Apply the search
        DataTable.columns(0).every( function () {
            this
                .search('<?php echo $this->type; ?>')
                .draw();
        } );

        $('body').on('click','[data-action="special-day-delete"]', function(){
            if(confirm('Do you want to delete ?'))
            {

                var _this = $(this);
                var arrId = [_this.attr('data-value')];
                $.post("<?php  echo BASE_ADMIN_URL.'/specialday/delete'; ?>",{'special_ids':arrId}, function(data){
                    if(data.error)
                    {
                        alert(data.message);
                    }
                    else{
                        DataTable
                            .row( _this.parents('tr') )
                            .remove()
                            .draw();
                    }

                },'json');
            }
        });
//
        $('body').on('click','[data-action="specials-day--delete"]', function(){
            if(confirm('Do you want to delete ?'))
            {
                var arrCheck = Array();
                var checkboxItems = $( '[data-action="check-delete"]');
                $.each(checkboxItems,function(index,value){
                    var element = $(this);
                    if(element.is(':checked'))
                        arrCheck.push(element.val());
                });
                if(arrCheck.length)
                {
                    $.post("<?php  echo BASE_ADMIN_URL.'/specialday/delete'; ?>",{'special_ids':arrCheck}, function(){
                        $.each(checkboxItems,function(index,value) {
                            var _this = $(this);
                            DataTable
                                .row( _this.parents('tr') )
                                .remove();
                        });
                        $('[data-action="check-all"]').prop('checked',false);
                        DataTable.draw();
                    },'json');
                }

            }
        });

        $('[data-hidden="group-type"]').remove();


        function doChecked(checkboxItems, checked){
            $.each(checkboxItems,function(index,value){
                $(this).prop('checked',checked);
            });
        }

    } );
</script>