<script src="<?= $this->static->frontend->js ;?>/detailCtrl.js"></script>
<title-url></title-url>
<div ng-controller="detailCtrl" id="PageNewsDetail" class="container clearfix panel panel-default">
  <title-news-url></title-news-url>
  <div class="panel-heading text-left title-news-url">

    <span><a href="">Trang chủ</a></span>
    <span class="fa fa-arrow-right"></span>
    <span><a href="">TP.HCM</a></span>
    <span class="fa fa-arrow-right"></span>
    <span><a href="">Việc làm - Tuyển sinh</a></span>
    <span class="fa fa-arrow-right"></span>
    <span><a href="">Việc tìm người</a></span>
    <span class="fa fa-arrow-right"></span>
    <span><a href="">Giáo viên - gia sư</a></span>          
  </div>


  <div class="panel-body bodyPanelNewsDetail">
    <div class="container">
      <div class="row">              
        <div id="colMenu" class="col-menu">            
          <ul class="menu-item" id="menu" >
            <li><div class="text-center"><a href="#"><i class="fa fa-car fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-motorcycle fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-home fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-laptop fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-plug fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-mobile-phone fa-3x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-tv fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-video-camera fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-television fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-life-ring fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-gift fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-truck fa-2x"></i></a></div></li>
            <li><div class="text-center"><a href="#"><i class="fa fa-gear fa-2x"></i></a></div></li>
          </ul>              
        </div>
        <!-- start col left -->
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 news-detail-col-left">
          <!-- start news detail -->
          <div id="NewsDetail" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          	<input type="hidden" id="returnUrl" value="<?= $this->returnUrl; ?>" />
          	<input type="hidden" id="newsId" value="<?= $this->newsId; ?>" />
            <div class="news-detail-title">            
              <h1>Cần Sinh viên dạy Toán Lý Hoá lớp 8, Bình Thạnh</h1>
            </div>
            <div class="news-detail-price clearfix">
              <span class="float-left">
                  <i class="fa fa-dollar"></i>&nbsp;
                  2.000.000 đ
              </span>
              <span class="float-left"><i class="fa fa-map-marker"></i>&nbsp;Quận Bình Thạnh - TP.HCM</span>
              <span class="float-left"><i class="fa fa-clock-o"></i>&nbsp;Ngày 21/11/2016</span>
              <span class="float-left"><i class="fa fa-id-badge"></i>&nbsp;Mã tin: 35706295</span>
            </div>

            <!-- slide hinh -->
            <div id="myCarousel" class="carousel slide news-detail-image" data-ride="carousel">              

              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox">
                <div class="item active">
                  <img src="./images/slide/hinh1.jpg" alt="hinh 1">
                </div>

                <div class="item">
                  <img src="./images/slide/hinh2.jpg" alt="hinh 2">
                </div>

                <div class="item">
                  <img src="./images/slide/hinh3.jpg" alt="hinh 3">
                </div>

                <div class="item">
                  <img src="./images/slide/hinh4.jpg" alt="hinh 4">
                </div>

                <div class="item">
                  <img src="./images/slide/hinh5.jpg" alt="hinh 5">
                </div>
              </div>

              <!-- Left and right controls -->
              <a class="left carousel-control arrow-slide" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control arrow-slide" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>

              <!-- Indicators -->
              <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active">
                  <img alt="" src="./images/slide/hinh1.jpg">
                </li>
                <li data-target="#myCarousel" data-slide-to="1">
                  <img alt="" src="./images/slide/hinh2.jpg">
                </li>
                <li data-target="#myCarousel" data-slide-to="2">
                  <img alt="" src="./images/slide/hinh3.jpg">
                </li>
                <li data-target="#myCarousel" data-slide-to="3">
                  <img alt="" src="./images/slide/hinh4.jpg">
                </li>
                <li data-target="#myCarousel" data-slide-to="4">
                  <img alt="" src="./images/slide/hinh5.jpg">
                </li>
              </ol>
            </div>
            <!-- end slide hinh -->
            <!-- more info -->
            <div id="news-detail-approved" class="news-detail-approved clearfix">
              <span>
                <span style="display:inline-block">
                    <i class="fa fa-check" style="color:#46F20D;"></i>
                    &nbsp;Duyệt tin bởi&nbsp;<strong> Dang Hien</strong>
                    &nbsp;<img width="30" height="30" alt="avatar" class="approved-avatar" src="#">
                </span>
              </span>
            </div>


            <div class="news-detail-price clearfix">
              <div class="col-md-2 col-sm-2 col-xs-3 price-name">Mức lương:</div>
              <div class="col-md-10 col-sm-10 col-xs-9 price-value">
                  2.000.000 đ
              </div>
            </div>

            <div class="news-detail-contact clearfix">
              <div class="clearfix">
                <div class="col-md-2 col-sm-2 col-xs-3 price-name">Liên hệ:</div>
                <div class="col-md-10 col-sm-10 col-xs-9 contact-name">thầy Sơn</div>
              </div>
              <div class="clearfix">
                <div class="col-md-2 col-sm-2 col-xs-3 price-name">Điện thoại:</div>
                <div class="col-md-10 col-sm-10 col-xs-9 contact-mobile">
                  <span data-bind="visible:ShowMobile()==false">0902675969</span>                    
                </div>
              </div>
            </div>  
            <!-- news detail -->
            <div class="news-detail-body overflow clearfix">
                Cần Sinh viên dạy Toán Lý Hoá lớp 8 tại Chu Văn An, Bình Thạnh, 5 buổi/tuần, 2tr/tháng, website: www.giasuductai.com. Gia sư vui lòng liên hệ: 135/6 Tân Kỳ Tân Quý, P Tân Sơn Nhì, Tân Phú, Tel: 0905.35.49.48 -0902.67.59.69.
            </div>
            <!-- detail technic -->            
        	<detail-properties info="newsDetail" ng-if="ntype === 'properties'"></detail-properties>            
        	<detail-job info="newsDetail" ng-if="ntype === 'job'"></detail-job>
        	<detail-car info="newsDetail" ng-if="ntype === 'car'"></detail-car>
        	<detail-bike info="newsDetail" ng-if="ntype === 'bike'"></detail-bike>
            <!-- end more info -->

            <!-- social info -->
            <div class="news-detail-social clearfix" id="dvEditClassified">
              <div class="col-md-7 col-sm-7 col-xs-12 favorite" style="padding:0px">
                <span>
                  <a title="Bỏ thích/Thích">
                    <i class="fa fa-star-o fa-2x" style="font-size:18px;" data-bind="style:{color:IsFavorite()==false? '#23527c':'#eda703'}"></i>
                    <span data-bind="text:IsFavorite()?'Bỏ thích':'Thích'">Thich</span>
                  </a>
                </span>
                <span data-bind="click: ValidPass.ViewEdit">
                  <a href="#"><i class="fa fa-edit"></i>&nbsp;Sửa tin</a>
                </span>
                <span>
                  <a title="Báo vi phạm" data-bind="click:ShowFeedBack"><i class="fa fa-warning fa-2x" style="font-size:18px;"></i>&nbsp;Báo vi phạm</a>
                </span>
                <span data-bind="click:PrintDetail, visible: ShowPrint">
                  <a title="In tin"><i class="fa fa-print fa-2x" style="font-size:18px"></i>&nbsp;In nội dung tin</a>
                </span>
              </div>
              <div class="col-md-5 col-sm-5 col-xs-12 social">
                <span class="fb-like" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></span>
                <span>
                  <span class="g-plusone" data-size="medium" data-annotation="none"></span>
                </span>
                <span>
                  <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
                </span>
              </div>
            </div>
            <!-- end socical info -->
          </div>                
          <!-- end news detail -->                              
          <!-- start relate news -->
          <div class="news-relate-content col-sm-12 col-xs-12">
            <!--Classified Similar-->
            <div class="new-list-relate">
              <h4 class="title">
                  <span>Tin rao vặt tương tự</span>
              </h4>
              <!-- news 1 -->
              <div class="news-box-list-content">
                <a class="news-image" title="Cần Sinh viên dạy lớp 2 tại Ung Văn Khiêm, Bình Thạnh," href="https://muaban.net/giao-vien-gia-su-quan-binh-thanh-l5919-c1110/can-sinh-vien-day-lop-2-tai-ung-van-khiem-binh-thanh--id35706241">
                        <img title="Cần Sinh viên dạy lớp 2 tại Ung Văn Khiêm, Bình Thạnh," alt="Cần Sinh viên dạy lớp 2 tại Ung Văn Khiêm, Bình Thạnh," src="https://cdn.muaban.net/cdn/images/thumb-list/201611/21/054/7609f0729bea467183a04da1a4f63ae3.jpg" width="120" height="90" />
                </a>
                <a title="Cần Sinh viên dạy lớp 2 tại Ung Văn Khiêm, Bình Thạnh," href="https://muaban.net/giao-vien-gia-su-quan-binh-thanh-l5919-c1110/can-sinh-vien-day-lop-2-tai-ung-van-khiem-binh-thanh--id35706241">
                  <div class="content">
                    <h2 class="title">Cần Sinh viên dạy lớp 2 tại Ung Văn Khiêm, Bình Thạnh,</h2>
                    <span class="price">2.000.000 đ</span>
                    <span class="address"><span class="fa fa-map-marker"></span> Quận Bình Thạnh, TP.HCM</span>
                    <span class="date">21/11/2016</span>
                  </div>
                </a>
              </div>
              <!-- news 2 -->
              <div class="news-box-list-content">
                <a class="news-image" title="Cần Gia sư dạy Tiếng Anh giao tiếp cơ bản, Bình Thạnh" href="https://muaban.net/giao-vien-gia-su-quan-binh-thanh-l5919-c1110/can-gia-su-day-tieng-anh-giao-tiep-co-ban-binh-thanh-id35204223">
                  <img title="Cần Gia sư dạy Tiếng Anh giao tiếp cơ bản, Bình Thạnh" alt="Cần Gia sư dạy Tiếng Anh giao tiếp cơ bản, Bình Thạnh" src="https://cdn.muaban.net/cdn/images/thumb-list/201610/20/916/ce589aafe1ca4a78afa8585ee4736f88.jpg" width="120" height="90" />
                </a>
                <a title="Cần Gia sư dạy Tiếng Anh giao tiếp cơ bản, Bình Thạnh" href="https://muaban.net/giao-vien-gia-su-quan-binh-thanh-l5919-c1110/can-gia-su-day-tieng-anh-giao-tiep-co-ban-binh-thanh-id35204223">
                  <div class="content">
                    <h2 class="title">Cần Gia sư dạy Tiếng Anh giao tiếp cơ bản, Bình Thạnh</h2>
                    <span class="price">1.800.000 đ</span>
                    <span class="address"><span class="fa fa-map-marker"></span> Quận Bình Thạnh, TP.HCM</span>
                    <span class="date">23/10/2016</span>
                  </div>
                </a>
              </div>                                
            </div>  
          </div> 
          <!-- end relate news --> 
          <!-- start read news -->
          <div class="ViewedItem col-sm-12 col-xs-12">
            <div class="news-home home-viewed visible-lg clearfix" style="margin-top:30px; ">
              <div class="news-ctl-box">
                  <h2 class="title"><span>Tin đã xem</span></h2>
              </div>
              <div class="home-viewed-content clearfix">
                <ul class="home-viewed-list clearfix" id="home-viewed-list">
                  <li>
                    <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-detail" data-gtm-action="home-favorite-posting-click" title="Cần Sinh viên dạy Toán Lý Hoá lớp 8, Bình Thạnh" href="https://muaban.net/giao-vien-gia-su-quan-binh-thanh-l5919-c1110/can-sinh-vien-day-toan-ly-hoa-lop-8-binh-thanh-id35706295">
                      <span class="viewed-item clearfix">
                        <span class="viewed-item-img">
                            <img title="Cần Sinh viên dạy Toán Lý Hoá lớp 8, Bình Thạnh" alt="Cần Sinh viên dạy Toán Lý Hoá lớp 8, Bình Thạnh" src="https://cdn.muaban.net/cdn/images/thumb-list/201611/21/101/8ea19e6add3a44729be7c9ea7191b1fa.jpg" width="120" height="90" />
                        </span>
                        <span class="viewed-item-body">Cần Sinh viên dạy Toán Lý Hoá lớp 8, Bình Thạnh</span>
                        <span class="viewed-item-price">2.000.000 đ</span>
                      </span>
                    </a>
                  </li>
                  <li>
                    <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-detail" data-gtm-action="home-favorite-posting-click" title="Cho thuê tầng trệt làm vp, bán hàng online, để ở hoặc làm xưởng may..." href="https://muaban.net/nha-hem-ngo-quan-12-l5909-c3407/cho-thue-tang-tret-lam-vp-ban-hang-online-de-o-hoac-lam-xuong-may--id35674651">
                      <span class="viewed-item clearfix">
                        <span class="viewed-item-img">
                          <img title="Cho thuê tầng trệt làm vp, bán hàng online, để ở hoặc làm xưởng may..." alt="Cho thuê tầng trệt làm vp, bán hàng online, để ở hoặc làm xưởng may..." src="https://cdn.muaban.net/cdn/images/thumb-list/201611/19/934/f168cfd5f2ce468c9a413a1d07941dd3.jpg" width="120" height="90" />
                        </span>
                        <span class="viewed-item-body">Cho thuê tầng trệt làm vp, bán hàng online, để ở hoặc làm xưởng may...</span>
                        <span class="viewed-item-price">4.500.000 đ</span>
                      </span>
                    </a>
                  </li>
                  <li>
                    <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-detail" data-gtm-action="home-favorite-posting-click" title="Cho thuê tầng trệt làm vp, bán hàng online, để ở hoặc làm xưởng may..." href="https://muaban.net/nha-hem-ngo-quan-12-l5909-c3407/cho-thue-tang-tret-lam-vp-ban-hang-online-de-o-hoac-lam-xuong-may--id35674651">
                      <span class="viewed-item clearfix">
                        <span class="viewed-item-img">
                          <img title="Cho thuê tầng trệt làm vp, bán hàng online, để ở hoặc làm xưởng may..." alt="Cho thuê tầng trệt làm vp, bán hàng online, để ở hoặc làm xưởng may..." src="https://cdn.muaban.net/cdn/images/thumb-list/201611/19/934/f168cfd5f2ce468c9a413a1d07941dd3.jpg" width="120" height="90" />
                        </span>
                        <span class="viewed-item-body">Cho thuê tầng trệt làm vp, bán hàng online, để ở hoặc làm xưởng may...</span>
                        <span class="viewed-item-price">4.500.000 đ</span>
                      </span>
                    </a>
                  </li>
                </ul>                                            
              </div>
            </div>
          </div>
          <!-- end read news -->
        </div>
        <!-- end col left -->
        <!-- start col right -->
        <div class="col-lg-6 col-md-6 hidden-sm hidden-xs news-detail-col-right">
          <!-- start reminder -->
          <div class="tips_main">
            <span class="tips_title">MUA HÀNG AN TOÀN</span>
            <ul>
              <li><span class="sprite_common_bullet_check_red"></span>KHÔNG trả tiền trước khi nhận hàng.</li>
              <li><span class="sprite_common_bullet_check_red"></span>Kiểm tra hàng cẩn thận, đặc biệt với hàng đắt tiền.</li>
              <li><span class="sprite_common_bullet_check_red"></span>Hẹn gặp ở nơi công cộng.</li>
              <li><span class="sprite_common_bullet_check_red"></span>Nếu bạn mua hàng hiệu, hãy gặp mặt tại cửa hàng để nhờ xác minh, tránh mua phải hàng giả.</li>
            </ul>
            <span class="vi_tips_footer">Tìm hiểu thêm về <a onclick="return xt_click(this,'C',xtn2,'buy_and_sell_safety_tip', 'N')" href="http://trogiup.chotot.com/mua-ban-an-toan">An toàn mua bán</a>.</span>
          </div>
          <!-- end reminder -->
        </div>  
        <!-- end col right -->
    </div>  
    </div>
  </div>    
</div>