<?php
// account info
$accountInfo    =  $this->accountInfo;
//var_dump($accountInfo);
?>
<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-user"></i>
        <span class="capitalize">User</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <!-- <div class="title-content bg-blue clearfix">
        <h5 class="white bold pull-left capitalize">User <?php echo $accountInfo['name']; ?></h5>
    </div> --><!-- title-content -->
    <div class="widget-content-user">
        <div class="container-fluid">
            <div class="row clearfix">
                <div class="col-sm-3 border-right">
                    <?php echo $this->render('usersearch.phtml'); ?>
                </div>
                <div class="col-sm-9">
                    <div class="all-info-user">
                        <ul class="tabs-menu-info mar-bot20 clearfix">
                            <li><a href="<?php echo BASE_ADMIN_URL.'/user/summary?account_id='.$accountInfo['account_id'];?>">Summary</a></li>
                            <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="javascript:void(0);">General</a></li>
                            <li ><a href="<?php echo BASE_ADMIN_URL.'/user/personal?account_id='.$accountInfo['account_id'];?>">Personal</a></li>
                            <li><a href="<?php echo BASE_ADMIN_URL.'/user/jobuser?account_id='.$accountInfo['account_id'];?>">Job</a></li>
                            <li><a  href="<?php echo BASE_ADMIN_URL.'/user/achievement?account_id='.$accountInfo['account_id'];?>">Achievement</a></li>
                        </ul><!-- tabs-menu-info -->
                        
                        <div><?php echo $this->message;?></div>
                        <div class="tabs-child">
                            <form action="<?php echo BASE_ADMIN_URL.'/user/general'?>" method="post">
                                <input type="hidden" name="account_id" value="<?php echo $accountInfo['account_id']?>"/>
                            <div id="general" class="general user-general">
                                <ul>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Family name</h6>
                                        <input type="text" name="first_name" value="<?php echo $accountInfo['first_name']; ?>" class="w500">
                                    </li>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Name</h6>
                                        <input type="text" name="last_name" value="<?php echo $accountInfo['last_name']; ?>" class="w500">
                                    </li>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">ID</h6>
                                        <input type="text" name="id" value="<?php echo $accountInfo['id']; ?>" class="w500">
                                    </li>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Team</h6>
                                        <div class="combobox w500 pull-left">
                                            <span class="arrow"></span>
                                            <?php if(isset($this->groupsTeam)) { ?>
                                            <select name="team_id" class="combobox-group bor-raduis4">
                                                <option value="0"></option>
                                                <?php foreach($this->groupsTeam as $team) { ?>
                                                    <option value="<?php echo $team['group_id']; ?>"
                                                        <?php if( $accountInfo['team_id'] == $team['group_id']) echo 'selected';  ?> >
                                                        <?php echo $team['group_name']; ?>
                                                    </option>
                                                <?php }?>
                                            </select>
                                            <?php } ?>
                                        </div><!-- bombobox -->
                                    </li>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Position</h6>
                                        <div class="combobox w500 pull-left">
                                            <span class="arrow"></span>
                                            <select name="position" class="combobox-group bor-raduis4">
                                                <option value="0">     </option>
                                                <?php foreach($this->positions['data'] as $key=>$position) { ?>
                                                    <option value="<?php echo $position['general_id']; ?>"
                                                        <?php if( $accountInfo['position'] == $position['general_id']) echo 'selected';  ?> >
                                                        <?php echo $position['name']; ?>
                                                    </option>
                                                <?php }?>
                                            </select>
                                        </div><!-- bombobox -->
                                    </li>

                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Level</h6>
                                        <div class="combobox w500 pull-left">
                                            <span class="arrow"></span>
                                            <select name="level" class="combobox-group bor-raduis4">

                                                <?php foreach($this->levels as $key=>$level) { ?>
                                                    <option value="<?php echo $key; ?>"
                                                        <?php if( $accountInfo['level'] == $key) echo 'selected';  ?> >
                                                        <?php echo $level; ?>
                                                    </option>
                                                <?php }?>
                                            </select>
                                        </div><!-- bombobox -->
                                    </li>

                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Working email</h6>
                                        <input type="text" name="email" value="<?php echo $accountInfo['email']; ?>" class="w500">
                                    </li>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Skype</h6>
                                        <input type="text" name="skype_account" value="<?php echo $accountInfo['skype_account']; ?>" class="w500">
                                    </li>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Birthday</h6>
                                        <input class="date_time_picker"  onkeypress="return false" type="text"  name="birthday" value="<?php echo $accountInfo['birthday']; ?>" class="w500">
                                    </li>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Phone</h6>
                                        <input type="text"  name="phone" value="<?php echo $accountInfo['phone']; ?>" class="w500">
                                    </li>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Contact address</h6>
                                        <input type="text"  name="contact_address" value="<?php echo $accountInfo['address']; ?>" class="w500">
                                    </li>
                                    <li class="clearfix">
                                        <h6 class="bold pull-left">Personal email</h6>
                                        <input type="text"  name="personal_email" value="<?php echo $accountInfo['personal_email']; ?>" class="w500">
                                    </li>
                                    <li class="clearfix avatar-form">
                                        <h6 class="bold pull-left">Avartar</h6>
                                        <div class="container-img-avartar pull-left bor-raduis4">
                                            <img id="avatar" src="<?php echo $accountInfo['image_tag']; ?>" width="100%" height="100%"/>
                                        </div><!--container-img-avartar-->
                                        <input type="hidden" name="image_name" value="<?php echo $accountInfo['image_tag']; ?>"/>
                                        <input type="hidden" name="picture" value="<?php echo $accountInfo['picture']; ?>"/>

                                        <span class="file pull-left bor-raduis4">Browse
                                            <input type="file"  id="chosenImage" class="file-get img-source" onchange="installCheckImageUpload(this)">
                                        </span>
                                    </li>
                                </ul>
                                <div class="footer-btn-tab clearfix">
                                    <a href="javascript:void(0);" class="back grey bor-raduis4" data-action="back-page">Back</a>
                                    <a href="javascript:void(0);" class="save white bor-raduis4 bg-blue" onclick="submitForm(); return false;">Save change</a>
                                </div><!--footer-btn-tab-->
                            </div><!-- summary -->
                            </form>
                        </div><!-- tabs-child -->
                    </div><!-- all-info-user -->
                </div>
            </div><!-- row -->
        </div><!-- container-fluid -->
    </div><!-- widget-content -->
</div><!-- container-content -->
<script>
    /*check file type*/
    function installCheckImageUpload(sender)
    {
        var inputHiddenElement  = $('[name="picture"]');
        var inputImageName      = $('[name="image_name"]');
        var inputImage  = $('#avatar');

//        sender,urlUpload,jsonData,inputHiddenElement,inputImage
        var jsonData    = [{'input_name':'f','input_val':'avatar'}];
        checkImageUpload(sender,baseurl+'/upload/index',jsonData,inputHiddenElement,inputImage,inputImageName);
    }
    function submitForm() {
    	$("form").submit();
       
    }


</script>