<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-user"></i>
        <span class="capitalize">User</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <div class="title-content bg-blue clearfix">
        <h5 class="panel-title white bold pull-left capitalize">User List</h5>
        <ul class="function-header pull-right">
            <li>
                <a href="<?php echo BASE_ADMIN_URL.'/user/exporttoexcel'?>">
                    <i class="fa fa-file-text-o"></i>
                    <span class="capitalize">export</span>
                </a>
            </li>
<!--            <li>-->
<!--                <a href="#">-->
<!--                    <i class="fa fa-plus"></i>-->
<!--                    <span class="capitalize">add new</span>-->
<!--                </a>-->
<!--            </li>-->
        </ul>
    </div><!-- title-content -->
    <div class="widget-content">
        <div class="container-table">
            <div class="table-responsive">
                <table id="table-content" class="display responsive" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th width="7%">ID</th>
                        <th>Family name</th>
                        <th>Name</th>
                        <th>Mail</th>
                        <th>Avatar</th>
                        <th>Team</th>
                        <th>Position</th>
                        <th>Active</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div><!-- table-responsive -->
        </div><!-- container-table -->
    </div><!-- widget-content -->
</div><!-- container-content -->
<script>
    $(document).ready(function() {
        $('#table-content tbody').on('click', 'td', function(e){
            if($(this).index() > 0 && $(this).index() != 7)
            {

                var action = $(this).parent('tr').find('td').eq(1).find('a');
                hrefRedirect(action);
//                alert(action.attr('href'));
            }

        });

        var DataTable =$('#table-content').DataTable( {
            "dom": '<"top"lpf <"clear">>rt<"bottom"ip<"clear">>',
//            "lengthChange": false,
            "processing": true,
            "serverSide": true,
            "bSort":      false,
            "ajax": "<?php echo BASE_ADMIN_URL."/user/lstuser"; ?>",
            "columns": [
                { "data": "id" },
                { "data": "firstName" },
                { "data": "lastName" },
                { "data": "email" },
                { "data": "avatar" },
                { "data": "team" },
                { "data": "position" },
                { "data": "sActive" },
                { "data": "createAt" }
            ]
        } );

        $('body').on('click','[data-action="account-delete"]', function(){
            if(confirm('Do you want to delete ?'))
            {
                var _this = $(this);
                var arrId = [_this.attr('data-value')];
                $.post("<?php  echo BASE_ADMIN_URL.'/user/delete'; ?>",{'account_ids':arrId}, function(data){
                    if(data.error)
                    {
                        alert(data.message);
                    }
                    else{
                        DataTable
                            .row( _this.parents('tr') )
                            .remove()
                            .draw();
                    }

                },'json');
            }
        });

    });
</script>