<?php
// account info
$accountInfo    = $this->accountInfo;
$contractTypes  = $this->contractTypes;
$myContractTypes  = $this->myContractTypes;

$levels         = $this->levels;
$projects       = $this->projects;
$projectsMember = $this->projectsMember;
$arrProject     = $this->arrProject;
$myGroups = $this->myGroupMembers;
$bHopDongDangThuViec = $this->bHopDongDangThuViec;
//Core_Common::var_dump($bHopDongDangThuViec);
$arrGroupMember = array(); //user for JS import user to
//var_dump($accountInfo);
$arrProjectsMember = array();
if(!empty($projectsMember)) {
    $countProject = count($projectsMember);
    $percentProjects = $countProject * 100;
    $total = 0;
    foreach ($projectsMember as $projectMember) {
        $total += intval($projectMember['percent']);
    }
    $truLayDu  = ($percentProjects - $total)/$countProject;

    foreach ($projectsMember as $key=>$projectMember) {
        $percentTmp = $projectMember['percent'] + $truLayDu;
        $projectsMember[$key]['percent_view']  = $percentTmp/$countProject;
    }
}
?>
<style>
    .addname-leader{
        list-style: none;
        margin: 10px;
    }
    .addname-manager{
        list-style: none;
        margin: 10px;
    }
    
    .row-new-group .member-new-group {
        width: 300px;
        text-align: left;
        margin-left: 250px;
        margin-top: 5px;
    }
</style>
<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-user"></i>
        <span class="capitalize">User</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <!-- <div class="title-content bg-blue clearfix">
        <h5 class="white bold pull-left capitalize">User <?= $accountInfo['name']; ?></h5>
    </div> --><!-- title-content -->
    <div class="widget-content-user">
        <div class="container-fluid">
            <div class="row clearfix">
                <div class="col-sm-3 border-right">
                    <?= $this->render('usersearch.phtml'); ?>
                </div>
                <div class="col-sm-9">
                    <div class="all-info-user">
                        <ul class="tabs-menu-info mar-bot20 clearfix">
                            <li><a href="<?= BASE_ADMIN_URL.'/user/summary?account_id='.$accountInfo['account_id'];?>">Summary</a></li>
                            <li><a href="<?= BASE_ADMIN_URL.'/user/general?account_id='.$accountInfo['account_id'];?>">General</a></li>
                            <li ><a href="<?= BASE_ADMIN_URL.'/user/personal?account_id='.$accountInfo['account_id'];?>">Personal</a></li>
                            <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a href="javascript:void(0);">Job</a></li>
                            <li><a  href="<?= BASE_ADMIN_URL.'/user/achievement?account_id='.$accountInfo['account_id'];?>">Achievement</a></li>
                        </ul><!-- tabs-menu-info -->
                        <div class="tabs-child">
                                <div id="job" class="job">
                                    <form action="<?= BASE_ADMIN_URL.'/user/jobuser'?>" method="post">
                                        <input type="hidden" name="account_id" value="<?= $accountInfo['account_id'];?>"/>
                                        <a class="btn btn-primary add-contract">Add contract</a>
                                        <ul class="job-info">
                                            <?php
                                            if(!empty($myContractTypes['data'])) {
                                                foreach ($myContractTypes['data'] as $myContractType) {

                                                    ?>
                                                    <li class="clearfix">
                                                    <div class="row m-t-20 item">
                                                        <div class="col-md-5" data-action="change-contract" data-item="contract-<?= $myContractType['general_id'] ?>">
                                                            <input class="hide" data-item="old-date" value="<?= $myContractType['date'] ?>"/>
                                                            <input class="hide" data-item="old-contract" value="<?= $myContractType['general_id'] ?>"/>
                                                            <h6 class="bold pull-left">Contract type</h6>

                                                            <div class="combobox w500 pull-left">
                                                                <span class="arrow"></span>
                                                                <select id="contract_type" name="contract_type"
                                                                        class="combobox-group bor-raduis4">
                                                                    <?php foreach ($contractTypes as $iGeneralId => $contract) {
                                                                        $sActive = ($iGeneralId == $myContractType['general_id']) ? 'selected' : '';
                                                                        echo '<option value="' . $iGeneralId. '" '.$sActive.'>' . $contract . '</option>';
                                                                    }
                                                                    ?>

                                                                </select>

                                                            </div>
                                                            <!-- combobox -->
                                                        </div>
                                                        <div class="col-md-5" data-action="change-date" data-item="date-<?= $myContractType['general_id'] ?>">
                                                            <h6 class="bold pull-left">Starting date</h6>
                                                            <input type="text" data-item="datetimepicker" id="start-date-<?= $myContractType['general_id'] ?>"
                                                                   value="<?= date('d-m-Y', $myContractType['date']); ?>"
                                                                   class="w500 date_time_picker" onkeypress="return false">
                                                        </div>
                                                        <div class="col-md-2 m-t-20">
                                                            <button class="btn btn-info save-contract"><i class="fa fa-check" aria-hidden="true"></i>
                                                            </button>
                                                            <button class="btn btn-default remove-contract"><i class="fa fa-times" aria-hidden="true"></i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                    </li>
                                                    <?php
                                                }
                                            }
                                            ?>
                                        </ul>
                                        <div class="row">
                                           <?php
                                           if(!empty($myGroups['data']))
                                           {
                                               foreach($myGroups['data'] as $myGroup)
                                               {
                                                   $groupMember = GroupMember::getInstance()->getGroupMemberByAccountAndGroupId($accountInfo['account_id'], $myGroup['group_id']);
                                                   $groupMembers = GroupMember::getInstance()->getGroupMemberID($myGroup['group_id'],0,MAX_QUERY_LIMIT);
                                                   if($myGroup['group_type'] == 2) {
                                                       ?>
                                        <div class="col-md-6">
                                            <ul class="list-group-level">
                                                <li>
                                                    <span class="label label-success">Group: </span>

                                                    <div class="">
                                                        <?= $myGroup['group_name']; ?>
                                                    </div>
                                                </li>

                                                <li>
                                                    <span class="label label-danger">Level:</span>

                                                    <div class="">
                                                        <?= $levels[$groupMember['level']]; ?>
                                                    </div>
                                                    <!-- bombobox -->
                                                </li>

                                                <?php
                                                $arrLevel = array();
                                                $groupMembers['data'] = Core_Common::array_sort($groupMembers['data'], 'level');
                                                //                                                            Core_Common::var_dump($groupMembers);
                                                foreach ($groupMembers['data'] as $groupMember) {

                                                    if ($groupMember['level'] > 1 && $groupMember['level'] < 6) {
                                                        $arrGroupMember [] = $groupMember;
                                                        ?>

                                                        <?php if (!in_array($groupMember['level'], $arrLevel)) {
                                                            $arrLevel [] = $groupMember['level'];
                                                            ?>
                                                            <li class="clearfix"
                                                                data-level-group="<?= $groupMember['group_id'] . '-' . $groupMember['level']; ?>">
                                                                <span class="label label-info"><?= $levels[$groupMember['level']]; ?></span>
                                                            </li>
                                                        <?php
                                                        } ?>
                                                    <?php
                                                    }
                                                }
                                                //
                                                ?>
                                                <?php
                                                echo '</ul>';
                                                echo '</div>';
                                                }
                                                ?>

                                                <?php
                                                
                                                }
                                                }
                                                ?>
                                            </div>
                                    </form>
                                    <!-- <div class="footer-btn-tab clearfix">
                                        <a href="javascript:void(0);" class="back grey bor-raduis4" data-action="back-page">Back</a>
                                       <a href="javascript:void(0);" class="save white bor-raduis4 bg-blue" onclick="submitForm(); return false;">Save change</a>
                                    </div> --><!--footer-btn-tab-->
                                </div><!-- job -->
                        </div><!-- tabs-child -->
                    </div><!-- all-info-user -->
                </div>
            </div><!-- row -->
        </div><!-- container-fluid -->
    </div><!-- widget-content -->
</div><!-- container-content -->
<script type="text/javascript">
$(function(){

    <?php
    // remove contract type 0 when current user ' s contract type > 0
    if($accountInfo['contract_type'] > 0)
        echo '$(\'#contract_type option[value="0"]\').remove();';

//    if($accountInfo['contract_type'] > 0 && $accountInfo['contract_type'] != $probationContractTypeId){
//
//            echo '$(\'#contract_type option[value="'.$probationContractTypeId.'"]\').remove();';
//
//    }
    foreach($arrGroupMember as $groupMember){
    ?>
    $('[data-level-group="<?=  $groupMember['group_id'].'-'.$groupMember['level']; ?>"]').append('<div class="w500"><?= $groupMember['name'];?></div>');
    <?php
    }?>

//    $('body').on('click','[data-action="add-more-project"]',function(){
//       var divAppend    = $('[data-action="appent-for-project"]');
//       $(this).after(divAppend.html());
//        $('.date_time_picker').datetimepicker({
//            format:'d-m-Y',
//            timepicker:false,
//            mask:true // '9999/19/39 29:59' - digit is the maximum possible for a cell
//        });
//    });
    $('body').on('click','[data-action="jobuser-submit"]',function(){
        $('form').submit();
    });

    $('body').on('click','[data-action="update"]',function(){
       if(confirm('Do you want to update ?'))
       {
           var _this    = $(this);
           var project  = parserProject(_this);
//           console.log(project);
           $.post("<?= BASE_ADMIN_URL.'/projectmember/update';?>",{data:JSON.stringify(project)}, function(data){
               var sMessage = data.message;
               if(sMessage != '')
                    alert(sMessage);
               else
                    location.reload(true);
           },'json');
       }// end if(confirm('Do you want to update ?'))
    });


    $('body').on('click','[data-action="delete"]',function(){
        if(confirm('Do you want to delete ?'))
        {
            var _this    = $(this);
            var parent   = _this.parent();
            var project  = parserProject(_this);
            $.post("<?= BASE_ADMIN_URL.'/projectmember/delete';?>",{data:JSON.stringify(project)}, function(data){
                location.reload(true);
            },'json');
        }// end if(confirm('Do you want to delete ?'))
    });

    $('body').on('click','[data-action="save"]', function(){
        if(confirm('Do you want to save ?'))
        {
            var _this    = $(this);
            var parent   = _this.parent();
            var project  = parserProject(_this);
            var projectName = parent.find('[data-project="project-id"]').html();
            $.post("<?= BASE_ADMIN_URL.'/projectmember/add';?>",{data:JSON.stringify(project)}, function(data){
                var sMessage = data.message;
                if(sMessage != '')
                    alert(sMessage);
                else
                    location.reload(true);
            },'json');
        }// end if(confirm('Do you want to delete ?'))
    });
    $('body').on('input propertychange paste','[data-autocomplete="manager"]',function(e){
        var _val = $.trim($(this).val());
        $('input[name="manager_id"]').val(0);
        if(_val == '')
            return;
        var params      = {};
        params['key']   = _val;
        params['team']  = '';
        var _html       = '<li class="clearfix">No Data</li>';
        var resultPlace =  $('[data-autocomplete="result-manager"]');
        $.post("<?= BASE_ADMIN_URL.'/user/searchuser'; ?>", { data: JSON.stringify(params)}, function(data){
            if(data.total > 0)
            {
                _html    = '';
                $.each(data['data'], function(index, account){
                    _html += suggesstionLI(account.image_tag,account.name,account.position_name,account.account_id,'addname-manager');
                });
            }
            resultPlace.find('ul').html(_html);
            resultPlace.show();

        },'json');
    });


    $('body').on('input propertychange paste','[data-autocomplete="leader"]',function(e){
        var _val = $.trim($(this).val());
        $('input[name="leader_id"]').val(0);
        if(_val == '')
            return;
        var params      = {};
        params['key']   = _val;
        params['team']  = '';
        var _html       = '<li class="clearfix">No Data</li>';
        var resultPlace =  $('[data-autocomplete="result-leader"]');
        $.post("<?= BASE_ADMIN_URL.'/user/searchuser'; ?>", { data: JSON.stringify(params)}, function(data){
            if(data.total > 0)
            {
                _html    = '';
                $.each(data['data'], function(index, account){
                    _html += suggesstionLI(account.image_tag,account.name,account.position_name,account.account_id,'addname-leader');
                });
            }
            resultPlace.find('ul').html(_html);
            resultPlace.show();

        },'json');
    });


    $('body').on('click','.addname-manager',function(e){

        var account_id = $(this).attr('data-aId');
        var name = $(this).attr('data-name');
        $('input[name="manager_id"]').val(account_id);

        $("#manger-display").fadeOut(100);
        $('[data-autocomplete="manager"]').val(name);
        $('[data-autocomplete="manager"]').focus();


    });

    $('body').on('click','.addname-leader',function(e){

        var account_id = $(this).attr('data-aId');
        var name = $(this).attr('data-name');
        $('input[name="leader_id"]').val(account_id);

        $("#leader-display").fadeOut(100);
        $('[data-autocomplete="leader"]').val(name);
        $('[data-autocomplete="leader"]').focus();

    });

    var i = 0;

    $('body').on('click', '.add-contract', function(e){
        e.preventDefault();
        var _temp =  '<?php foreach ($contractTypes as $iGeneralId => $contract) {
                            echo '<option value="' . $iGeneralId. '" >' . $contract . '</option>';
                        }
                    ?>';

        var _html =   '<div class="clearfix"></div><div class="row item m-t-20 item-'+i+'">'+
                        '<div data-action="change-contract" data-item="contract" class="col-md-5">'+
                            '<input class="hide" data-item="old-date" value="0"/> ' +
                            '<input class="hide" data-item="old-contract" value="0"/>' +
                            '<h6 class="bold pull-left">Contract type</h6>'+
                            '<div class="combobox w500 pull-left">'+
                                '<span class="arrow"></span>'+
                                '<select id="contract_type" name="contract_type" class="combobox-group bor-raduis4">'+
                                _temp +
                                '</select>'+
                            '</div>'+
                        '</div><div class="col-md-5" data-action="change-date" data-item="date">'+
                            '<h6 class="bold pull-left">Starting date</h6>'+
                            '<input type="text" data-item="datetimepicker" value="" class="w500 date_time_picker" onkeypress="return false">'+
                        '</div>'+
                        '<div class="col-md-2 m-t-20">'+
                            '<button class="btn btn-info save-contract"><i class="fa fa-check" aria-hidden="true"></i></button>'+
                            '<button class="btn btn-default remove-contract"><i class="fa fa-times" aria-hidden="true"></i></button>'+
                        '</div></div>';
        $('.job-info').append(_html);

        $('[data-item="datetimepicker"]').datetimepicker({
           format:'d-m-Y',
           timepicker:false,
           mask:true // '9999/19/39 29:59' - digit is the maximum possible for a cell
        });  
        i++;
    });

    $('body').on('click', '.save-contract', function(e){
        e.preventDefault();
        var _this = $(this);
        var _val = _this.parents('.item').find('select[name="contract_type"]').val();
        var dtpk = _this.parents('.item').find('[data-item="datetimepicker"]').val();
        var old_date = _this.parents('.item').find('[data-item="old-date"]').val();
        var old_contract = _this.parents('.item').find('[data-item="old-contract"]').val();


        $.post("<?php  echo BASE_ADMIN_URL.'/api/token/index'; ?>",{'method': 'generateToken'}, function(token) {
            var params = {"old-contract": old_contract, "old-date": old_date, "contract-type":_val, "date":dtpk, "account-id":<?= $accountInfo['account_id']?>,"token":token};
            
            $.post(baseurl+'/user/save-user-contract-type',params,function(response){
                if(!response.error){
                    var contract = response.contract;
//                    var _ele = $('[data-item="contract-'+contract.general_id+'"]');

                    _this.parents('.item').find('[data-item="old-date"]').val(contract.date);
                    _this.parents('.item').find('[data-item="old-contract"]').val(_val);

                }else{

                    var contract = response.contract;
                    var _ele = $('[data-item="contract-'+contract.general_id+'"]');

                    _this.parents('.item').find('select[name="contract_type"]').val(contract.general_id);
                    _this.parents('.item').find('[data-item="datetimepicker"]').val(contract.date);

                }
                alert(response.message);
            },'json');
        });

    });

    $('body').on('click', '.remove-contract', function(e){
        e.preventDefault();
        var _this = $(this);
        var _val = _this.parents('.item').find('select[name="contract_type"]').val();
        var dtpk = _this.parents('.item').find('[data-item="datetimepicker"]').val();

        if(confirm('Are you sure?')){
            $.post("<?php  echo BASE_ADMIN_URL.'/api/token/index'; ?>",{'method': 'generateToken'}, function(token) {
                var params = {"contract-type":_val, "date":dtpk, "account-id":<?= $accountInfo['account_id']?>,"token":token};

                $.post(baseurl+'/user/delete-user-contract',params,function(response){
                    alert(response.message);
                    if(!response.error){
                        _this.parents('.item').remove();
                    }
                },'json');
            });

        }
    });
});
function parserProject(_this)
{
    var parent               = _this.parent();
    var project              = {};
    var projectId            = parent.find('[data-project="project-id"]');
    var projectPercent       = parent.find('[data-project="percent"]');
    var projectStartDate     = parent.find('[data-project="start_date"]');
    var projectEndDate       = parent.find('[data-project="end_date"]');
    project['project-id']    = projectId.val();
    project['project-name']  = parent.find('[data-project="project-id"] :selected').text();
    if($.trim(project['project-name']) == '')
    {
        project['project-name'] = parent.find('[data-project="project-name"]').val();
    }
    project['percent']       = projectPercent.val();
    project['account-id']    = <?= $accountInfo['account_id']; ?>;
    project['start_date']    = projectStartDate.val();
    project['end_date']      = projectEndDate.val();
    return project;
}
function suggesstionLI(avatar, name, position, account_id,class_name){

    return '<li class="'+class_name+'" data-aId="' + account_id + '" data-name="' + name + '">'+
        '<a href="javascript:void(0);">'+
        '<div class="inform-tags-members clearfix">'+
        '<div class="img-tags-members mg10 fl">'+
        '<img alt="" width="36" src="' + avatar + '">'+
        ' <strong> ' + name + ' </strong> '+
        ' <span> ' + position + ' </span> '+
        '</div>'+
        '</div>'+
        '</a>'+
        '</li>';
}

function submitForm() {
	$("form").submit();
   
}
</script>