<?php //var_dump($this->groupsTeam); ?>
<div class="info-user-left">
    <input type="text" id="text-user-search" class="search-profile bor-raduis4 mar-bot15" placeholder="search">
    <div class="combobox">
        <span class="arrow"></span>
        <select class="combobox-group bor-raduis4" id="select-team">
            <option value="0">All</option>
            <?php
            if($this->groupsTeam) {
                foreach ($this->groupsTeam as $team) { ?>
                    <option value="<?php echo $team['group_id'] ?>"> <?php echo $team['group_name'] ?></option>
                <?php }
            }
            ?>

        </select>
    </div><!-- bombobox -->
    <ul class="members-group">
        <?php
            foreach($this->accountsSearch['data'] as $accountInfo) {
                $account = Core_Common::accountProcess($accountInfo);
        ?>
            <li class="clearfix">
                <div class="img-member bor-raduis4 pull-left">
                    <img width="36px" height="36px" src="<?php echo $account['image_tag']; ?>" alt="">
                </div><!-- img-member -->
                <div class="name-member ">
                    <a href="<?php echo BASE_ADMIN_URL.'/user/summary?account_id='.$account['account_id']; ?>"><h5 class="bold"><?php echo $account['name']; ?></h5></a>
                    <span><?php echo $account['position_name']; ?></span>
                </div><!-- name-member -->
            </li>
        <?php } ?>
    </ul><!-- members-group -->
</div><!-- summary_left -->
<script>
    $(function(){
        var selTeam = $('#select-team');
        var textUserSearch = $('#text-user-search');
        var $params = {};

        selTeam.change(function(){
            userSearch();
        });
        textUserSearch.on('input propertychange paste',function(e){
            userSearch();
        });

        function userSearch()
        {
            $params['team']    = selTeam.val();
            $params['key']     = textUserSearch.val();

            $.post("<?php echo BASE_ADMIN_URL.'/user/searchuser'; ?>", { data: JSON.stringify($params)}, function(data){
                var _html = '<li class="clearfix">No Data</li>';
                data = JSON.parse(data);
                if(parseInt(data.total) > 0)
                {
                    _html = '';
                    var accounts = data['data'];
                    $.each(accounts,function(index,account){
                        _html +=
                            '<li class=" clearfix">' +
                            '<div class="img-member bor-raduis4 pull-left">' +
                            '<img width="36px" height="36px" src="'+account.image_tag+'" alt="">' +
                            '</div><!-- img-member -->' +
                            '<div class="name-member">' +
                            '<a href="<?php echo BASE_ADMIN_URL.'/user/summary?account_id=' ?>'+account.account_id+'"><h5 class="bold">'+account.name+'</h5></a>' +
                            '<span>'+account.position_name+'</span>' +
                            '</div><!-- name-member -->' +
                            '</li>';
                    });

                }
                $('.members-group').html(_html);
            })
        }
    })
</script>