<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="index, follow" />
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <link rel="stylesheet" type="text/css" href="<?php echo  $this->static->backend->css . '/login/bootstrap.min.css' ?>">
        <link rel="stylesheet" type="text/css" href="<?php echo  $this->static->backend->css . '/login/bootstrap-responsive.min.css' ?>">
        <link rel="stylesheet" type="text/css" href="<?php echo  $this->static->backend->css . '/login/style.css' ?>">
        <script type="text/javascript">
            var baseurl = "<?php echo BASE_URL; ?>";
        </script>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span4"></div>
                <div class="span4 ">
                    <div class="container-fluid m-login-container">
                        <div class="page-header" style="text-align:left">
                            <img src="<?php echo  $this->static->backend->images . '/logognt.jpg' ?>">
                        </div>
                        <?php if(isset($this->message) && $this->message != ''): ?>
                        <div class="alert">
                            <?php echo $this->message; ?>
                        </div>
                        <?php endif; ?>

                        <form  name="tf" class="" action="<?php echo BASE_URL; ?>/login" method="post">
                            
                            <div class="control-group">
                                <label class="control-label" for="controller">Email:</label>
                                <div class="controls">
                                    <input name="username" class="span12" id="username" type="text" value="<?php echo $this->email;?>" />
                                </div>
                            </div>

                            
                            <div class="control-group">
                                <label class="control-label" for="controller">Password:</label>
                                <div class="controls">
                                    <input class="span12" name="password" id="password" type="password" />
                                </div>
                            </div>

                            <div class="control-group">
                                <div class="controls">
                                    <button type="button" onClick="doLogin(); return false;" style="margin-top: 15px" class="btn btn-primary"> Login</button>
                                </div>
                            </div>
                        </form>
                    </div>          
                </div>
                <div class="span4"></div>
            </div>
        </div>
    </body>
</html>
