<?php
$groupTypes = $this->groupTypes;
$countries  = $this->countries;
$arrData    = $this->arrData;
$bomMembers = $this->bomMembers;
?>
<style>
    .addname-admin{
        list-style: none;
        margin: 10px;
    }
    ul.tags-staff, .cmt ul.tags-staff {
        position: absolute;
        left: 341px;
        background-color: #fff;
        border: 1px solid #999;
        margin: 2px 0;
        z-index: 9999;
        width:  498px;
    }
    .row-new-group .member-new-group {
        width: 300px;
        text-align: left;
        margin-left: 250px;
        margin-top: 5px;
    }
</style>
<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-group"></i>
        <span class="capitalize">Group</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <div class="title-content bg-blue clearfix">
        <h5 class="white bold pull-left capitalize">Add group</h5>
    </div><!-- title-content -->
    <div class="widget-content">
        <form method="post">
            <div id="general" class="general">
                <ul>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Name</h6>
                        <input type="text" name="group_name" value="<?php echo $arrData['group_name']; ?>" class="w500">
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Type</h6>
                        <div class="combobox w500 pull-left">
                            <span class="arrow"></span>
                            <select name="group_type" class="combobox-group bor-raduis4">
                                <?php 
                                global $globalConfig;
                                foreach($groupTypes as $key=>$type){ 
                                	if($this->isExcept && $key == $globalConfig['group_type']['company']){
										continue; 
									}?>
                                
                                    <option value="<?php echo $key;?>" <?php if($key == $arrData['group_type']) { echo "selected";} ?>> <?php echo $type; ?></option>
                                <?php } ?>
                            </select>
                        </div><!-- bombobox -->
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Country</h6>
                        <div class="combobox w500 pull-left">
                            <span class="arrow"></span>
                            <select name="country_id" class="combobox-group bor-raduis4">
                                <?php foreach($countries as $key=>$country){ ?>
                                    <option value="<?php echo $key;?>"  <?php if($key == $arrData['country_id']) { echo "selected";} ?>> <?php echo $country; ?></option>
                                <?php } ?>
                            </select>
                        </div><!-- bombobox -->
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Privacy</h6>
                        <div class="combobox w500 pull-left">
                            <span class="arrow"></span>
                            <select name="is_public" class="combobox-group bor-raduis4">

                                <option value="0"  <?php if($arrData['is_public'] == 0) { echo "selected";} ?>> private </option>
                                <option value="1"  <?php if($arrData['is_public'] == 1) { echo "selected";} ?>> public </option>
                            </select>
                        </div>
                    </li>
                    <li class="clearfix">
                        <h6 class="bold pull-left">Admin</h6>
                        <?php if(!empty($bomMembers['data'])){?>
                            <div class="combobox w500 pull-left" style="display: none;">
                                <span class="arrow"></span>
                                <select data-action="select-bom-user" class="combobox-group bor-raduis4">
                                    <option value="0"> ----------- </option>
                                    <?php foreach($bomMembers['data'] as $member) {
                                        ?>
                                        <option value="<?php echo $member['account_id']; ?>">
                                            <?php echo $member['name']; ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>
                        <?php } ?>
                        <input autocomplete="off" type="text" data-action="user-search" value="<?php echo $arrData['admin_name']; ?>" name="admin_name" data-autocomplete="admin" class="w500">
                        <input data-action="user-id" name="admin_id"  value="<?php echo $arrData['admin_id']; ?>"  type="hidden"/>
<!--                        <div class="admin-member-new-group">-->
<!---->
<!--                        </div>-->
                    </li>

                    <li class="clearfix">
                        <h6 class="bold pull-left">Manager</h6>
                        <input autocomplete="off" data-action="user-search" type="text" value="<?php echo $arrData['manager_name']; ?>"  name="manager_name"  class="w500">
                        <input data-action="user-id" name="manager_id"  value="<?php echo $arrData['manager_id']; ?>"  type="hidden"/>
                        <div class="admin-member-new-group">

                        </div>
                    </li>

                    <li class="clearfix">
                        <h6 class="bold pull-left">Avartar</h6>
                        <div class="container-img-avartar pull-left bor-raduis4">
                            <img id="avatar"   src="<?php echo $arrData['image_name'];?>" width="100%" height="100%" <?php if (empty($arrData['image_name'])){echo'style="display:none"';}?>/>
                        </div><!--container-img-avartar-->
                        <span class="file pull-left bor-raduis4">Browse
                            <input type="file"  id="chosenImage" class="file-get img-source" onchange="installCheckImageUpload(this)">
                        </span>
                        <input type="hidden" name="image_url" value="<?php echo $arrData['image_url'];?>"/>
                        <input type="hidden" name="image_name" value="<?php echo $arrData['image_name'];?>"/>
                    </li>

                    <li class="clearfix">
                        <h6 class="bold pull-left">Order</h6>
                        <input type="text" name="sort_order" value="<?php echo $arrData['sort_order']; ?>" class="w500">
                    </li>

                    <li class="clearfix active-check-box-group">
                        <h6 class="bold pull-left">Active</h6>
                        <div class="checkbox">
                            <label> Yes <input type="radio" name="active" class="" value="1" <?php if($arrData['active'] == 1) { echo "checked";}?>></label>
                            <label> No <input type="radio" name="active" class="" value="0" <?php if($arrData['active'] == 0) { echo "checked";}?>></label>
                        </div>

                    </li>
                </ul>
                <div class="footer-btn-tab clearfix">
                    <a href="javascript:void(0);" class="back grey bor-raduis4" data-action="back-page">Back</a>
                    <a href="javascript:void(0);" class="save white bor-raduis4 bg-blue" onclick="submitForm(); return false;">Save change</a>
                </div><!--footer-btn-tab-->
            </div><!-- add group -->
        </form>
    </div><!-- widget-content -->
</div><!-- container-content -->
<script type="text/javascript">
    $(function(){
        createDisplayObjectHtml($('input[name="manager_name"]'),'','user-search-result');
        createDisplayObjectHtml($('input[name="admin_name"]'),'','user-search-result');
//        data-action="select-bom-user"
        var selectBomUser   = $('select[data-action="select-bom-user"]');
        var userSearchEle   = selectBomUser.parents('li').find('input[data-action="user-search"]');
        $('body').on('change','select[name="group_type"]', function(){
            var _this   = $(this);
            $('input[name="admin_id"]').val(0);
            $('input[name="admin_name"]').val('');
            if(_this.val() == 2)
            {
                selectBomUser.parent().show();
                userSearchEle.hide();
            }else
            {
                selectBomUser.parent().hide();
                userSearchEle.show();
            }
        });


        $('body').on('change','select[data-action="select-bom-user"]', function(){
            var _this   = $(this);
            $('input[name="admin_id"]').val(_this.val());
        });


        $('.error-report').remove();

            <?php
            if(!empty($this->arrError)) {
                foreach ($this->arrError as $error) {
                    ?>
            var html = '';
                html = '<span class="margin-10 red error-report"><?php echo $error['message']; ?></span>';
                $('[name="<?php echo $error['field']; ?>"]').after(html);
            <?php
                }
            }
        ?>

        $('body').on('input propertychange paste','[data-action="user-search"]',function(e){
            var _this   = $(this);
            var _val = $.trim($(this).val());
            var resultPlace =  _this.parent().find('.user-search-result');
            var userIdEle = _this.parent().find('input[data-action="user-id"]');
            userIdEle.val(0);

            if(_val == '') {
                resultPlace.hide();
                return;
            }
            var params      = {};
            params['key']   = _val;
            params['team']  = '';
            var _html       = '<li class="clearfix">No Data</li>';

            $.post("<?php echo BASE_ADMIN_URL.'/user/searchuser'; ?>", { data: JSON.stringify(params)}, function(data){
                if(data.total > 0)
                {
                    _html    = '';
                    $.each(data['data'], function(index, account){
                        _html += suggesstionLI(account.image_tag,account.name,account.position_name,account.account_id, 'addname');
                    });
                }
                resultPlace.find('ul').html(_html);
                resultPlace.show();

            },'json');
        });

        $('body').on('click','.addname',function(e){
            var _this = $(this);
            var display = _this.parents('.user-search-result');
            var userIdEle =   display.parent().find('input[data-action="user-id"]');
            var inputSearch = display.parent().find('input[data-action="user-search"]');
            var account_id = $(this).attr('data-aId');
            var name = $(this).attr('data-name');

            userIdEle.val(account_id);
            display.fadeOut(100);
            inputSearch.val(name);
            inputSearch.focus();


        });

        function suggesstionLI(avatar, name, position, account_id, class_name){
            return '<li class="'+class_name+'" data-aId="' + account_id + '"  data-name="' + name + '">'+
                '<a href="javascript:void(0);">'+
                '<div class="inform-tags-members clearfix">'+
                '<div class="img-tags-members mg10 fl">'+
                '<img alt="" width="36" src="' + avatar + '">'+
                ' <strong> ' + name + ' </strong> '+
                ' <span> ' + position + ' </span> '+
                '</div>'+
                '</div>'+
                '</a>'+
                '</li>';
        }
    });
    function submitForm()
    {
        $('form').submit();
    }
    function installCheckImageUpload(sender)
    {
        var inputHiddenElement  = $('[name="image_url"]');
        var inputImageName      = $('[name="image_name"]');
        var inputImage  = $('#avatar');

//        sender,urlUpload,jsonData,inputHiddenElement,inputImage
        var jsonData    = [{'input_name':'f','input_val':'group'}, {'input_name':'w','input_val':'200'}, {'input_name':'h','input_val':'200'}];
        checkImageUpload(sender,baseurl+'/upload/upload-group',jsonData,inputHiddenElement,inputImage,inputImageName);
    }

</script>