<?php
    $arrGroup   = array_flip($this->GroupType);
?>
<style>
    .group-type{
        float: left;
        position: relative;
        left: 70px;
    }
</style>
<div class="title-page mar-bot15">
    <h4>
        <i class="fa fa-group"></i>
        <span class="capitalize">Group</span>
    </h4>
</div><!-- title-page -->
<div class="container-content">
    <div class="title-content bg-blue clearfix">
        <h5 class="panel-title white bold pull-left capitalize">Group list</h5>
        <ul class="function-header pull-right">
            <li>
                <a href="<?php echo BASE_ADMIN_URL.'/group/add';?>">
                    <i class="fa fa-plus"></i>
                    <span class="capitalize">add new</span>
                </a>
            </li>
        </ul>
    </div><!-- title-content -->
    <div class="widget-content">
        <div class="container-table">
            <div class="table-responsive">
                <table id="table-content" class="display responsive nowrap table table-hover table-condensed" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th><div class="checkbox-custom checkbox-primary"><input type="checkbox" id="inputUnchecked" data-action="check-all"/><label for="inputUnchecked"></label></div></th>
                        <th width="7%">ID</th>
                        <th>Name</th>
                        <th>Avatar</th>
                        <th>Type</th>
                        <th>Privacy</th>
                        <th>Active</th>
                        <th>Action</th>
                        <!-- <th>Is Bom</th> -->
                        <th>Order</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div><!-- table-responsive -->
        </div><!-- container-table -->
    </div><!-- widget-content -->
</div><!-- container-content -->

<div data-hidden="group-type" style="display: none;">
    <select data-action="search-by-type" name="group-type">
        <option value="">---------</option>
        <?php foreach($arrGroup as $key=>$group) { ?>
            <option value="<?php echo $key?>"><?php echo $group?></option>
        <?php } ?>
    </select>
</div>

<script>
    $(document).ready(function() {
        $('#table-content tbody').on('click', 'td', function(e){
            if($(this).index() > 0 && $(this).index() != 7)
            {
                var action = $(this).parent('tr').find('td').eq(2).find('a');
                if(typeof action.attr('href') !== 'undefined');
                {
                    hrefRedirect(action);
                }
            }

        });

        $('body').on('click','[data-action="check-all"]',function(){
            var _this = $(this);
            var checkboxItems = $( '[data-action="check-delete"]');
            if(_this.is(':checked'))
                doChecked(checkboxItems,true);
            else
                doChecked(checkboxItems,false);
        });

        var groupTable  = $('#table-content').DataTable( {
            "dom": '<"top"<"margin-10 pull-left delete-ids">l <"margin-10 group-type"> pf <"clear">>rt<"bottom"ip<"clear">>',
            "processing": true,
            "serverSide": true,
            "bSort":      true,
            "ajax": "<?php echo BASE_ADMIN_URL."/group/lstgroup"; ?>",
            "columns": [
                { "data": "checkbox_delete", "name" : "", "bSortable": false },
                { "data": "id", "name" : "group_id", "bSortable": true },
                { "data": "name", "name" : "group_name", "bSortable": true},
                { "data": "image_url", "name" : "", "bSortable": false},
                { "data": "group_type_name", "name" : "", "bSortable": false },
                { "data": "group_privacy" , "name" : "is_public", "bSortable": false},
                { "data": "group_active_checkbox" , "name" : "", "bSortable": false},
                { "data": "actions" , "name" : "", "bSortable": false},
                // { "data": "isBom", "name" : "is_bom"},
                { "data": "order" , "name" : "", "bSortable": false}
            ]
//            "aoColumnDefs": [
//                { "bSortable": false, "aTargets": [ 0 ] },
//                { "bSortable": false, "aTargets": [ 1 ] },
//                { "bSortable": false, "aTargets": [ 2 ] },
//                { "bSortable": false, "aTargets": [ 3 ] },
//                { "bSortable": false, "aTargets": [ 4 ] },
//                { "bSortable": false, "aTargets": [ 5 ] },
//                { "bSortable": false, "aTargets": [ 6 ] },
//                { "bSortable": false, "aTargets": [ 7 ] },
//                { "bSortable": false, "aTargets": [ 9 ] }
//
//            ]
        } );
//        groupTable.columns(8).
        $('body').on('click','[data-action="group-delete"]', function(){
            if(confirm('Do you want to delete ?'))
            {

                var _this = $(this);
                var arrId = [_this.attr('data-value')];
                $.post("<?php  echo BASE_ADMIN_URL.'/group/delete'; ?>",{'group_id':arrId}, function(data){
                    if(data.error)
                    {
                        alert(data.message);
                    }
                    else{
                        groupTable
                            .row( _this.parents('tr') )
                            .remove()
                            .draw();
                    }

                },'json');
            }
        });

        $('body').on('click','[data-action="delete-groups"]', function(){
            if(confirm('Do you want to delete ?'))
            {
                var arrCheck = Array();
                var checkboxItems = $( '[data-action="check-delete"]');
                $.each(checkboxItems,function(index,value){
                    var element = $(this);
                    if(element.is(':checked'))
                        arrCheck.push(element.val());
                });
                if(arrCheck.length)
                {
                    $.post("<?php  echo BASE_ADMIN_URL.'/group/delete'; ?>",{'group_id':arrCheck}, function(){
                        $.each(checkboxItems,function(index,value) {
                            var _this = $(this);
                            groupTable
                                .row( _this.parents('tr') )
                                .remove();
                        });
                        $('[data-action="check-all"]').prop('checked',false);
                        groupTable.draw();
                    },'json');
                }

            }
        });
        $("div.group-type").prepend($('[data-hidden="group-type"]').html());
        $("div.delete-ids").prepend('<a href="javascript:void(0);"><i data-action="delete-groups" class="fa fa-trash fa-lg"></i><a>');
        $('[data-hidden="group-type"]').remove();

        // Apply the search
        groupTable.columns(0).every( function () {
            var that = this;
            $( '[data-action="search-by-type"]').on( 'change', function () {
                that
                    .search(this.value)
                    .draw();
            } );
        } );

        function doChecked(checkboxItems, checked){
            $.each(checkboxItems,function(index,value){
                $(this).prop('checked',checked);
            });
        }

    } );
</script>