<?php 
if ($this->pageCount)
{
    
?>
<div class="boxPaging">
        <div class="showPage">&nbsp;</div>
        <div class="pagAct">
            
            <?php if($this->current != 1): ?>
                <a  href="javascript:void(0);" onclick="document.getElementById('_jsPage').value='<?php echo 1 ?>'; document.forms['filterform'].submit();" class="button gray">&laquo;&laquo;</a>
            <?php endif; ?>
            
            <?php if($this->current > 1): ?>
                <a href="javascript:void(0);" onclick="document.getElementById('_jsPage').value='<?php echo $this->current - 1; ?>'; document.forms['filterform'].submit();" class="button gray">&laquo;</a>
            <?php endif; ?>
            
            <label>Page</label>
            <span class="button gray"><?php echo $this->current; ?></span>
            <label>of <?php  echo $this->pageCount;?>
              </label> 
            
            <?php if($this->current < $this->pageCount): ?>
                <a href="javascript:void(0);" onclick="document.getElementById('_jsPage').value = '<?php echo $this->current + 1; ?>';document.forms['filterform'].submit(); " class="button gray">&raquo;</a>
            <?php endif; ?>
            <?php if($this->current != $this->pageCount): ?>
                <a href="javascript:void(0);" onclick="document.getElementById('_jsPage').value = '<?php echo $this->pageCount; ?>';document.forms['filterform'].submit();" class="button gray">&raquo;&raquo;</a>
            <?php endif; ?>
        </div>
    </div>
<?php
}
?>
