<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    
    <!--Favicon-->
    <link rel="shortcut icon" href="<?= $this->static->frontend->images.'/favicon-2.ico'?>" type="image/x-icon">
    <link rel="icon" href="<?= $this->static->frontend->images.'/favicon-2.ico'?>" type="image/x-icon">
    <title><?php echo $this->originalName; ?></title>

    <style>
        html {
            height: 100%;
            width: 100%;
        }

        body {
            background: #fff;
            color: #333;
            font-family: Arial, Tahoma,sans-serif;
            font-size: 12px;
            font-weight: normal;
            height: 100%;
            margin: 0;
            overflow-y: hidden;
            padding: 0;
            text-decoration: none;
        }

        form {
            height: 100%;
        }

        div {
            margin: 0;
            padding: 0;
        }
    </style>

    <script type="text/javascript" src="<?php echo DOC_SERV_API_URL ?>"></script>

    <script type="text/javascript">

        var docEditor;        
        var fileType = "<?php echo strtolower(pathinfo($this->filename, PATHINFO_EXTENSION)); ?>";
        var originalName = "<?php echo $this->originalName; ?>";
        var innerAlert = function (message) {
            if (console && console.log)
                console.log(message);
            ;
        };

        var onReady = function () {
            innerAlert("Document editor ready");
        };

        var onBack = function () {
            location.href = "<?php echo BASE_URL; ?>";
        };

        var onDocumentStateChange = function (event) {
            var title = document.title.replace(/\*$/g, "");
            document.title = title + (event.data ? "*" : "");
        };

        var onRequestEditRights = function () {
            if (typeof DocsAPI.DocEditor.version == "function") {
                var version = DocsAPI.DocEditor.version();
                if ((parseFloat(version) || 0) >= 3) {
                    location.href = location.href.replace(RegExp("action=view\&?", "i"), "");
                    return;
                }
            }
            docEditor.applyEditRights(true);
        };

        var onDocumentSave = function (event) {
            SaveFileRequest(fileType, event.data);
        };

        var onError = function (event) {
            if (console && console.log && event)
                console.log(event.data);
        };

        var сonnectEditor = function () {

            docEditor = new DocsAPI.DocEditor("iframeEditor",
                {
                    width: "100%",
                    height: "100%",

                    type: "<?php echo $this->viewType; ?>",
                    documentType: "<?php echo $this->documentType; ?>",
                    document: {
                        title: "<?php echo $this-> originalName; ?>",
                        url: "<?php echo $this->fullURL; ?>",
                        fileType: fileType,
                        key: "<?php echo $this->key; ?>",                        
                        info: {
                            author: "<?php echo $this->arrlogin["nickName"] ?>",
                            created: "<?php echo date('d.m.y') ?>"
                        },
                        permissions: {
                            edit: false,
                            download: true
                        }
                    },
                    editorConfig: {
                        mode: "<?php echo $this->mode; ?>",

                        lang: "en-US",

                        callbackUrl: "<?php echo $this->callbackUrl; ?>",

                        embedded: {
                            saveUrl: "<?php echo $this->fullURL ?>",
                            embedUrl: "<?php echo $this->fullURL ?>",
                            shareUrl: "<?php echo $this->fullURL ?>",
                            toolbarDocked: "top"
                        },
                        customization: {
                            about: false,
                            feedback: false,
                            customer: {
                                address: "G0906 The Manor Officetel, 91 Nguyen Huu Canh Street, Ward 22, Binh Thanh District, HCM city",
                                info: "Gianty Co., Ltd is a member of Global Group, a leading group in Japan which provides cloud computing and digital content products and services",
                                logo: "<?php echo BASE_URL; ?>/static/images/docs/docs_logo.png",
                                mail: "info@gianty.com.vn",
                                name: "Gianty Co.,Ltd",
                                www: "gianty.com.vn",
                            },
                            goback: {
                                url: "<?php echo BASE_URL ?>",
                            },
                            logo: {
                                image: "<?php echo BASE_URL; ?>/static/images/docs/docs_logo.png",
                                url: "<?php echo BASE_URL; ?>",
                            }
                        },
                        user: {
                            name: "<?php $this->nickName ?>",
                            id: "<?php $this->accountID ?>",
                        }
                    },
                    events: {
                        'onReady': onReady,
                        'onBack': <?php echo $this->onBack; ?>,
                        'onDocumentStateChange': onDocumentStateChange,
                        'onRequestEditRights': onRequestEditRights,
                        'onSave': onDocumentSave,
                        'onError': onError
                    }
                });
        };

        if (window.addEventListener) {
            window.addEventListener("load", сonnectEditor);
        } else if (window.attachEvent) {
            window.attachEvent("load", сonnectEditor);
        }

        function getXmlHttp() {
            var xmlhttp;
            try {
                xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
            } catch (e) {
                try {
                    xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                } catch (ex) {
                    xmlhttp = false;
                }
            }
            if (!xmlhttp && typeof XMLHttpRequest != 'undefined') {
                xmlhttp = new XMLHttpRequest();
            }
            return xmlhttp;
        }

        function SaveFileRequest(fileType, fileUri) {
            var req = getXmlHttp();
            if (console && console.log) {
                req.onreadystatechange = function () {
                    if (req.readyState == 4) {
                        console.log(req.statusText);
                        if (req.status == 200) {
                            console.log(req.responseText);
                        }
                    }
                };
            }

            var requestAddress = "<?php echo BASE_URL; ?>/docs/editor-ajax"
                + "?id=" + "<?php echo $this->fileId ?>"
                + "&type=save"                
                + "&filetype=" + encodeURIComponent(fileType)
                + "&fileuri=" + encodeURIComponent(fileUri);
            req.open('get', requestAddress, true);

            req.send(fileUri);
        }

    </script>
</head>
<body>
    <form id="form1">
        <div id="iframeEditor">
        </div>
    </form>
</body>
</html>