<link href="<?= $this->static->frontend->css ;?>/v2/document.css" rel="stylesheet" type='text/css'>
<script src="<?= $this->static->frontend->js ;?>/v2/ng-tags-input.min.js"></script>
<script src="<?= $this->static->frontend->js ;?>/v2/contextMenu_docs.js?v=1.5.6"></script>
<script src="<?= $this->static->frontend->js ;?>/v2/docCtrl.js"></script>
<!-- main document content -->
<div class="_permissiondenied text-center" ng-controller="permissionDeny">
	<img src="<?= $this->static->frontend->images.'/v2/permissiondeny.png'?>" alt="" class="center-block img-responsive">
	<h3 class="text-center text-danger">Permission denied!</h3>
	<div class="text-center">Sorry about that, but you don't have permission to access this file</div>
	<div class="text-center">Click <strong>request</strong> to get access to this file</div>
	<div class="text-center m-t-10"><button class="btn btn-main m-r-10" ng-click="sendRequest()" ng-disabled="loadingRequest">
	<span ng-if="!loadingRequest">Request</span><span ng-if="loadingRequest">Processing...</span></button><a class="btn btn-default _f" href="<?= BASE_URL ?>">Cancel</a></div>
</div>
<script>
	app.factory('permission', function($q, $http, $log){
		return {
			requestShare: function(fileId){
				var params = {
					fileId: fileId,
				}
				var config = {
					headers: {
						'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8;'
					}
				}
				var defer = $q.defer();
				$http.post('/api/docs/request-share-docs', $.param(params), config)
					.success(function (data){
						defer.resolve(data);
					})
					.error(function (msg, code){
						defer.reject(msg);
						$log.error(msg, code);
					});
				return defer.promise;
			},
		}
	});

	app.controller('permissionDeny', function($scope, $http, $q, permission, $rootScope, toastr){
		$scope.loadingRequest = false;
		$scope.sendRequest = function(){
			$scope.loadingRequest = true;
			var path = $rootScope.location.split('/');
			console.log(path[path.length - 1]);
			var fileId = path[path.length - 1];
			permission.requestShare(fileId).then(function successCallback(response){
				if(response){$scope.loadingRequest = false;}
				if(response.error){toastr.error(response.message, 'Error!')}else{toastr.success('Request ok','Success!')}
			}, function errorCallback(response){})
		}
	});
</script>