<div class="row">
                  <h1 class="slogan">WITH YOU, WE CHALLENGE INFINITE POSSIBILITIES</h1>
                  <div class="user-block">            	
                    <div class="user-status">
                         <span class="user-name"><?php echo $this->arrLogin['nickName'];?></span>.
                        <button class="btn btn-link" onClick="doLogOut(); return false;">Logout</button>
                    </div>
                       
                    <span id="newMail"> 

                    </span>  
                 </div>
</div>