  <link rel="stylesheet" href="<?php echo $this->static->frontend->css.'/waves.min.css'?>">
  <!-- mobile nav-->
 <div class="mn-team-mobile hidden-lg hidden-md hidden-sm">
     <div class="t-name">
         <img src="<?= $this->static->frontend->images.'/ios-icon/group-detail.svg';?>" width="32" height="32" alt="">
         <?php echo $this->arrGroup['group_name'];?>
     </div>
     <div class="opt-team">
         <ul>
             <li class="waves-btn">
                <a href="<?= BASE_URL;?>/user/feed/groupid/<?= $this->groupid;?>">
                    <img src="<?= $this->static->frontend->images.'/ios-icon/chart.svg';?>" alt=""
                    width="32" height="32">
                    <span><?= $this->locales->group->activitystream;?></span>
                </a>
             </li>
             <li class="waves-btn active">
                <a class="active" disabled="disabled" href="<?= BASE_URL;?>/group/document/g/<?= $this->groupid;?>/p/0">
                    <img src="<?= $this->static->frontend->images.'/ios-icon/document.svg';?>" alt="" width="32" height="32">
                    <span><?= $this->locales->group->document;?></span>
                </a>
            </li>
            <li class="waves-btn">
                <a href="<?= BASE_URL ?>/group/calendar/groupid/<?= $this->groupid ?>/group-type/<?= $this->arrGroupList['group_type'] ?>">
                    <img src="<?= $this->static->frontend->images.'/ios-icon/calendar-svg.svg';?>" alt="" width="32" height="32">
                    <span><?= $this->locales->group->calendar;?></span>
                </a>
            </li>
            <li class="waves-btn">
                <a href="<?= BASE_URL;?>/user/index/groupid/<?= $this->groupid;?>">
                    <img src="<?= $this->static->frontend->images.'/ios-icon/group-detail.svg';?>" alt="" width="32" height="32">
                    <span><?= $this->locales->group->member;?></span>
                </a> 
            </li>
            <li class="waves-btn">
                <a href="<?= BASE_URL;?>/group/update/id/<?= $this->groupid;?>">
                    <img src="<?= $this->static->frontend->images.'/ios-icon/settings.svg';?>" alt="" width="32" height="32">
                    <span><?= $this->locales->group->setting;?></span>
                </a>
            </li>
         </ul>
     </div>
 </div>
 <!--end mobile nav-->
  <!--Menu header -->
      <div class="header-menu-team clearfix hidden-xs">
        <div class="title-team">
              <i class="fa fa-group"></i>
              <span><?php echo $this->arrGroup['group_name'];?></span>
          </div>
          <ul class="function-menu-team">
            <li>
                <a href="<?php echo BASE_URL;?>/user/feed/groupid/<?php echo $this->groupId;?>">
                    <i class="fa fa-area-chart"></i>
                      <span><?php echo $this->locales->group->activitystream;?></span>
                  </a>
              </li>
              <li>
                <a class="active" href="<?php echo BASE_URL;?>/group/document/g/<?php echo $this->groupId;?>/p/0">
                    <i class="fa fa-folder-open"></i>
                      <span><?php echo $this->locales->group->document;?></span>
                  </a>
              </li>
              <li>
                <a href="<?= BASE_URL ?>/group/calendar/groupid/<?= $this->groupId ?>/group-type/<?= $this->groupType ?>">
                    <i class="fa fa-calendar"></i>
                      <span><?php echo $this->locales->group->calendar;?></span>
                  </a>
              </li>
               
              <li>
                <a href="<?php echo BASE_URL;?>/user/index/groupid/<?php echo $this->groupId;?>">
                    <i class="fa fa-user"></i>
                      <span><?php echo $this->locales->group->member;?></span>
                  </a> 
              </li>
              <li>
                <a href="<?php echo BASE_URL;?>/group/update/id/<?php echo $this->groupId;?>">
                    <i class="fa fa-cog"></i>
                      <span><?php echo $this->locales->group->setting;?></span>
                  </a>
              </li>
          </ul>
      </div> 
<!-- Menu header-->
  <div class="document-wrapper">
    <div class="tab-option">
    <ul>
      <li><!-- <a href="#" class="documentFolder"><i class="fa fa-plus-square fa-fw"></i>New folder</a> -->
       <button class="btn btn-primary  btn-newFolder"><i class="fa fa-plus-square fa-fw"></i>New folder</button>
      </li>
      <!-- <li><a href="#" class="document-uploadFile"><i class="fa fa-cloud-upload fa-fw"></i>Upload file</a></li> -->
      <li>
        <div class="fileUpload btn btn-success ">
          <span><i class="fa fa-cloud-upload fa-fw"></i>Upload</span>
          <input type="file" class="upload" id="chosenFile" onchange="checkFileDocument(this,'',false);"/>
        </div>
      </li>
    </ul>
    </div>
    
    <div class="breadcrumbFolder">
      <ul>
        <li onclick="backFolder();"><a href="javascript:void(0);"><i class="fa fa-arrow-left"></i></a></li>
        <li><a href="<?php echo BASE_URL;?>/group/document?g=<?php echo $this->groupId;?>"><i class="fa fa-refresh"></i></a></li>
        <li class="link-documentFolder">
        <?php echo $this->pathFolder;?>
        </li>
      <ul>
    </div>
    
    <div class="folder-wrapper">
       <ul>     
       <?php

       	if(!empty($this->arrFiles) && $this->arrFiles['total'] > 0){

        foreach ($this->arrFiles['data'] as $file){

	       		if ($file['type'] == FOLDER) {?>
                <li style="position:relative;" data-item="document">
                <div class="folderWrapper" onclick="showFile('<?php echo $file["_id"];?>');">
			          <div class="<?php if($this->arrLogin['accountID'] == $file['owner']){ echo "icon-imgFolder";} else{ echo "icon-imgFolderOwner";}?>" ></div>
			          <div class="nameFolder"><?php echo $file['name'];?></div>
                </div>
                    <!--option delete folder-->
					<?php if($this->arrLogin['accountID'] == $file['owner']){?> 
                     <div class="optionFolder"  style="position:absolute;top:0;right:0;cursor:pointer;display:none;">
                       <i class="fa fa-trash fa-fw delFile" data-id="<?php echo $file["_id"];?>"></i>
                     </div>
					<?php }?>
                     <!--end option delete folder -->
              </li>
	      <?php }else{ ?>
	      			 <li style="position:relative;" data-item="document">
	      			 	<?php if(Core_Common::endsWith($file['name'], ".doc") || Core_Common::endsWith($file['name'], ".docx")){?>
	      			 			<div class="icon-imgWord"></div>
		          				<div class="nameFolder"><?php echo $file['name'];?></div>
	      			 	<?php }?>
	      			 	<?php if(Core_Common::endsWith($file['name'], ".xls") || Core_Common::endsWith($file['name'], ".xlsx")){?>
	      			 			<div class="icon-imgExcel"></div>
		          				<div class="nameFolder"><?php echo $file['name'];?></div>
	      			 	<?php }?>
	      			 	<?php if(Core_Common::endsWith($file['name'], ".ppt") || Core_Common::endsWith($file['name'], ".pptx")){?>
	      			 			<div class="icon-imgPptx"></div>
		          				<div class="nameFolder"><?php echo $file['name'];?></div>
	      			 	<?php }?>
<!--	      			 	--><?php //if(Core_Common::endsWith($file['name'], ".pdf") || Core_Common::endsWith($file['name'], ".pdf")){?>
	      			 	<?php if(Core_Common::endsWith($file['name'], ".pdf")){?>
	      			 			<div class="icon-imgPdf"></div>
		          				<div class="nameFolder"><?php echo $file['name'];?></div>
	      			 	<?php }?>
                
                <div class="optionFolder"  style="position:absolute;top:0;right:0;cursor:pointer;display:none;">
                  <a href="<?php echo BASE_URL.'/upload/download-feed-document/id/'.$file['_id'];?>"><i class="fa fa-cloud-download dowFile"></i></a>
				  <?php if($this->arrLogin['accountID'] == $file['owner']){?>
					<i class="fa fa-trash fa-fw delFile" data-id="<?php echo $file["_id"];?>"></i>
				  <?php }?>
                </div>
                
	      			 </li>
	      <?php }?>
       		
        <?php }
         }?>
      </ul> 

     <?php echo $this->render('pagination_document.phtml');?>
    
    </div>
  </div>


<!-- Popup Newfolder file-->
<div class="popup-selectFile newFolderWrapper" id="draggable">
  <div class="title-selectFile">New folder<span class="close-FilePopup pull-right text-right clearfix"><i class="fa fa-times"></i></span></div>
  <div class="form-group formNewFolder">
    <label for="folderName">Folder Name:</label>
    <input type="text" id="folderName" name="folderName" class="form-control folderName">  
  </div>
  
  <div class="text-center group-selectFilebutton">
    <button class="btn btn-primary btn-sm" onclick="createFolder();">Create Folder</button>
    <button class="btn-cancelFolder btn btn-default btn-sm">Cancel</button>
  </div>
</div>

<input type="hidden" id="group_id" value="<?php echo $this->groupId;?>"/>
<input type="hidden" id="parent" value="<?php echo $this->parent; ?>"/>
  <!--Start Popup check file--><!--muon show thi display:block; an? display:none;-->
  <div class="overlayCheckFile">
      <div class="popupWrapper">
          <i class="fa fa-times" data-action="cancel-replace" ></i>
          <div class="proccessDocument">
              <h3>Upload new document</h3>
              <div class="form-inline-01">
                  <div class="form-group">
                      <input type="text" class="form-control" data-item="file-name-replace" placeholder="">
                  </div>
                  <button type="button" class="btn btn-primary" data-action="replace">Replace</button>
                  <button type="button" class="btn btn-default" data-action="cancel-replace" >Cancel</button><br/>
                  <span class="text-danger">This file has already exists.</span>
              </div>
<!--              <button type="button" class="btn btn-success" data-action="add-new-file" >Upload more</button>-->
<!--              <button type="button" class="btn btn-default" data-action="cancel-replace" >Close</button>-->
          </div>
      </div>
  </div>
  <!--End popup check file-->
          <script>
              var lastBreadCrumb = {g:<?php echo $this->groupId;?>, p:<?php echo $this->parent;?>, f:'<?php echo $this->nameFolder;?>'};
              $(function(){

                  $(document).ready(function(){
                      $('body').on('click', '[data-action="replace"]', function(){
                          $('[data-action="add-new-file"]').prop('disabled',true);
                          $('[data-action="replace"]').prop('disabled',true);
                          checkFileDocument(null,$('[data-item="file-name-replace"]').val(),false,true);
                      });

                      $('body').on('click', '[data-action="add-new-file"]', function(){
                          $('[data-action="add-new-file"]').prop('disabled',true);
                          $('[data-action="replace"]').prop('disabled',true);
                          checkFileDocument(null,'',true);
                      });

                      $('body').on('click', '[data-action="cancel-replace"]', function(){
                          $('#chosenFile').val('');
                          $('[data-item="file-name-replace"]').val('');
                          $('.overlayCheckFile').hide();
                      });
                  });
              });

              $('.title-selectFile').mouseover(function(){
                    $( "#draggable" ).draggable({ disabled: false});
              });
              $('.title-selectFile').mouseout(function(){
                    $( "#draggable" ).draggable({ disabled: true });
              });

              $("body").on('click', '.btn-newFolder', function(){
                $(".popup-selectFile").show();
              });

              $("body").on('click','.close-FilePopup', function(){
                $(".popup-selectFile").hide();
              });

              $("body").on('click','.btn-cancelFolder',function(){
                $(".popup-selectFile").hide();
              });
              
              function createFolder(){
                  var g = $("#group_id").val();
                  var p = $("#parent").val();
                  var f = $("#folderName").val();
                  
            	     //create file
                     $.post(baseurl + "/group/create-folder",{
                    	        'g': g, 'p':p, 'f':f, 't':<?php echo FOLDER;?>
                    	    }, function(data){ 
                        	    if(data.error == 1){      
                            	    alert(data.message);
                        	    }else{
                    	      		window.location.href = baseurl + '/group/document?g=' + g + '&p=' + p;
                        	    }
                    },'json');
                	 
              }

              /*check file type*/
              function checkFileDocument(sender,reName,addNew,replace) {

            	  var p = $("#parent").val();
            	  var g = $("#group_id").val();
                  reName = (typeof reName === 'undefined') ? '' : reName;
                  addNew = (typeof addNew === 'undefined') ? false : addNew;
                  replace = (typeof addNew === 'undefined') ? false : replace;
				  //user must create a folder before upload
				  if(p < 1){
					alert('Please select or create a folder before upload files.');
					return false;
				  }

//                  var validExts = new Array(".xlsx", ".xls", ".pdf", ".doc", ".docx", ".ppt", ".pptx");
//                  var fileExt = sender.value;
//                  fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
//                  if (validExts.indexOf(fileExt) < 0) {
//                    alert("Invalid file selected, valid files are of " +
//                             validExts.toString() + " types.");
//                    return false;
//                  }

                  $.ajax({
                      url: baseurl + "/upload/upload-document",
                      type: "POST",
                      contentType: false,
                      processData: false,
                      dataType: "json",
                      data: function() {
                          var data = new FormData();
                          data.append("chosenFile", jQuery("#chosenFile").get(0).files[0]);
                          data.append("re-name", reName);
                          data.append("replace", replace);
                          data.append("add-new", addNew);
                          data.append("g", lastBreadCrumb.g);
                          data.append("p", lastBreadCrumb.p);
                          data.append("f", lastBreadCrumb.f);
                          return data;
                          /* Or simply return new FormData(jQuery("form")[0]);*/
                      }(),
                      error: function(_, textStatus, errorThrown) {
                          alert("upload file error");

                      },
                      success: function(response, textStatus) {

                      	if(response.error == 0){
                            window.location.href = baseurl + '/group/document?g=' + g + '&p=' + p;
                          	//create file
//                      		$.post(baseurl + "/group/create-folder",{
//                    	        'g': g, 'p':p, 'f':response.filename, 't':<?php //echo FILE;?>//, 'path':response.path
//                    	    }, function(data){
//                        	    if(data.error == 1){
//                            	    alert(data.message);
//                        	    }else{
//                    	      		window.location.href = baseurl + '/group/document?g=' + g + '&p=' + p;
//                        	    }
//                    	 },'json');

                      	}else{
                            $('[data-action="add-new-file"]').prop('disabled',false);
                            $('[data-action="replace"]').prop('disabled',false);
                            if(typeof response.file_already !== 'undefined')
                            {
                                $('[data-item="file-name-replace"]').val(response.filename);
                                $('.overlayCheckFile').show();
                            }else
                                AlertFail(response.message);
                      	}
                      }
                  });



              }

              function showFile(parent){
            	  var g = $("#group_id").val();
            	  window.location.href = baseurl + '/group/document?g=' + g + '&p=' + parent;
              }

              function backFolder(){
            	  var p = $("#parent").val();
            	  var g = $("#group_id").val();

            		$.post(baseurl + "/group/back-folder",{
          	        'g': g, 'p':p
	          	    }, function(data){ 
	              	    if(data.error == 1){      
	                  	    alert(data.message);
	              	    }else{
	          	      		window.location.href = baseurl + '/group/document?g=' + g + '&p=' + data.p;
	              	    }
	          	 	},'json');
              }

              //paging
              function clickNumber(page){
            	  var p = $("#parent").val();
            	  var g = $("#group_id").val();
            	  window.location.href = baseurl + '/group/document?g=' + g + '&p=' + p + '&page=' + page;
              }
              
              //delete file
              $('body').on('click', ".delFile", function(event){
                  var _this = $(this);
                  if(!confirm('Do you want to delete ?'))
                    return false;
                  var id = $(this).data("id");

            		$.post(baseurl + "/group/delete-document",{
          	        'id': id
	          	    }, function(data){
                        console.log(data);
	              	    if(data.error == 1){
	                  	    alert(data.message);
	              	    }else
                            _this.parents('[data-item="document"]').remove();
//	          	      		window.location.href = baseurl + '/group/document?g=' + data.g + '&p=' + data.p;
//	              	    }
	          	 	},'json');
              });
              //download file
               
               /*$(".dowFile").live('click',function(event){
                  alert('Download!');
              });*/

              $(".folder-wrapper ul li").hover(function(){
                $(this).find('.optionFolder').toggle();
              });
         </script>
<script src="<?php echo $this->static->frontend->js.'/waves.min.js'?>"></script>
<script type="text/javascript">
    Waves.init();
    Waves.attach('.waves-btn', ['waves-block']);
</script>
                    
