<?php
$group = $this->group;
if(empty($group))
    die('Data not found');
$group  = Core_Common::groupProcess($group);
$countries = $this->countries;
$bomMembers = $this->bomMembers;
$groupType  = $this->groupType;
?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Edit group <?php echo '" '.$group['group_name'].' "'; ?></h4>
</div>
<div class="modal-body" >
    <form role="form" data-item="f-update-group">
        <div class="form-group">
            <label for="name">Name:</label>           
            <input type="text" name="group_name" value="<?php echo $group['group_name']; ?>" class="form-control" id="name">
        </div>

        <div class="form-group">
            <label for="type">Type:</label>
            <input type="text" disabled value="<?php echo isset($groupType[$group['group_type']]) ? $groupType[$group['group_type']] : 'Other'; ?>" class="form-control" id="type">
        </div>

        <div class="form-group">
            <label for="privacy">Privacy:</label>
            <select name="is_public">
                <option value="0">private</option>
                <option value="1">public</option>
            </select>
        </div>

        <?php  if($group['group_type'] > 0 && $group['group_type'] < 4) {  ?>

        <div class="form-group">
            <label for="country">Country:</label>
            <select name="country_id">
            <?php foreach($countries as $key=>$country){?>
<!--                <option value="--><?php //echo $key;?><!--" --><?php //if($key == $group['country_id']) { echo 'checked';}?><!--> --><?php //echo $country;?><!-- </option>-->
                <option value="<?php echo $key;?>"> <?php echo $country;?> </option>
            <?php } ?>
            </select>
        </div>

        <div class="form-group">
            <label for="admin">Admin:</label>
            <?php
            if($group['group_type'] == 2) {
                if (!empty($bomMembers['data'])) {
                    ?>
                    <select name="admin_id">
                        <option value="0"> ----------- </option>
                        <?php foreach($bomMembers['data'] as $member) {
                        ?>
                        <option value="<?php echo $member['account_id']; ?>">
                            <?php echo $member['name']; ?>
                        </option>
                        <?php } ?>
                    </select>
                <?php }
            }
            else{ ?>

            <input autocomplete="off" data-action="user-search" type="text" value="<?php echo $group['admin_name']; ?>"  name="admin_name"  class="form-control">
            <input data-action="user-id" name="admin_id"  value="<?php echo $group['admin_id']; ?>"  type="hidden"/>
            <?php } ?>
        </div>


        <div class="form-group">
            <label for="manager">Manager:</label>
            <input autocomplete="off" data-action="user-search" type="text" value="<?php echo $group['manager_name']; ?>"  name="manager_name"  class="form-control">
            <input data-action="user-id" name="manager_id"  value="<?php echo $group['manager_id']; ?>"  type="hidden"/>
        </div>
        <?php } ?>
        <div class="form-group">
            <label for="order">Order:</label>
            <input name="sort_order" type="text" class="form-control" value="<?php echo $group['sort_order']; ?>" id="order">
        </div>

        <div class="form-group">
            <label for="type">Active:</label>
            <div class="checkbox">
                <label> Yes <input type="radio" name="active" class="" value="1" checked=""></label>
                <label> No <input type="radio" name="active" class="" value="0"></label>
            </div>
        </div>

        <div class="form-group">
            <input type="file"  id="chosenImage"onchange="installCheckImageUpload(this)">
            <input type="hidden" name="image_url" id="image_url"/>
        </div>
        <input type="hidden" name="group_id" value="<?php echo $group['group_id']; ?>"/>
        <input type="hidden" name="group_type" value="<?php echo $group['group_type'] ?>">
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="button" data-action="update-group" class="btn btn-primary">Save changes</button>
</div>
<script>
    $(function(){

        $("a[data-target=#myModal]").click(function(ev) {
            ev.preventDefault();
            var target = $(this).attr("href");

            // load the url and show modal on success
            $("#myModal .modal-content").load(target, function() {
                $("#myModal").modal("show");
            });
        });

        var methodAjax = 'editFreeGroup';
        <?php  if($group['group_type'] > 0 && $group['group_type'] < 4) { ?>
        var methodAjax = 'edit';
        createDisplayObjectHtml($('input[name="manager_name"]'),'','user-search-result');
        createDisplayObjectHtml($('input[name="admin_name"]'),'','user-search-result');
        <?php } ?>
        $('select[name="is_public"]').val("<?php echo $group['is_public'];?>");
        $('select[name="country_id"]').val("<?php echo $group['country_id'];?>");
        $('input[name="active"][value="<?php echo $group['active']; ?>"]').prop('checked',true);
        $('body').on('click','[data-action="update-group"]', function(){
            $.post("<?= BASE_URL.'/api/token/index'; ?>", {'method': 'generateToken'}, function (token) {
                $.post(baseurl + '/api/group/index?token='+token+'&method=' + methodAjax, $('[data-item="f-update-group"]').serialize(), function (response) {
                    var errors = response.body;
                    $('.alert-danger').remove();
                    $('.alert-success').remove();
                    //console.log(parseInt(errors.length));
                    if (parseInt(errors.length) > 0) {
                        var _html = '';
                        $.each(errors, function (index, value) {
                            var field = value.field.replace('_', ' ');
                            _html += '<p>' + field + ' ' + value.message + '</p>';
                        });
                        $('.modal-body').prepend('<div class="alert alert-danger">' + _html + '</div>');
                    }
                    else {
                        $('.modal-body').prepend('<div class="alert alert-success"> Update Success !</div>');
                        window.top.location.reload();
                    }
                });
            });

        });
        $('body').on('input propertychange paste','[data-action="user-search"]',function(e){
            var _this   = $(this);
            var _val = $.trim($(this).val());
            var resultPlace =  _this.parent().find('.user-search-result');
            var userIdEle = _this.parent().find('input[data-action="user-id"]');
            userIdEle.val(0);

            if(_val == '') {
                resultPlace.hide();
                return;
            }
            var params      = {};
            params['key']   = _val;
            params['team']  = '';
            var _html       = '<li class="clearfix">No Data</li>';

            $.post("<?php echo BASE_URL.'/user/searchuser'; ?>", { data: JSON.stringify(params)}, function(data){
                if(data.total > 0)
                {
                    _html    = '';
                    $.each(data['data'], function(index, account){
                        _html += suggesstionLI(account.image_tag,account.name,account.position_name,account.account_id, 'addname');
                    });
                }
                resultPlace.find('ul').html(_html);
                resultPlace.show();

            },'json');
        });

        $('body').on('click','.addname',function(e){
            var _this = $(this);
            var display = _this.parents('.user-search-result');
            var userIdEle =   display.parent().find('input[data-action="user-id"]');
            var inputSearch = display.parent().find('input[data-action="user-search"]');
            var account_id = $(this).attr('data-aId');
            var name = $(this).attr('data-name');

            userIdEle.val(account_id);
            display.fadeOut(100);
            inputSearch.val(name);
            inputSearch.focus();


        });

        function suggesstionLI(avatar, name, position, account_id, class_name){
            return '<li class="'+class_name+'" data-aId="' + account_id + '"  data-name="' + name + '">'+
                '<a href="javascript:void(0);">'+
                '<div class="inform-tags-members clearfix">'+
                '<div class="img-tags-members mg10 fl">'+
                '<img alt="" width="36" src="' + avatar + '">'+
                ' <strong> ' + name + ' </strong> '+
                ' <span> ' + position + ' </span> '+
                '</div>'+
                '</div>'+
                '</a>'+
                '</li>';
        }
    });
    function installCheckImageUpload(sender)
    {
        var inputHiddenElement  = $('[name="image_url"]');
        var inputImageName      = $('[name="image_name"]');
        var inputImage  = $('#avatar');

//        sender,urlUpload,jsonData,inputHiddenElement,inputImage
        var jsonData    = [{'input_name':'f','input_val':'news'}];
        checkImageUpload(sender,baseurl+'/upload/index',jsonData,inputHiddenElement,inputImage,inputImageName);
    }
</script>
