
<link href="../static/css/v2/group.css" rel="stylesheet" type='text/css'>

<!--data-table css-->
<link rel="stylesheet" type="text/css" href="<?= $this->static->frontend->js . '/datatable/css/jquery.dataTables.css' ?>" media="screen">
<link rel="stylesheet" type="text/css" href="<?= $this->static->frontend->js . '/datatable/css/dataTables.tableTools.css' ?>" media="screen">
<link rel="stylesheet" type="text/css" href="<?= $this->static->frontend->js . '/datatable/css/datatable.responsive.css' ?>" media="screen">
<!--data-table css-->

<script src="../static/js/v2/groupController.js"></script>

<script src="<?= $this->static->frontend->js ;?>/v2/ng-tags-input.min.js"></script>
<script src="<?= $this->static->frontend->js ;?>/v2/contextMenu.js"></script>

<!--<script type="text/javascript" src="--><?//= $this->static->frontend->js . '/feed.js'; ?><!--"></script>-->

<!--data-table js-->
<script type="text/javascript" src="<?= $this->static->frontend->js . '/datatable/js/jquery.dataTables.min.js' ?>"></script>
<script type="text/javascript" src="<?= $this->static->frontend->js . '/datatable/js/dataTables.tableTools.js' ?>"></script>
<script type="text/javascript" src="<?= $this->static->frontend->js . '/datatable/js/datatable.responsive.min.js' ?>"></script>
<script type="text/javascript" src="<?= $this->static->frontend->js . '/v2/group/work-group.js' ?>"></script>
<!--data-table js-->

<div class="groupWrapper">
    <div ng-cloak class="contain-request-list">
        <div class="menu-leave">
            <?php echo $this->render('partial_tab_group.phtml'); ?><!-- menu-leave -->
        </div>
        <div class="container-all-groups clearfix" data-item="lst-group">  
            <div class="contentInvite">
                <div class="subTab">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#inviteSent">Invitations sent</a></li>
                        <li><a data-toggle="tab" href="#inviteReceived">Invitations received</a></li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div id="inviteSent" class="tab-pane fade in active">
                        <div class="boxCheck">
                            <input id="invite-sent-select-all" type="checkbox">
                            <i class="fa fa-close" aria-hidden="true" data-action="invite-sent-del-all"></i>
                        </div>                        
                        <table class="table table-hover table-condensed" id="invite-sent-table" class="display">
                            <thead>
                            <tr role="row">
                                <th></th>
                                <th>Request ID</th>
                                <th>Group name</th>
                                <th>Name</th>
                                <th>Employee ID</th>
                                <th>Team</th>
                                <th  class="btnAction">Action</th>
                                <th>GroupId</th>
                                <th>Type</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <div id="inviteReceived" class="tab-pane fade">
                        <div class="boxCheck">
                            <input id="invite-received-select-all" type="checkbox">
                            <i class="fa fa-close" aria-hidden="true" data-action="invite-received-del-all"></i>
                        </div>   
                        <table class="table table-hover table-condensed" id="invite-received-table">
                            <thead>
                            <tr role="row">
                                <th></th>
                                <th>Request ID</th>
                                <th>Group name</th>
                                <th>Name</th>
                                <th>Employee ID</th>
                                <th>Team</th>
                                <th class="btnAction">Action</th>
                                <th>GroupId</th>
                                <th>Type</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>    
     <!-- show popup delete or leave group -->
     <div class="md-overlay"></div>
    <nav id="cbp-spmenu-s2" class="contain-add-group cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right project-panel  popupConfirmDelete popupConfirmRequest">
        <div class="rmv-pushright pull-right iconClose">
            <i class="fa fa-times"></i>
        </div>
        <p class="desPopup">Do you want to delete this record?</p>
        <div class="boxBtn-Group">                
            <a class="btn btn-default btn-cancel-group btnClose" href="javascript:void(0);">
                Cancel
            </a>
            <a class="btn btn-primary btnDelete" href="javascript:void(0);">
                Delete
            </a>
        </div>
    </nav>           
</div>   
<script type="text/javascript">
    $(function(){        
        installDataTable($('#invite-sent-table'),$('#invite-sent-select-all'),'#invite-sent-table [data-action="delete"]','[data-action="invite-sent-del-all"]','#invite-sent-table [data-item="cb-delete[]"]',1);

        var _installTable = true;
        $('a[href="#inviteReceived"]').click(function(){
            if(!_installTable)
                return;

            _installTable = false;
            installDataTable($('#invite-received-table'),$('#invite-received-select-all'),'#invite-received-table [data-action="delete"]','[data-action="invite-received-del-all"]','#invite-received-table [data-item="cb-delete[]"]',3);
        })
    })
</script>