<?php foreach ($this->arrGroupMember as $group) {
    $show_more = false;
    if ($group['group_type'] != 1) {
        ?>

        <div class="contain-album">
            <div class="title-page">
                <h4><?php echo $group['group_name']; ?></h4>
            </div>
            <div class="contain-photos">
                <ul class="photos clearfix">

                    <?php if (isset($this->arrAlbumTeam[$group['group_id']])) {
                        $total = $this->arrTotalAlbum[$group['group_id']]['total'] - count($this->arrAlbumTeam[$group['group_id']]);
                        $show_more = true;
                        ?>

                        <?php
                        foreach ($this->arrAlbumTeam[$group['group_id']] as $value) {
                            ?>
                            <li>
                                <a href="<?php echo BASE_URL; ?>/photo/albumdetail?a_id=<?php echo $value['album_id']; ?>&g_id=<?php echo $value['group_id']; ?>">
                                    <div class="iframe">
                                        <div class="ifram-img-in">

                                            <img style="width: 100%; height: 100%"
                                                 src="<?php echo $this->urlImage . $value['image_url']; ?>" alt="">

                                        </div>
                                    </div>
                                </a>

                                <p><?php echo substr($value['name'], 0, 50) . '...'; ?></p>
                                <span><?php echo $value['total']; ?> photos</span>
                            </li>
                        <?php }
                    } ?>
                </ul>
                <?php if ($show_more && $total > 0) { ?>
                    <p class="txt-center">
                        <a data-group="<?php echo $group['group_id']; ?>" class="btn btn-success showmore-photo"
                           data-offset="1" data-action="show-more-album"
                           href="javascript:void(0);">show more</a>
                    </p>
                <?php } ?>
            </div>
        </div>
    <?php }
}
    ?>