<div class="col-lg-12 title_group"><span>Favourites</span> <span>(2)</span></div>
<?php foreach ($this->MyGroups as $group) {
    $group = Core_Common::groupProcess($group);
    ?>
    <div class="col-md-3" data-item="group">
        <div class="media  _itemgroup clearfix">
            <div class="media-body">
                <div class="pull-left m-r-10 "><a href="javascript:;"><?php echo $group['imageUrl']; ?></a></div>
                <div class="wrap-content-group">
                        <!-- <span class="media-heading text-bold"
                        title="<?php echo $group['group_name']; ?>"><?php echo $group['group_name']; ?></span> -->
                        <!-- Single button -->
                        <div class="btn-group">
                            <div class="name-group" title="<?php echo $group['group_name']; ?>" ><a href="javascript:;"><?php echo $group['group_name']; ?></a></div>
                            <div class="toggle_sub dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                 <span class="caret"></span>
                            </div>
                            <ul class="dropdown-menu">
                                <li><a href="javascript:;">Add to Favorites</a></li>
                                <li><a href="javascript:;">Turn Off Notification</a></li>
                                <?php if ($group['is_admin'] == 1) { ?>                                    
                                    <li role="separator"><span  class="divider"></span></li>
                                    <li><a href="<?php echo BASE_URL . '/group/update/id/' . $group['group_id']; ?>">
                                        Edit
                                    </a></li>
                                    <li><a href="javascript:void(0);"  data-action="delete-group"
                                    data-value="<?php echo $group['group_id']; ?>">
                                        Delete
                                    </a></li>
                                <?php } ?>
                                <?php if ($group['account_id'] !== $this->arrLogin['accountID']) {
                                    if ($group['group_type'] == 0 || $group['group_type'] == 4) {
                                        ?>                                        
                                        <li role="separator"><span  class="divider"></span></li>
                                        <li><a href="javascript:void(0);"
                                                onclick="leaveGroup('<?php echo $group['group_id']; ?>',this);">
                                            Leave Group
                                        </a></li>
                                    <?php }
                                }
                                ?>
                            </ul>
                        </div>
                    <div class="_tsrs">
                        <span class="text-muted"><?php echo $group['total']; ?> members</span>
                        <!--<div class="btn-group">
                            <?php if ($group['is_admin'] == 1) { ?>
                                <a href="<?php echo BASE_URL . '/group/update/id/' . $group['group_id']; ?>"
                                   class="btn btn-default btn-sm">Edit
                                </a>
                                <a href="javascript:void(0);" class="btn btn-default btn-sm" data-action="delete-group"
                                   data-value="<?php echo $group['group_id']; ?>">
                                    Delete
                                </a>
                            <?php } ?>
                            <?php if ($group['account_id'] !== $this->arrLogin['accountID']) {
                                if ($group['group_type'] == 0 || $group['group_type'] == 4) {
                                    ?>
                                    <button href="javascript:void(0);" class="btn btn-default btn-sm"
                                            onclick="leaveGroup('<?php echo $group['group_id']; ?>',this);">
                                        Leave
                                    </button>
                                <?php }
                            }
                            ?>
                            </ul>
                        </div> -->
                        <!-- btn-group-->
                    </div>
                </div>
            </div><!-- content-group -->
            <!--<?php if ($group['is_manager']) { ?>
                <span class="role">Manager</span>
            <?php } else if ($group['is_admin']) {
                ?>
                <span class="role">Admin</span>

                <?php
            } ?> -->
        </div><!-- media-->
    </div><!-- end col-md-4 -->

<?php } ?>