
<link href="../static/css/v2/group.css" rel="stylesheet" type='text/css'>

<script src="<?= $this->static->frontend->js ;?>/v2/ng-tags-input.min.js"></script>
<script src="<?= $this->static->frontend->js ;?>/v2/contextMenu.js"></script>
<div class="groupWrapper" ng-controller="groupController">
    <div ng-cloak class="contain-request-list">
        <div class="menu-leave">
            <?php echo $this->render('partial_tab_group.phtml'); ?><!-- menu-leave -->
        </div>
        <div class="container-all-groups clearfix" data-item="lst-group">
            <div id="containerMyGroup" name="iframeGroup">
                <div class="row" >
                    <div class="col-lg-12 title_group"><span>{{arrFavorite.name}}</span> <span>({{arrFavorite.total}})</span></div>
                    <div class="col-md-3" ng-repeat="groupFa in arrFavorite.data" data-item="group">
                        <div class="media  _itemgroup clearfix">
                            <div class="media-body">
                                <div class="pull-left">
                                    <a ng-href="/feed/feed-group/group-id/{{groupFa.group_id}}">
                                        <img  width="80px" height="80px" class="imgs-sub-circle" ng-src="../upload/group/200x200/{{groupFa.image_url}}">
                                    </a>
                                </div>
                                <div class="wrap-content-group">
                                    <div class="btn-group">
                                        <div class="name-group" title="{{groupFa.group_name}}">
                                            <a class="groupNameText" ng-href="/feed/feed-group/group-id/{{groupFa.group_id}}">{{groupFa.group_name}}</a>
                                        </div>
                                        <div class="toggle_sub dropdown-toggle iconToggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                             <span class="caret"></span>
                                        </div>
                                        <ul class="dropdown-menu">
                                            <li ng-if="optionRemoveFavorite(groupFa)"><a href="javascript:;" ng-click="removeFavoriteFunc(groupFa, myFavorite)">Remove to Favorites</a></li>
                                            <li><a href="javascript:;" ng-if="offNotifyGroup(groupFa)" ng-click="turnOffNotifyFunc(groupFa)" >Turn Off Notification</a></li>
                                            <li><a href="javascript:;" ng-if="onNotifyGroup(groupFa)" ng-click="turnOnNotifyFunc(groupFa)">Turn On Notification</a></li>
                                        </ul>
                                    </div>
                                    <div class="_tsrs">
                                        <span class="text-muted">{{groupFa.total}} members</span>
                                    </div>
                                </div> 
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" ng-repeat="group in arrGroup">
                    <div class="col-lg-12 title_group"><span>{{group.name}}</span> <span>({{group.total}})</span></div>
                    <div class="col-md-3" data-item="group" ng-show="group.createGroup">
                        <div class="media  _itemgroup clearfix boxCreateGroup" >
                            <div class="media-body">
                                <div class="wrap-content-group">
                                    <div class="btn-group  btn-search-join">
                                        <div class="name-group fl btnCreateGroup" title="Create Group">
                                            <a href="javascript:void(0);" ng-click="showPopupCreate()">
                                                <span class="iconCreate"></span>
                                                <span>Create Group</span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3" ng-repeat="myGroup in group.data | orderBy: group_name" data-item="group">
                        <div class="media  _itemgroup clearfix">
                            <div class="media-body">
                                <div class="pull-left">
                                    <a ng-href="/feed/feed-group/group-id/{{myGroup.group_id}}">
                                        <img  width="80px" height="80px" class="imgs-sub-circle" ng-src="../upload/group/200x200/{{myGroup.image_url}}">
                                    </a>
                                </div>
                                <div class="wrap-content-group">
                                    <div class="btn-group">
                                        <div class="name-group" title="{{myGroup.group_name}}">
                                            <a ng-href="/feed/feed-group/group-id/{{myGroup.group_id}}" class="groupNameText">{{myGroup.group_name}}</a>
                                        </div>
                                        <div class="toggle_sub dropdown-toggle iconToggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                             <span class="caret"></span>
                                        </div>
                                        <ul class="dropdown-menu">
                                            <li><a href="javascript:;" ng-click="addFavoriteFunc(myGroup, group)">Add to Favorites</a></li>
                                            <li><a href="javascript:;" ng-if="offNotifyGroup(myGroup)" ng-click="turnOffNotifyFunc(myGroup)" >Turn Off Notification</a></li>
                                            <li><a href="javascript:;" ng-if="onNotifyGroup(myGroup)" ng-click="turnOnNotifyFunc(myGroup)">Turn On Notification</a></li>
                                            <li ng-if="optionEditDelete(myGroup)" role="separator"><span class="divider"></span></li>
                                            <li ng-if="optionEditDelete(myGroup)" ng-click="showPopupEdit(myGroup)"><a href="javascript:void(0);">Edit</a></li>
                                            <li ng-if="optionEditDelete(myGroup)" ng-click="showPopupConfirm(myGroup, group)"><a href="javascript:void(0);">Delete</a></li>
                                            <li ng-if="optionLeaveGroup(myGroup)" role="separator"><span class="divider"></span></li>
                                            <li ng-if="optionLeaveGroup(myGroup)" ng-click="showPopupLeave(myGroup, group)"><a href="javascript:void(0);">Leave Group</a></li>
                                        </ul>
                                    </div>
                                    <div class="_tsrs">
                                        <span class="text-muted">{{myGroup.total}} members</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
        </div>
    </div>     

    <div class="md-overlay" ng-click="canelCreateGroup()"></div>

    <!-- show popup delete or leave group -->
    <nav id="cbp-spmenu-s2" class="contain-add-group cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right project-panel  popupConfirmDelete">
        <div class="rmv-pushright pull-right iconClose" ng-click="canelCreateGroup()">
            <i class="fa fa-times"></i>
        </div>
        <p class="titleGroup"><b>{{titleGroup}} this Group?</b></p>
        <p class="desPopup">Do you want to {{titleGroup | lowercase }} <b>{{nameGroup}}</b> group?</p>
        <div class="boxBtn-Group">                
            <a class="btn btn-default btn-cancel-group" href="javascript:void(0);" ng-click="canelCreateGroup()">
                Cancel
            </a>
            <a class="btn btn-primary" href="javascript:void(0);" ng-click="deleteOrLeaveGroupFunc(groupId, objGroup)">
                {{titleGroup}} Group
            </a>
        </div>
    </nav>  

    <!-- show popup create new group -->
    <nav id="cbp-spmenu-s2" class="contain-add-group cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right project-panel popupCreateGroup">
        <div class="rmv-pushright pull-right iconClose" ng-click="canelCreateGroup()">
            <i class="fa fa-times"></i>
        </div>
        <h3>{{titlePopup}}</h3>
        <input type="text" name="group_name" class="form-control" id="group_id" style="display:none">
        <form class="form-new-group">
            <div class="form-group form-choose-images">
                <div class="box-img-info">
                    <img id="chooseAvatar" alt="" src="../static/images/choose-image-blank.png">
                </div>
                <div class="form-input-file">
                    <a href="javascript:void(0);" class="fileinput-filename">
                        <span class="text-file">
                            Upload group image
                        </span>
                        <input type="file" onchange="checkImagePhotoPost(this);" id="chosenImagePhotoPost">
                        <!-- <i class="fa fa-refresh"></i> Change picture -->
                    </a>
                    <p class="note-upload">Recommend using the image resolution is 174x174 Pixels smallest.</p>
                    <input type="hidden" value="" id="imageGroup">
                </div>            
            </div>
            <div class="form-group">
                <label for="album-name">Group name</label>
                <!--<input type="text" class="form-control" id="album_name" name="album_name" value="">-->
                <input type="text" name="group_name" class="form-control" id="group_name">
            </div>
            <div class="form-group">
                <label for="album-desc">Description</label>
                <!--<textarea rows="1" type="text" class="form-control" id="desc" name="desc" style="resize:none;"></textarea>-->
                <textarea id="desc" type="text" class="form-control" name="desc" rows="3" style="resize:none;"></textarea>
            </div>
            <div class="form-group">
                <div class="row-new-group row-addMember">
                    <label>Invite Member</label>
                    <div class="boxAddMember" ng-click="focusAddMember()">   
                        <div class="totalMemberGroup" style="display:none">{{totalMember}}</div>                    
                        <div class="member-new-group">
                            <!-- member has been added -->
                            <input type="text" name="name" value="" id="name" class="inputAddMember" autocomplete="off" >
                        </div>
                    </div>
                   
                    <ul id="display" style="display:none;" class="tags-staff popup-new-group">       
                        <!-- view list member -->              
                    </ul>
                </div>
                <div class="boxFav-createGroup">
                    <input type="checkbox" name="checkFavor" value="4" > <span>Add this group to your favorite</span>
                </div>
            </div>
            <div class="form-group">
                <div class="row-new-group">
                    <label class="ver-top">Privacy</label>
                    <div class="public-privacy">
                        <div class="public-privacy-group">
                            <div class="radio">
                                <input type="radio" name="privacy[]" value="1" id="radioPublic">
                                <label for="radioPolicy"><span>Public</span></label>
                            </div>
                            <p>Anyone can find and join the group</p>
                        </div>

                        <div class="public-privacy-group">
                            <div class="radio">
                                <input type="radio" name="privacy[]" value="0" id="radioPrivacy" checked>
                                <label for="radioPrivacy"><span>Privacy</span></label>
                            </div>
                            <p>Anyone can find the group and need an approval to join</p>
                        </div>

                    </div>                
                </div>
            </div>   
            <div class="form-group form-btn text-right">                
                <a class="btn btn-default btn-cancel-group" href="javascript:void(0);" ng-click="canelCreateGroup()">
                    Cancel
                </a>
                <a class="btn btn-primary boxBtnCreateGroup" href="javascript:void(0);" ng-click="createGroupFunc();">
                    Create
                </a>
                <a class="btn btn-primary btnEditGroup" href="javascript:void(0);" ng-click="editGroupFunc();">
                    Update
                </a>
            </div>
        </form>
    </nav>      
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>

<script>
     //hide popup delete or leave group

    function checkImagePhotoPost(sender) {
        var validExts = new Array(".jpg", ".png", ".gif", ".bmp", ".jpeg", ".GIF", ".JPG", ".PNG");
        var fileExt = sender.value;
        var formatFile = $("#chosenImagePhotoPost").get(0).files[0];
        fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
        if (validExts.indexOf(fileExt) < 0) {
            //alert(locales_file_extens_invalid.replace("[0]", validExts.toString()));
            alert("This " + formatFile.name.replace("[0]", validExts.toString()) + " file dosen't image file");
            //return false;
        }
        $.ajax({
            url: baseurl + "/upload/upload-group",
            type: "POST",
            dataType: "json",
            contentType: false,
            processData: false,
            data: function () {
                var data = new FormData();
                data.append("chosenImage", formatFile);
                return data;
                /* Or simply return new FormData(jQuery("form")[0]);*/
            }(),
            error: function (_, textStatus, errorThrown) {
                alert("This " + formatFile.name.replace("[0]", validExts.toString()) + " file dosen't image file");
                //console.log(textStatus, errorThrown);
            },
            success: function (response, textStatus) {
                if (response.error == 0) {
                    //var imgTmp = '<img width="170" src="' + response['url'] + '">';
                    //$(".box-img-info").html('').append(imgTmp);
                    $("#chooseAvatar").attr("src", response['url'])
                    $("#imageGroup").val(response['filename']);
                } else {
                    alert("This " + formatFile.name.replace("[0]", validExts.toString()) + " file dosen't image file");
                }
            }
        });       
        return true;
    }
</script>