<div class="header-menu-team clearfix">
                            <div class="title-team">
                                  <i class="fa fa-group"></i>
                                  <span><?= $this->Obj['group_name'] ?></span>
                              </div>
                              <ul class="function-menu-team">
                                <li>
                                    <a  href="<?= BASE_URL;?>/user/feed/groupid/<?= $this->groupid;?>">
                                        <i class="fa fa-area-chart"></i>
                                          <span><?= $this->locales->group->activitystream;?></span>
                                      </a>
                                  </li>
                                  <li>
                                    <a href="<?= BASE_URL;?>/group/document/g/<?= $this->groupid;?>/p/0">
                                        <i class="fa fa-folder-open"></i>
                                          <span><?= $this->locales->group->document;?></span>
                                      </a>
                                  </li>
                                  <li>
                                    <a href="#">
                                        <i class="fa fa-calendar"></i>
                                          <span><?= $this->locales->group->calendar;?></span>
                                      </a>
                                  </li>
                                    <?php
//                                    if(
//                                        Core_Common::checkAdminOfObject($Group, $this->arrLogin['accountID']) ||
//                                        Core_Common::checkOwnerOfObject($Group, $this->arrLogin['accountID'])
//                                    ){
                                    ?>
                                  <li>
                                    <a class="active" href="<?= BASE_URL;?>/user/index/groupid/<?= $this->groupid;?>">
                                        <i class="fa fa-user"></i>
                                          <span><?= $this->locales->group->member;?></span>
                                      </a>
                                  </li>
                                  <li>
                                    <a href="<?= BASE_URL;?>/group/update/id/<?= $this->groupid;?>">
                                        <i class="fa fa-cog"></i>
                                          <span><?= $this->locales->group->setting;?></span>
                                      </a>
                                  </li>
<!--                                    --><?php //} ?>
                              </ul>
                          </div>

<div class="contain-request-list">
                          
                          <div class="menu-leave">
                              <ul>
                                  <li>
                                      <!-- <a  href="javascript:void(0);"> -->
                                      <a  href="<?= BASE_URL.'/user/index/groupid/'.$this->groupid; ?>">
                                          <?= $this->locales->group->member;?>
                                        </a>
                                    </li>
                                    <li>
                                      <a  class="active" href="<?= BASE_URL.'/group/org-chart/group_id/'.$this->groupid; ?>">
                                          <?= $this->locales->group->orgchart;?>
                                        </a>
                                    </li>                                  
                                </ul>
                            </div><!-- menu-leave -->

    <?php
    $Obj = $this->Obj;
    if(empty($Obj)){?>
        <div class="alert alert-danger">Group Not Found</div>
    <?php }else{?>
        <div class="orgChartWrapper">
            <ul>
                <?php
                if($Obj['manager_info'])
                {
                    ?>
                    <li data-item="<?= $Obj['manager_info']['account_id']; ?>">
                        <img src="<?= $Obj['manager_info']['image_tag']; ?>" class="img-responsive img-orgchart img-rounded pull-left"/>
                        <a href="javascript:void(0);" data-value="<?= $Obj['manager_info']['account_id']; ?>" class="orgCharName">
                            <?= $Obj['manager_info']['name']; ?> <i class="fa fa-plus-square fa-fw collapseNodePlus"></i>
                        </a>
                    </li>
                <?php
                }else if($Obj['admin_info']){
                    ?>
                    <li data-item="<?= $Obj['admin_info']['account_id']; ?>">
                        <img src="<?= $Obj['admin_info']['image_tag']; ?>" class="img-responsive img-orgchart img-rounded pull-left"/>
                        <a href="javascript:void(0);" data-value="<?= $Obj['admin_info']['account_id']; ?>" class="orgCharName">
                            <?= $Obj['admin_info']['name']; ?> <i class="fa fa-plus-square fa-fw collapseNodePlus"></i>
                        </a>
                    </li>
                <?php
                }
                ?>

                <div data-item="org-chart-tmp" style="display:none;">
                    <ul class="subOrgchart">
                        <li data-item="">
                            <img data-fill="avatar" src="" class="img-responsive img-orgchart img-rounded pull-left"/>
                            <a data-fill="name" href="javascript:void(0);" data-value="" class="orgCharName">
                                <i class="fa fa-plus-square fa-fw collapseNodePlus"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <script>
                    $(document).ready(function(){
                        var busy = false;
                        $("body").on('click', '.orgCharName', function(){
                            var _this = $(this);
                            var _val = _this.data('value');

                            if(_val == 0 || $.trim(_val) =='')
                                return false;


                            var _i = $(this).find('i');
                            if(_i.hasClass('fa-minus-square')){
                                _i.toggleClass('fa-minus-square');
                                _this.parents('li').find('.subOrgchart').remove();
                                return false;
                            }
                            if(busy)
                                return false;

                            busy = true;
                            var url = '';
                            <?php if(isset($Obj['group_id'])){?>
                            var url = baseurl + '/api/org-chart?method=groupSubMember&groupId=<?= $Obj['group_id']; ?>';
                            <?php }?>
                            $.post(url, function (data) {
                                busy = false;

                                _i.toggleClass('fa-minus-square');
                                var dataTmp = $('[data-item="org-chart-tmp"]');
                                var _html = '';
                                $.each(data, function (index, member) {
                                    var liEle = dataTmp.find('li');

                                    liEle.find('[data-fill="avatar"]').attr('src', member.image_tag);
                                    if (member.hasChild)
                                        liEle.find('[data-fill="name"]').prepend(member.name);
                                    else
                                        liEle.find('[data-fill="name"]').html(member.name);
                                    _html += '<li data-item="' + member.account_id + '">' + liEle.html() + '</li>';
                                });
                                $('li[data-item="' + _val + '"]').append('<ul class="subOrgchart">' + _html + '</ul>');
//                                console.log($('li[data-item="' + _val + '"]').html(),_val);
                            }, 'json');

                        });
                    });
                </script>
            </ul>
        </div>
    <?php } ?>



</div>
