

<?php if($this->iTotalPage > 0){?>               
	<section class="text-right">
	      <nav role="navigation">
	        <ul class="cd-pagination text-right">
	        
	         <li <?php if ($this->iPage > 1){ echo 'onclick="clickNumber('.($this->iPage -1).');"';}?> class="button"><a <?php if($this->iPage == 1){echo 'class="disabled"';} ?>href="javascript:void(0);">Prev</a></li>
	        <?php for($i = 1; $i <= $this->iTotalPage; $i++){
		         if($this->iPage == $i){?>
                     <li><a class="current" href="javascript:void(0);"><?php echo $i;?></a></li>
           <?php }else{?>
                     <li onclick="clickNumber('<?php echo $i; ?>');" ><a href="javascript:void(0);"><?php echo $i;?></a></li>      
            <?php }?>

	       <?php }?>
	          <li <?php if ($this->iPage < $this->iTotalPage){ echo 'onclick="clickNumber('.($this->iPage +1).');"';}?> class="button"><a <?php if($this->iPage > $this->iTotalPage -1){echo 'class="disabled"';}?> href="javascript:void(0);">Next</a></li>
	        </ul>
	      </nav> <!-- cd-pagination-wrapper -->
	</section>
<?php }?>     

