<div class="md-overlay"></div>
<nav id="cbp-spmenu-s2" class="contain-add-group cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right project-panel">
    <div class="rmv-pushright pull-right">
        <i class="fa fa-times"></i>
    </div>
    <h3>Create New Group</h3>
    <form class="form-new-group">
        <div class="form-group form-choose-images">
            <div class="box-img-info">
                <img alt="" src="../static/images/choose-image-blank.png">
            </div>
            <div class="form-input-file">
                <a href="javascript:void(0);" class="fileinput-filename">
                    <span class="text-file">
                        Upload group image
                    </span>
                    <input type="file" onchange="checkImagePhotoPost(this);" id="chosenImagePhotoPost">
                    <!-- <i class="fa fa-refresh"></i> Change picture -->
                </a>
                <p class="note-upload">Recommend using the image resolution is 174x174 Pixels smallest.</p>
                <input type="hidden" value="" id="imageGroup">
            </div>            
        </div>
        <div class="form-group">
            <label for="album-name">Group name</label>
            <!--<input type="text" class="form-control" id="album_name" name="album_name" value="">-->
            <input type="text" name="group_name" class="form-control" id="group_name">
        </div>
        <div class="form-group">
            <label for="album-desc">Description</label>
            <!--<textarea rows="1" type="text" class="form-control" id="desc" name="desc" style="resize:none;"></textarea>-->
            <textarea id="desc" type="text" class="form-control" name="desc" rows="3" style="resize:none;"></textarea>
        </div>
        <div class="form-group">
            <div class="row-new-group">
                <label>Add Member</label>
                <input type="text" name="name" value="" id="name" class="form-control">
                <ul id="display" style="display:none;" class="tags-staff popup-new-group">
                    <li>
                        <a href="#">
                            <div class="inform-tags-members txt-left clearfix">
                                <div class="img-tags-members mg10 fl">
                                    <img alt="" src="images/avt-1.jpg">
                                </div>
                                <div class="name-tags-members clearfix">
                                    <strong>Ronaldo</strong>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="inform-tags-members txt-left clearfix">
                                <div class="img-tags-members mg10 fl">
                                    <img alt="" src="images/avt-1.jpg">
                                </div>
                                <div class="name-tags-members clearfix">
                                    <strong>Ronaldo</strong>
                                </div>
                            </div>
                        </a>
                    </li>
                </ul>
                <div class="member-new-group">

                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row-new-group">
                <label class="ver-top">Privacy</label>
                <div class="public-privacy">
                    <div class="public-privacy-group">
                        <div class="radio">
                            <input type="radio" name="privacy[]" value="1" id="radioPolicy">
                            <label for="radioPolicy"><span>Public</span></label>
                        </div>
                        <p>Anyone can find and join the group</p>
                    </div>

                    <div class="public-privacy-group">
                        <div class="radio">
                            <input type="radio" name="privacy[]" value="0" id="radioPrivacy" checked>
                            <label for="radioPrivacy"><span>Privacy</span></label>
                        </div>
                        <p>Anyone can find the group and need an approval to join</p>
                    </div>

                </div>                
            </div>
        </div>   
        <div class="form-group form-btn text-right">                
            <a class="btn btn-default btn-cancel-group" href="javascript:void(0);"
                onclick="hidePopupNewGroup();">
                Cancel
            </a>
            <a class="btn btn-primary" href="javascript:void(0);" onclick="createNewGroup();">
                Create
            </a>
        </div>
    </form>
</nav>

<script>
    //hide popup create album
    $(".md-overlay").click(function () {
        $(this).removeClass("md-show");
        $("#cbp-spmenu-s2").removeClass("cbp-spmenu-open");
    });

    $(".rmv-pushright").click(function () {
        $(".md-overlay").removeClass("md-show");
        $("#cbp-spmenu-s2").removeClass("cbp-spmenu-open");
    });

    $(".btn-cancel-group").click(function () {
        $(".md-overlay").removeClass("md-show");
        $("#cbp-spmenu-s2").removeClass("cbp-spmenu-open");

        while (lgAccountIds.length > 0) {
            lgAccountIds.pop();
        }
    });

</script>

<script type="text/javascript">

    var lgAccountIds = [];//list account id

    function hidePopupNewGroup() {
        $(".popup-add-new-group").fadeOut(300);
        //clear data
        while (lgAccountIds.length > 0) {
            lgAccountIds.pop();
        }
    }

    $(document).ready(function () {

        $('body').on("click", ".overlay-popup-new-group", function () {
            hidePopupNewGroup();
        });

        $('body').on("keyup", "#name", function () {

            var name = $(this).val();

            $("#display").fadeOut(100);


            if (name != null && name.length > 0) {

                $.post(baseurl + "/search/index2", {
                    'name': name
                }, function (data) {


                    var valueShowUsers = $('<ul></ul>');

                    for (var i = 0; i < data.users.length; i++) {

                        valueShowUsers.append(suggesstionLI('', data.users[i]['picture'], data.users[i]['name'], data.users[i]['account_id']));
                    }

                    if (data.users.length > 0) {
                        //msgbox.hide();
                        $("#display").html(valueShowUsers.html());
                        $("#display").fadeIn(100);
                    }

                }, 'json');

            }

        });

        $('body').on("click", ".addname", function () {

            var account_id = $(this).attr('data-aId');
            var name = $(this).attr('data-name');

            if (!checkExistsArray(lgAccountIds, account_id)) {

                lgAccountIds.push(account_id);

                var item = '<span data-aId="' + account_id + '" contenteditable="false" class="uiToken">' +
                    '<a href="javascript:void(0);" style="margin:0px 5px;">' + name + '</a>' +
                    '<a contenteditable="true" href="javascript:void(0);" class="close-btn close-btn-hover"><i class="fa fa-times"></i></a>' +
                    '</span>';

                $(".member-new-group").append(item);
                $("#display").fadeOut(100);
                $("#name").val('');
                $("#name").focus();
            } else {
                alert('Member already exists.');
            }


        });

        $('body').on("click", ".close-btn", function () {

            $(this).parent().remove();

            var account_id = $(this).parent().attr('data-aId');
            lgAccountIds = removeArray(lgAccountIds, account_id);
        });

        $('body').on("click", ".box-popup-add-new-group", function () {
            $("#display").fadeOut(100);
        });

    });


    function suggesstionLI(link, avatar, name, account_id) {

        return '<li class="addname" data-aId="' + account_id + '" data-name="' + name + '">' +
            '<a href="javascript:void(0);">' +
            '<div class="inform-tags-members clearfix">' +
            '<div class="img-tags-members mg10 fl">' +
            '<img alt="" width="36" src="' + avatar + '">' +
            '</div>' +
            '<div class="name-tags-members clearfix">' +
            '<strong>' + name + '</strong>' +
            '</div>' +
            '</div>' +
            '</a>' +
            '</li>';
    }

    //create new group
    function createNewGroup() {

        var group = {};
        group['name'] = $("#group_name").val();
        group['desc'] = $("#desc").val();
        group['is_public'] = $('input[name="privacy[]"]:checked').val();
        group['account_ids'] = lgAccountIds;
        group['image_url'] = $("#imageGroup").val();

        $.post(baseurl + "/group/create", {
            data: JSON.stringify(group)
        }, function (response) {

            if (response.error) {
                AlertFail(response.message);
            }
            else {
                AlertSuccess(response.message);
                window.location.href = baseurl + '/group/my';
            }

        }, 'json');

    }

    function removeArray(arr, number) {
        for (var i = arr.length - 1; i >= 0; i--) {
            if (arr[i] === number) {
                arr.splice(i, 1);
            }
        }
        return arr;
    }

    function checkExistsArray(arr, value) {
        for (var i = arr.length - 1; i >= 0; i--) {
            if (arr[i] === value) {
                return true;
            }
        }
        return false;
    }

    function checkImagePhotoPost(sender) {

        var validExts = new Array(".jpg", ".png", ".gif", ".bmp", ".jpeg", ".GIF", ".JPG", ".PNG");
        var fileExt = sender.value;
        fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
        if (validExts.indexOf(fileExt) < 0) {
            alert(locales_file_extens_invalid.replace("[0]", validExts.toString()));
            return false;
        }

        $.ajax({
            url: baseurl + "/upload/upload-group",
            type: "POST",
            dataType: "json",
            contentType: false,
            processData: false,
            data: function () {
                var data = new FormData();
                data.append("chosenImage", jQuery("#chosenImagePhotoPost").get(0).files[0]);
                return data;
                /* Or simply return new FormData(jQuery("form")[0]);*/
            }(),
            error: function (_, textStatus, errorThrown) {
                alert(locales_upload_error);
                //console.log(textStatus, errorThrown);
            },
            success: function (response, textStatus) {
                if (response.error == 0) {
                    var imgTmp = '<img width="170" src="' + response['url'] + '">';
                    $(".box-img-info").html('').append(imgTmp);
                    $("#imageGroup").val(response['filename']);

                } else {
                    alert(locales_upload_error);
                }
            }
        });

        return true;

    }
</script>