<?php
$group = $this->group;
$arrLogin = $this->arrLogin;
?>
<div class="grid_12">
    <?php echo $this->render('partial_tab.phtml'); ?>
    <div class="contain-request-list">
        <?php if (!$group['is_admin'] && !$group['is_manager']) {
            echo '<div class="alert alert-danger">Access is denied</div>';
        } else { ?>
            <div class="menu-leave">
                <ul>
                    <li>
                        <a href="<?php echo BASE_URL; ?>/group/update/id/<?php echo $this->group['group_id']; ?>">
                            <?php echo $this->locales->group->setting; ?>
                        </a>
                    </li>
                    <li>
                        <a class="active" href="javascript:void(0);">
                            <?php echo $this->locales->group->member; ?>
                        </a>
                    </li>
                    <!-- <li>
                                    	<a href="<?php echo BASE_URL; ?>/group/settingmember/id/<?php echo $this->groupid; ?>">
                                        	<?php echo $this->locales->group->member; ?>
                                        </a>
                                    </li>-->
                </ul>
            </div><!-- menu-leave -->
            <div class="tag-username-setting">
                <input type="text" placeholder="Tag username to invite" name="name" id="name">
                <input type="button" value="Invite" onclick="inviteMember(this);">
                <ul id="display" style="display:none;" class="tags-staff left-10">
                    <li>
                        <a href="#">
                            <div class="inform-tags-members txt-left clearfix">
                                <div class="img-tags-members mg10 fl">
                                    <img alt="" src="images/avt-1.jpg">
                                </div>
                                <div class="name-tags-members clearfix">
                                    <strong>Ronaldo</strong>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="inform-tags-members txt-left clearfix">
                                <div class="img-tags-members mg10 fl">
                                    <img alt="" src="images/avt-1.jpg">
                                </div>
                                <div class="name-tags-members clearfix">
                                    <strong>Ronaldo</strong>
                                </div>
                            </div>
                        </a>
                    </li>
                </ul>
                <div class="member-new-group">

                </div>
            </div><!-- box-search-member -->
            <div class="request-content">
                <div class="action-approve-list mg-top10 clearfix">
                    <div class="check-all checkbox-primary fl">
                        <input type="checkbox" id="selectAll">
                        <label for="selectAll"></label>
                    </div>
                    <ul class="action-list action-tooltip fl">
                        <li>
                            <a title="Cancel" href="javascript:void(0);" onclick="deleteRequestList();">
                                <i class="fa fa-remove"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- action-approve-list -->
                <div class="table-content-request">
                    <table class="table">
                        <thead>
                        <tr>
                            <th bgcolor="#eaeaea" class="txt-center uppercase" colspan="6">Pending</th>
                        </tr>
                        </thead>
                        <thead>
                        <tr>
                            <th width="20px"></th>
                            <th>RequestID</th>
                            <th>Name</th>
                            <th>EmployeeID</th>
                            <th>Team</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if (!empty($this->groupInvites)) {
                            foreach ($this->groupInvites as $groupInvite) {

                                ?>
                                <tr data-item="group-request-<?php echo $groupInvite['request_id'];?>">
                                    <td>
                                        <div class="check-all checkbox-primary">
                                            <input class="checkbox1"
                                                   id="checkbox_<?php echo $groupInvite['request_id'];?>"
                                                   type="checkbox" name="check[]"
                                                   value="<?php echo $groupInvite['request_id'];?>">
                                            <label for="checkbox_<?php echo $groupInvite['request_id'];?>"></label>
                                        </div>
                                    </td>
                                    <td><?php echo $groupInvite['request_id'];?></td>
                                    <td><?php echo $groupInvite['accountToInfo']['name'];?></td>
                                    <td><?php echo $groupInvite['accountToInfo']['position_name'];?></td>
                                    <td><?php echo $groupInvite['groupInfo']['group_name'];?></td>
                                    <td>
                                        <ul class="action-table-approve action-tooltip clearfix">
                                            <li>
                                                <a class="rejectAction" title="Cancel" href="javascript:void(0);"
                                                   onclick="deleteRequest('<?php echo $groupInvite['request_id'];?>')">
                                                    <i class="fa fa-remove"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            <?php }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
                <!-- table-content-request -->
                <div class="people-page clearfix">
                    <?php echo $this->groupInvites; ?>
                </div>
                <input type="hidden" name="page" id="page" value="<?php echo $this->page; ?>"/>
            </div><!-- request content -->
        <?php } ?>
    </div>
    <input type="hidden" value="<?php echo $this->groupid; ?>" id="groupid">

</div>

<script language="javascript">
var settings = { 
		nop     : '<?php echo ADMIN_PAGE_SIZE;?>',
		offset  : 0,
		error   : '<p><?php echo $this->locales->no_more_posts;?></p>',
		delay   : 500, 
		scroll  : true 
	};

var offset = settings.offset;
var busy = false;
var initmessage = '<p><?php echo $this->locales->load_more;?></p>';

var lgAccountIds = [];//list account id
var allVals = [];

var groupid = '<?php echo $this->groupid;?>';
	
$(document).ready(function() {
	//search tag freinds
  	 $('body').on("keyup", "#name", function(){
	   	 
  		var name = $(this).val();

  		$("#display").fadeOut(100);
		
		//msgbox.html("Type the name of someone or something...");
		
		if(name != null && name.length>0){

			$.post(baseurl + "/search/index2",{
				  'name': name
				  }, function(data){       

						
					 // msgbox.html('');

						var valueShowUsers = $('<ul></ul>');
						
						for (var i = 0; i < data.users.length; i++){
							
							valueShowUsers.append(suggesstionLI('', data.users[i]['picture'], data.users[i]['name'], data.users[i]['account_id']));
						}

						if(data.users.length > 0){
							//msgbox.hide();
							$("#display").html(valueShowUsers.html());
							$("#display").fadeIn(100);
						}
	            },'json');
		}
  	});
   //add name
  	$('body').on("click", ".addname", function(){

  		var account_id = $(this).attr('data-aId');
		var name = $(this).attr('data-name');
  		if(!checkExistsArray(lgAccountIds,account_id)){
  			//check exist in groupmember
  			$.post(baseurl + "/group/checkgroupmemberexist",{
				'm_id':account_id,
				'g_id':groupid
				  }, function(data){   
				    if(data.error == 1){
						alert(data.message); 
				    }else{
				    	lgAccountIds.push(account_id);
						var item = '<span data-aId="' + account_id + '" contenteditable="false" class="uiToken">'+
							            '<a href="javascript:void(0);">' + name + '</a>'+
							            '<a contenteditable="true" href="javascript:void(0);" class="close-btn close-btn-hover"></a>'+
						        	'</span>';
						$(".member-new-group").append(item);
						$("#display").fadeOut(100);
						$("#name").val('');
						$("#name").focus();
				    }
		       		
		        },'json');
			
  		}else{
	   		alert('Member already exists.');
  		}
  		
		
	});

	//remove name
	$('body').on("click", ".close-btn", function(){

   	$(this).parent().remove();

   	//remove accountid
   	var account_id = $(this).parent().attr('data-aId');
   	lgAccountIds = removeArray(lgAccountIds, account_id);
	});

	//hide name list
	$("body").click
	(
	  function(e)
	  {
	    if(e.target.className !== "tags-staff")
	    {
	      $("#display").fadeOut(100);
	    }
	  }
	);

	//check box all
	$('body').on( "click", '#selectAll', function(e) {  //on click

    	
        if(this.checked) { // check select status
        	allVals = [];//reset list
        	
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = true;  //select all checkboxes with class "checkbox1" 
                allVals.push($(this).val());      
            });
        }else{
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = false; //deselect all checkboxes with class "checkbox1"     
                allVals = removeArray(allVals, $(this).val());                
            });        
        }
       
    });

	 $('body').on( "click", '.checkbox1', function(e) {
	        if(this.checked){
	        	allVals.push($(this).val());  
	        }else{
	        	allVals = removeArray(allVals, $(this).val());
	        }
	    });
	
});

function inviteMember(_this){
	if(lgAccountIds.length > 0){
        _this = $(_this);
        _this.prop('disabled',true);
	var group = {};
	group['groupid'] = $("#groupid").val();
	group['account_ids'] = lgAccountIds;
	
	$.post(baseurl + "/group/invitemember",{
		data:JSON.stringify(group)
		  }, function(response){
        _this.prop('disabled',false);
            if (response.error)
                AlertFail(response.message);
            else {
                AlertSuccess(response.message);
                window.location.href = baseurl + '/group/settingrequest/id/' + group['groupid'];
            }

//			alert(data.message);
//		    if(data.error == 0){
//
//				window.location.href = baseurl + '/group/settingrequest/id/' + group['groupid'];
//		    }
       		
        },'json');
	}else{
		alert('No User.');
	}
}

function suggesstionLI(link, avatar, name, account_id){
	
	return '<li class="addname" data-aId="' + account_id + '" data-name="' + name + '">'+
				'<a href="javascript:void(0);">'+
				'<div class="inform-tags-members clearfix">'+
			    	'<div class="img-tags-members mg10 fl">'+
			    		'<img alt="" width="36" src="' + avatar + '">'+
			        '</div>'+
			        '<div class="name-tags-members clearfix">'+
			        	'<strong>' + name + '</strong>'+
			        '</div>'+
			    '</div>'+
			'</a>'+
			'</li>';
}

function checkExistsArray(arr, value){
	for(var i = arr.length - 1; i >= 0; i--) {
	    if(arr[i] === value) {
	       return true;
	    }
	}
	return false;
}

function removeArray(arr, number){
	for(var i = arr.length - 1; i >= 0; i--) {
	    if(arr[i] === number) {
	       arr.splice(i, 1);
	    }
	}
	return arr;
}


//delete request
function deleteRequest(r) {
    if (r != '') {
        if (!confirm('Are you sure?'))
            return;
        var requestEle = $('[data-item="group-request-' + r + '"]');
        $.post(baseurl + "/group/deleterequest", {
            'request_id': r
        }, function (response) {
            if (response.error)
                AlertFail(response.message);
            else {

                requestEle.remove();
                AlertSuccess(response.message);
            }
            //remove list id
            allVals = removeArray(allVals, r);

        }, 'json');
    } else {
        alert("Request is not exits.");
    }

}

function deleteRequestList() {

    if (allVals.length > 0) {

        if (!confirm('Are you sure?'))
            return;

        var requestIds = {};
        requestIds['request_ids'] = allVals;

        $.post(baseurl + "/group/deleterequestlist", {
            data: JSON.stringify(requestIds)
        }, function (responses) {
            $.each(responses, function (index, response) {
                var requestEle = $('[data-item="group-request-' + allVals[index] + '"]');
                if (response.error)
                    AlertFail(response.message);
                else {
                    requestEle.remove();
                    AlertSuccess(response.message);
                }
            });
            $('#selectAll').prop('checked', false);
            $('input[name="check[]"]:checked').prop('checked', false);
            allVals = [];

        }, 'json');
    } else {
        alert("Please select Request");
    }
}


function showGroupNext(page)
{
    
	window.location = baseurl + '/group/settingrequest?id=' + groupid + '&page=' + page;
     
}

</script>
                    
