<div class="grid_12">
         <?php echo $this->render('partial_tab.phtml');?>
        <div class="contain-request-list">
                        	<div class="menu-leave">
                            	<ul>
                                	<li>
                                    	<a href="<?php echo BASE_URL;?>/group/settingrequest/id/<?php echo $this->groupid;?>">
                                        	<?php echo $this->locales->group->setting;?>
                                        </a>
                                    </li>
                                    <li>
                                    	<a class="active" href="javascript:void(0);">
                                        	<?php echo $this->locales->group->member;?>
                                        </a>
                                    </li>                                  
                                </ul>
                            </div><!-- menu-leave -->
                      
                            <div class="request-content">
                               <?php if($this->isadmin){?>
                        		<div class="action-approve-list mg-top10 clearfix">
                                	<div class="check-all fl">
                                    	<input type="checkbox" id="selectAll">
                                        
                                    </div>
                                    <ul class="action-list action-tooltip fl">                                    	
                                        <li>
                                        	<a title="Approve" href="javascript:void(0);">
                                            	<i class="fa fa-trash" onclick="deleteAccountList();"></i>
                                            </a>
                                        </li>                                       
                                    </ul>
                                </div><!-- action-approve-list -->
                                <?php }?>
                                <div class="table-content-request">
                            	<table class="table">
                                	<thead>
                                    	<tr><th bgcolor="#eaeaea" class="txt-center uppercase" colspan="6">member</th>
                                    </tr></thead>
                                	<thead>
                                        <tr>
                                        	<th width="20px"></th>
                                            <th>Name</th>
                                            <th>ID</th>
                                            <th>Team</th>
                                            <?php if($this->isadmin){?>
                                            <th>Action</th>    
                                            <?php }?>                                        
                                        </tr>
                                    </thead>
                                    <tbody> 
                                     <?php  if(!empty($this->paginator))
			                            {
			                                foreach ($this->paginator as $value)
			                                {?>                                   	
                                    	<tr>
                                        	<td><input class="checkbox1" type="checkbox" name="check[]" value="<?php echo $value['account_id'];?>"></td>
                                            <td><?php echo $value['name'];?></td>
                                            <td><?php echo $value['id'];?></td>
                                            <td><?php echo $value['group_name'];?></td> 
                                           <?php if($this->isadmin){?>
                                            <td>
                                            	<ul class="action-table-approve action-tooltip clearfix">                                                	
                                                    <li>
                                                        <a title="Approve" href="javascript:void(0);">
                                                            <i class="fa fa-trash" onclick="deleteAccount('<?php echo $value['account_id'];?>')"></i>
                                                        </a>
                                                    </li>                                                   
                                                </ul>
                                            </td>     
                                            <?php }?>                                       
                                        </tr>
                        <?php          }
				                    }
				                    ?>                                                 
                                    </tbody>
                                </table>
                            </div><!-- table-content-request -->
                             <div class="people-page clearfix">
                    			<?php echo $this->paginator;?>
                			</div>
                			<input type="hidden" name="page" id="page" value="<?php echo $this->page;?>" />      
                        	</div><!-- request content -->           
                        </div>
                        
      <input type="hidden" value="<?php echo $this->groupid;?>" id="groupid">
 
 </div>

<script language="javascript">

var groupid = '<?php echo $this->groupid;?>';				                    
var allVals = [];

$(document).ready(function() {
	
	//check box all
	$('body').on( "click", '#selectAll', function(e) {  //on click

    	
        if(this.checked) { // check select status
        	allVals = [];//reset list
        	
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = true;  //select all checkboxes with class "checkbox1" 
                allVals.push($(this).val());      
            });
        }else{
            $('.checkbox1').each(function() { //loop through each checkbox
                this.checked = false; //deselect all checkboxes with class "checkbox1"     
                allVals = removeArray(allVals, $(this).val());                
            });        
        }
       
    });

	 $('body').on( "click", '.checkbox1', function(e) {
	        if(this.checked){
	        	allVals.push($(this).val());  
	        }else{
	        	allVals = removeArray(allVals, $(this).val());
	        }
	    });
	
});

function deleteAccountList(){ 
	if(allVals.length > 0){

		if (confirm('Are you sure?')) {
			
			var requestIds = {};
			requestIds['group_id'] = groupid;
			requestIds['account_ids'] = allVals;
			
			$.post(baseurl + "/account/deletelist",{
				data:JSON.stringify(requestIds)
				  }, function(data){       
	
					if(data.total > 0){
						alert('Total:' + data.total + '\n' + 'Total Deleted:' + data.totalDelete);
						
					}else{
						alert('Request not exists');
						
					}
					window.location = baseurl + '/group/settingmember/id/' + groupid;           		
	           		
	            },'json');
		}
	}else{
		alert("Please select Request");
	}
}

//delete request
function deleteAccount(r){
	if(r != ''){
		if (confirm('Are you sure?')) {
			$.post(baseurl + "/account/delete",{
				  'id': r,
				  'g_id':groupid
				  }, function(data){       
					//remove list id
					allVals = removeArray(allVals, r);
					
				    alert(data.message);
				    window.location = baseurl + '/group/settingmember/id/' + groupid;
	           		
	            },'json');
		} else {
		  
		}
		
	}else{
		alert("Request is not exits.");
	}
}

function showGroupNext(page)
{
    
	window.location = baseurl + '/group/settingmember?id=' + groupid + '&page=' + page;
     
}

function checkExistsArray(arr, value){
	for(var i = arr.length - 1; i >= 0; i--) {
	    if(arr[i] === value) {
	       return true;
	    }
	}
	return false;
}

function removeArray(arr, number){
	for(var i = arr.length - 1; i >= 0; i--) {
	    if(arr[i] === number) {
	       arr.splice(i, 1);
	    }
	}
	return arr;
}

</script>
                    
