<?php
$group =  $this->arrGroup;
$bDisabled = false;
if (!empty($group))
{
    $bDisabled = (!$this->arrGroup['is_admin'] && !$this->arrGroup['is_manager']) ? true : false;
    $sDisabled = ($bDisabled) ? 'disabled' : '';
}
?>
    <?php echo $this->render('partial_tab.phtml'); ?>
    <script src="<?php echo $this->static->frontend->js . '/feed.js'; ?>"></script>
    <div class="contain-request-list">
        <div class="menu-leave clearfix">
            <ul>
                <li>
                    <a class="active" href="javascript:void(0);">
                        <?php echo $this->locales->group->setting; ?>
                    </a>
                </li>
                <?php if(!$bDisabled){?>
                <li>
                    <a href="<?php echo BASE_URL; ?>/group/settingrequest/id/<?php echo $this->groupid; ?>">
                        <?php echo $this->locales->group->member; ?>
                    </a>
                </li>
                <?php }?>
            </ul>
        </div>
        <!-- menu-leave -->
            <?php if($bDisabled){?>
                <small class="text-danger">This group is view only.</small>
            <?php } ?>

        <?php if (!empty($group)) {
            ?>
            <div class="row">
                <div class="col-md-7">
                    <div class="setting-general-information ">
                        <form data-item="f-update-group">
                            <fieldset>
                                <legend align="center">General Information</legend>
                                <div class="frame-img-general-info fl">
                                    <div class="box-img-info">
                                        <img alt="" src="<?php echo $this->arrGroup['image_tag']; ?>">
                                    </div>
                                    <?php if (!$bDisabled) { ?>
                                        <div class="btn-change-pic">
                                            <a href="javascript:void(0);">
                                                <input id="chosenImagePhotoPost" type="file"
                                                       onchange="checkImagePhotoPost(this);">
                                                <i class="fa fa-refresh"></i> Change picture
                                            </a>
                                        </div>
                                    <?php } ?>
                                </div>
                                <!-- frame-img-general-info -->
                                <div class="text-general-info">
                                    <div class="row-text mg-bt10">
                                        <label>Name</label>
                                        <input <?php echo $sDisabled ?> type="text"
                                                                        value="<?php echo $this->arrGroup['group_name']; ?>"
                                                                        name="group_name" id="name">
                                    </div>
                                    <div class="row-text mg-bt10">
                                        <label>Description</label>
                                        <textarea <?php echo $sDisabled ?>  rows="3" name="desc"
                                                                            id="desc"><?php echo $this->arrGroup['content']; ?></textarea>
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div><!-- setting-general-information -->
                </div>
                <div class="col-md-5">
                    <div class="privacy-setting mg-top20 clearfix">
                        <form class="form-new-group">
                            <fieldset>
                                <legend align="center">Privacy Information</legend>
                                <div class="row-new-group">
                                    <div class="public-privacy">
                                        <div class="text-left public-privacy-group">
                                            <div class="radio">
                                                <input <?php echo $sDisabled ?>  class="pull-left" type="radio" id="radioPolicy"
                                                                                 name="privacy[]"
                                                                                 value="1" <?php if ($this->arrGroup['is_public'] == 1) {
                                                    echo "checked";
                                                } ?>>
                                                <label for="radioPolicy"><span>Public</span></label>
                                            </div>
                                            <div class="infoPrivacy">
                                                <p>Anyone can see and join the group</p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="text-left public-privacy-group">
                                            <div class="radio">
                                                <input <?php echo $sDisabled ?>  class="pull-left" type="radio"
                                                                                 id="radioPrivacy" name="privacy[]"
                                                                                 value="0" <?php if ($this->arrGroup['is_public'] != 1) {
                                                    echo "checked";
                                                } ?>>
                                                <label for="radioPrivacy">
                                                    <span>Privacy</span></label>
                                            </div>
                                            <div class="infoPrivacy">
                                                <p>Anyone can find the group and need an acceptance to join</p>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- public-privacy -->
                                </div>
                            </fieldset>
                        </form>
                    </div><!-- privacy-setting-->
                </div>
            </div>
        <?php } ?>

        <?php if (!$bDisabled) { ?>
            <div class="btn-save-general">
                <input type="button" value="Update" id="udpate" onclick="updateGroup();">
            </div><!-- btn-save-general -->
        <?php } ?>
    <input type="hidden" value="<?php echo $this->groupid; ?>" id="groupid">
    <input type="hidden" value="" id="imageGroup">
</div>

<script language="javascript">
    function updateGroup() {

        var groupid = $('#groupid').val();
        var name = $('#name').val();
        var desc = $('#desc').val();
        var is_public = $('input[name="privacy[]"]:checked').val();
        var image_url = $("#imageGroup").val();

        $.post(baseurl + "/group/update", {
            'groupid': groupid,
            'name': name,
            'desc': desc,
            'is_public': is_public,
            'image_url': image_url
        }, function (data) {
            if (data.error)
                AlertFail(data.message);
            else if (!data.error)
                AlertSuccess(data.message);

        }, 'json');
    }


    function checkImagePhotoPost(sender) {

        var validExts = new Array(".jpg", ".png", ".gif", ".bmp", ".jpeg", ".GIF", ".JPG", ".PNG");
        var fileExt = sender.value;
        fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
        if (validExts.indexOf(fileExt) < 0) {
            alert(locales_file_extens_invalid.replace("[0]", validExts.toString()));
            return false;
        }

        $.ajax({
            url: baseurl + "/upload/upload-group",
            type: "POST",
            contentType: false,
            processData: false,
            dataType: 'JSON',
            data: function () {
                var data = new FormData();
                data.append("chosenImage", jQuery("#chosenImagePhotoPost").get(0).files[0]);
                return data;
                /* Or simply return new FormData(jQuery("form")[0]);*/
            }(),
            error: function (_, textStatus, errorThrown) {
                alert(locales_upload_error);
                //console.log(textStatus, errorThrown);
            },
            success: function (response, textStatus) {
                if (response != '') {
                    var imgTmp = '<img width="200" src="' + response.url + '">';
                    $(".box-img-info").html('').append(imgTmp);
                    $("#imageGroup").val(response.filename);

                } else {
                    alert(locales_upload_error);
                }
            }
        });
        return true;
    }
</script>
                    
