<div class="news-detail-technic clearfix">
  <div class="technic-title clearfix">Thông tin nhà tuyển dụng</div>
  <div class="clearfix" style="margin-top:15px;">                 
    <div class="col-md-12 col-sm-12 col-xs-12 item-value technic-title" style="padding:0px"></div>
  </div>
  <ul class="clearfix">       
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Loại hình công việc:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">Bán thời gian cố định</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Tuổi:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">- - -</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Giới tính:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Bằng cấp:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Ngoại ngữ:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Vị trí:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Kinh nghiệm:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">-</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item" style="display:none">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Mức lương:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">2.000.000 đ - -</div>
      </div>
    </li>
  </ul>
</div>              