<div class="news-detail-technic clearfix">
  <div class="technic-title clearfix">Thông tin bất động sản</div>
  <div class="clearfix" style="margin-top:15px;">                 
    <div class="col-md-12 col-sm-12 col-xs-12 item-value technic-title" style="padding:0px"></div>
  </div>
  <ul class="clearfix">       
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Loại bất động sản:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.propeCatName}}</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Dự án:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.propeProject}}</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Địa chỉ:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.propeAddress}}</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Diện tích đất:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.CT1}}</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Tầng/lầu:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.CT5}}</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Phòng ngủ:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.CT6}}</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Phòng tắm:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.CT7}}</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Diện tích sử dụng:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.CT2}}</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Hướng:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.CT3Name}}</div>
      </div>
    </li>
    <li class="col-md-6 col-sm-12 col-xs-12 technic-item">
      <div>
        <div class="col-md-5 col-sm-5 col-xs-5 item-name">Pháp lý:</div>
        <div class="col-md-7 col-sm-7 col-xs-7 item-value">{{newsDetail.CT4Name}}</div>
      </div>
    </li>
  </ul>
</div>