    <script src="<?= $this->static->frontend->js ;?>/loginService.js"></script>
    <script src="<?= $this->static->frontend->js ;?>/loginCtrl.js"></script>    
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <div ng-controller="loginCtrl" class="col-lg-4 col-md-4 col-sm-6 col-xs-12 col-left-login">
      <form name="loginFrm" class="form login-form" method="post" action="" >        
        <input id="sid" name="sid" type="hidden" value="<?= $this->token ?>" />        
        <input id="returnUrl" name="returnUrl" type="hidden" value="<?= $this->redirectPage ?>" />        
        <div class="col-md-12 content">
          <div class="button-social button-google">
              <span class="icon-google-plus fa fa-google-plus fa-2x"></span>
              <a href="<?= $this->urlGGLogin; ?>">Đăng nhập bằng Google</a>
          </div>
          <div class="button-space"></div>
          <div class="button-social button-facebook">
              <span class="icon-facebook fa fa-facebook-official fa-2x"></span>
              <a href="<?= $this->urlFBLogin; ?>">Đăng nhập bằng Facebook
              </a>
          </div>          
          <div class="button-space"></div>
          <div class="divider">
              <hr class="left" />Hoặc Đăng nhập bằng Email <hr class="right" />
          </div>          
          <div class="field-validation-error hide">
            {{message}}            
          </div>          
          <div class="form-group">
              <input ng-model="email" class="form-control" id="Email" maxlength="256" name="email" placeholder="Email *" type="email" value="<?= $this->email; ?>"  ng-required="required" />
              <span class="field-validation-valid"></span>
              <span class="field-validation-error" ng-show="loginFrm.email.$dirty && loginFrm.email.$invalid">Bạn vui lòng nhập tên đăng nhập</span>
          </div>
          <div class="form-group">
              <input ng-model="password" class="form-control" id="Password" maxlength="51" name="password" placeholder="Mật khẩu *" type="password" />
              <span class="field-validation-valid"></span>
              <span class="field-validation-error-pass hide" id="Error_password" >Bạn vui lòng nhập Mật khẩu</span>
          </div>                              
          <div class="g-recaptcha <?= $this->recaptchaDis; ?>" data-sitekey="<?= $this->ggSiteKey; ?>"></div>          
          <div class="form-group">
              <div class="btn-submit">
                  <div id="errorSummary">                
                  </div>
                  <input type="button" value="Đăng nhập" class="button" ng-click="Login()" ng-disabled="loginFrm.email.$dirty && loginFrm.email.$invalid || loginFrm.password.$dirty && loginFrm.password.$invalid" />&nbsp;&nbsp;<a href="javascript:void(0);" onclick="javascript:goForgot();">Quên mật khẩu</a>?
              </div>
          </div>          
        </div>
      </form>
      <div class="loadingPage" ng-if="loading"><img src="<?= $this->static->frontend->images ?>/loading.svg" alt=""></div>      
    </div>
    <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12 col-right-login">
      <h4>Thithien.com - Tạo tài khoản</h4>
      <p>Tạo tài khoản trên Thithien.com để tham gia cộng đồng mua bán hàng đầu.</p>
      <ul>
        <li class="fa fa-check-square-o fa-2x">
          <span>Đăng tin miễn phí</span>
        </li>
        <li class="fa fa-check-square-o fa-2x">
          <span>Hỗ trợ liên tục</span>
        </li>
        <li class="fa fa-check-square-o fa-2x">
          <span>Nổi bật tin đặc biệt</span>
        </li>
        <li class="fa fa-check-square-o fa-2x">
          <span>Mua của người chán, bán cho người cần</span>
        </li>
        <li class="fa fa-check-square-o fa-2x">
          <span>Quảng cáo liên tục và dài hạn</span>
        </li>
      </ul>
    </div>
    <div class="col-right-tbao hide" style="padding-left:100px;">
      <h4>Cảm ơn {{fullname}} đã đăng ký tài khoản</h4>

      <p>Bạn đã đăng ký tài khoản tại ThiThien Salom <br />
        Để sử dụng được bạn cần phải kích hoạt tài khoản theo cách sau:
      </p>
      <p>
        Chúng tôi đã gửi thông tin xác nhận đăng ký đến địa chỉ email <span class="highlight">{{email}}</span> của bạn.<br /> 
        Hãy làm theo hướng dẫn trong thư xác nhận. Thư xác nhận có thể không có trong phần inbox, bạn nên kiểm tra thêm phần Spam/Bulk
      </p>        
    </div>