<script src="<?= $this->static->frontend->js . '/feed/photo-contenteditable-comment.js'; ?>" type='text/javascript'></script>

    	<div class="bg-contain-photo clearfix">
        	<div class="photo-large">
            	<img draggable="false" src="" alt="">
              <div class="option-photo-popup">
                <i class="fa fa-download"></i>&nbsp;Download
              </div>
            </div>
            <div class="action-photo">
            	<a href="javascript:void(0);" class="pull-left ">
                  <img class="back_arrow" width=64px height=64px src="<?php echo $this->static->frontend->images.'/back_arrow.png'?>"/>
                </a>
                <span></span>
                <a href="javascript:void(0);" class="pull-right">
                  <img class="next_arrow" width=64px height=64px src="<?php echo $this->static->frontend->images.'/next_arrow.png'?>"/>
                </a>
            </div><!-- action-photo -->
        </div><!-- bg-contain-photo -->
        <div class="conmment-photo">
        	<div class="stt-host-photo">
            	<a href="javascript:void(0);" class="close-img">
                	<i class="icon-close"></i>
                </a>
            	<div class="info-host-photo clearfix">
                	<div class="img-host fl">
                    	<div class="contain-img-user">
                        	<img draggable="false" src="" alt="">
                        </div>
                    </div>
                    <div class="detail-host-photo">
                    	<label id="p-name">name</label>
                        <p class="grey" id="p-team">dasdasHuman resource</p>
                        <!-- <p class="grey" id="p-created"></i>09:22-07/11/2015</p> -->
                    </div>
                    <div class="descPhoto clearfix">
<!--                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore rerum doloribus, perspiciatis mollitia dolores maiores voluptatibus dolorum, iure tempora dolor numquam esse eos earum dolore assumenda voluptatem. Libero, illo, ea?-->
                    </div>
                </div><!-- info-host-photo -->
                <p class="host-cmt-photo"></p>
                <div class="clearfix" >
                    <ul class="action-host-photo">
                        <li id="like-action">
	                        <a onclick="addLikePhoto('0');" class="like detail" id="like-Click">
	                        	<i class="fa fa-heart-o fa-fw"></i>(<span id="add-Like">0</span> Likes)
	                        </a>
	                        <input type="hidden" id="is-Like" value="0"></li>
                        <li>
                            <a href="javascript:void(0);">
                                <i class="fa fa-comment-o fa-fw"></i>
                                (<span id="number-Comment">0</span> Comments)
                            </a>
                        </li>
                       <!-- <li>
                            <a href="#">
                                <i class="icon-share"></i>
                                <span>111</span>
                            </a>
                        </li>-->
                    </ul>
                </div>
            </div><!-- stt-photo -->
            <div class="cmt-photo">
            	<div class="comment box-content">
                    <p>
                        <a data-action="view-more-comment-photo-popup" href="#" class="view-more">
                            <span class="glyphicon glyphicon-share-alt" style="width:15px;"></span>View previous comments
                        </a>
                    </p>
                    <div class="comment-post addnew clearfix">
                        <a href="#" class="pull-right fl">
                            <img draggable="false" src="" alt="">
                        </a>
                        <div class="contain-cmt">
                            <p>
                                <span class="username"><a href="#">Sed ut perspiciatis</a></span>
                                <small class="text-muted detail">1 mins ago</small>
                                <small class="text-muted detail fr">09:22 - 07/11/2014 </small>
                            </p>
                            <div class="content">
                                <p>
                                    Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
                                </p>
                            </div>
                        </div>
                        <!-- end comment of user -->
                    </div>
                    <!-- end comment post -->
                    <div class="comment-post addnew clearfix" data-item="post-area">
                        <a href="#" class="pull-right fl">
                            <img draggable="false" src="" alt="">
                        </a>
                        <div class="cmt" >
                            <div data-item="photo-content-comment" class="comments-textarea" id="contentbox" contenteditable="true" >
                                asdasd<span class="uiToken" contenteditable="false">
                                    <a href="#">Ronaldo</a>
                                    <a href="#" contenteditable="true" class="close-btn close-btn-hover"></a>
                                </span>sadasd                
                            </div>
                            <ul class="tags-staff" style="display:none;">                                    	
                                <li>
                                    <a href="#">
                                        <div class="inform-tags-members clearfix">
                                            <div class="img-tags-members mg10 fl">
                                                <img draggable="false" src="" alt="">
                                            </div>
                                            <div class="name-tags-members clearfix">
                                                <strong>Ronaldo</strong>
                                            </div>
                                        </div>
                                    </a>
                                </li>	
                                <li>
                                    <a href="#">
                                        <div class="inform-tags-members clearfix">
                                            <div class="img-tags-members mg10 fl">
                                                <img draggable="false" src="" alt="">
                                            </div>
                                            <div class="name-tags-members clearfix">
                                                <strong>Ronaldo</strong>
                                            </div>
                                        </div>
                                    </a>
                                </li>	
                            </ul>
                        </div><!-- end comment of user -->
                    </div><!-- end comment post -->
                </div>
            </div>
            
        </div><!-- conmment-photo -->


<script type="text/javascript">

    var feedLanguage = {};
    feedLanguage.messagePostStatus = '<?= $this->locales->feedLang->saySomething ?>';
    var paramComment = {
        offset: 2,
        limit: 10,
        photo_id : 0,
        comment_id : 0
    };
    var say_some_thing = "<?= $this->locales->feedLang->saySomething ?>";
    var write_comment = "<?= $this->locales->feedLang->writeComment ?>";
    function deleteComment (comment_id, photo_id, _this) {
        _this = $(_this);
        if(confirm('Do you wan to delete ?'))
        {
//            $('[data-item="lst-comment-photo-popup"]').find('[data-comment="'+comment_id+'"]').remove();
            $.post(baseurl+'/photo2feed/delete-photo-comment/id/'+comment_id+'/photo_id/'+photo_id,function(response){
                if(response.result){
                    _this.parents('[data-item="comment"]').remove();
                    $('#number-Comment').html(response.totalComment);
//                    $('#numberComment_'+feed.feed_id).html(response.totalComment);
                }
                else{
                    alert(response.message);
                }
            },'json');
        }

    };

    function deletePhoto(_this){
        var _this = $(_this);
        if(!confirm('Do you want to delete ?'))
            return false;

        var photoId = [];
        photoId.push(_this.data('value'));
        $.post("<?= BASE_URL.'/api/token/index'; ?>", {'method': 'generateToken'}, function (token) {
            $.post(baseurl + '/api/photo?token='+token+'&method=deletePhotos&photoIds=[' + photoId.join(',') + ']', function (response) {

                if (response.error)
                    alert(response.message);
                else {
                    $('.contain-all-popup').hide();
                    $('.contain-all-popup').find('div[contenteditable="true"]').mentionsInput('destroy');
                    var itemPhoto = $('i[data-value="' + _this.data('value') + '"]').parents('[data-item="photo"]');
                    setTimeout(function () {
                        albumGrid.masonry('remove', itemPhoto).masonry();
                    }, 500)

                }
            }, 'json');
        });
    }

    function showCommentsPhoto(photo_id)
    {
        //console.log('comment', commentID);
        commentID = (typeof  commentID === 'undefined') ? 0 : commentID;
        paramComment.photo_id = photo_id;
        paramComment.comment_id = commentID;
        $.post(baseurl + "/comment/photofeed",paramComment, function(data){
            var totalComment = (typeof data.comments.length === 'undefined') ?  0 : data.comments.length;

            if(totalComment > 0){
                paramComment.offset = paramComment.offset + paramComment.limit;
                var lstCommentEle = $('[data-item="lst-comment-photo-popup"]');
                $.each(data.comments, function(index, value){
                    if(index == 0)
                        commentID = value.id;

                    setPhotoComment(value);
                    lstCommentEle.prepend(commentPostPhoto(value.photo_feed_id, value.picture, value.name, value.differencetime,
                        '', value.content, value.id, value.del, value.edit ));
                });
            }
            
            if(totalComment < paramComment.limit || totalComment == 0)
                $('[data-action="view-more-comment-photo-popup"]').remove();

        },'json');
    }
$(document).ready(function() {
    



    
    photo_id = 0;
//    $("body").delegate('div[contenteditable="true"]',"focus", function(e) {
//        if (this.hasChildNodes() && document.createRange() && window.getSelection()) {
//            var text = $.trim($(this).text());
//            if (text == say_some_thing || text == write_comment) {
//                placeholder = '<span style="color:#808080">'+text+'</span>';
//                $(this).empty();
//                setCursorToEnd($(this));
////$(".new-post").addClass('focusPost');
//            }
//        }
//    }).delegate('div[contenteditable="true"]',"focusout", function(e) {
//        if (!$(this).text().length) {
//            $(this).html(placeholder);
////$(".new-post").removeClass('focusPost');
//        }
//    });


//    function setCursorToEnd(ele)
//    {
//        var range = document.createRange();
//        var sel = window.getSelection();
//        if(range.startOffset > 0) {
//            range.setStart(ele, 0);
//            range.collapse(true);
//            sel.removeAllRanges();
//            sel.addRange(range);
//        }
//        ele.focus();
//    }

		//show/hide icon next prev
   //  $(".bg-contain-photo").hover(function(){
   //    $(".action-photo").show();
      
   //  });
	  // $(".conmment-photo").hover(function(){
   //    $(".action-photo").hide();
   //  });
	
	//remove tag
	$('body').on( "click", '.close-btn', function(e) {
		e.preventDefault();
		$(this).parent().remove();
	});

	//close popup
	$('body').on( "click", '.close-img', function(e){
		$('.contain-all-popup').fadeOut('fast');
        $(this).unbind('keyup'); // or $(this)
        $('html').css('overflow', ' auto');
	});
    
    $('body').on('click', function(event){
        if(!$(event.target).is('.popup-photo-detail, .popup-photo-detail *')){
            $('.contain-all-popup').fadeOut('fast');
            $(this).unbind('keyup'); // or $(this)
            var contenteditables = $('.contain-all-popup').find('div[contenteditable="true"]');
            $.each(contenteditables, function(i,e){
                if($(e).hasClass('ui-autocomplete-input')){
                    var id = $(e).attr('id');
                    $('#'+id).mentionsInput('destroy');
                }

            });
//            console.log($('.contain-all-popup').find('div[contenteditable="true"]'));
//            $('.contain-all-popup').find('div[contenteditable="true"]').mentionsInput('destroy');
            $('html').css('overflow', ' auto');
        }
    });

	//onclick next image
	$('body').on("click", '.next_arrow', function(e){
		if(busyClick == false){

            if(currentPhotoIds.length - 1 == indexPhotoId)
                indexPhotoId = 0;
            else
                indexPhotoId++;

//			if(currentPhotoIds.length - 1 > indexPhotoId){
				busyClick = true;
				var photoId = currentPhotoIds[indexPhotoId];
				//show popup
				showPopup(photoId, currentFeedId);
//			}

		}
	});

	$('body').on("click", '.back_arrow', function(e){
		if(busyClick == false){
            if(indexPhotoId == 0)
                indexPhotoId = currentPhotoIds.length - 1;
            else
                indexPhotoId--;

//			if(indexPhotoId > 0){
				busyClick = true;
				var photoId = currentPhotoIds[indexPhotoId];

				//show popup
				showPopup(photoId, currentFeedId);

//			}
		}
	});
//
//    var start=/@/ig;
//    var word=/@(\w+)/ig;
//    $('body').on("keyup", '[data-item="post-content"]', function(e) {
//
//        var keyCode = event.keyCode | event.which;
//        var _this = $(this);
//        var postAreaEle = _this.parents('[data-item="post-area"]');
//        var displayStaffEle = postAreaEle.find('[data-item="display-staff"]');
//        var displayMsgEle = postAreaEle.find('[data-item="display-msg"]');
//        var content = _this.html();
//        return searchUserName(content, start, word, displayStaffEle, displayMsgEle, keyCode);
//    });
//
//    $('body').on("keyup", ".comment3", function(e) {
//
//        var keyCode = event.keyCode | event.which;
//        var _this = $(this);
//        var postAreaEle = _this.parents('[data-item="post-area"]');
//        var displayStaffEle = postAreaEle.find('[data-item="display-staff"]');
//        var displayMsgEle = postAreaEle.find('[data-item="display-msg"]');
//        var content = _this.html();
//        return searchUserName(content, start, word, displayStaffEle, displayMsgEle, keyCode);
//    });
//
//    $('body').on("click", ".addname", function(){
//
//        var _this = $(this);
//        var postAreaEle = _this.parents('[data-item="post-area"]');
//        var postContentEle = postAreaEle.find('[data-item="post-content"]');
//        var tmp = _this.attr('title');
//        addUserNameToText(tmp, postContentEle);
//        postContentEle.focusEnd();
//    });
//	//post comment photo
//
//	$("div").delegate(".comment3","keypress", function(e) {
//    	var code = (e.keyCode ? e.keyCode : e.which);
//        var _this = $(this);
//        var postAreaEle = _this.parents('[data-item="post-area"]');
//        var displayStaffEle = postAreaEle.find('[data-item="display-staff"]');
//  	  if (code == 13 && e.shiftKey) {
////          document.execCommand('insertHTML', false, "<br/><br/>");
//  	  }else if(code == 13 && $.trim($(this).text()).length && displayStaffEle.find('li').length == 0){
//  		  e.preventDefault(); /*Stops enter from creating a new line*/
//
//  		if(busyCommentPhoto == false){
//  			busyCommentPhoto = true;
//
//  			  var id = $(this).attr("data-title");
//  			  var str = id.split("_");

//  			  if(str.length > 1){
//  	  			  var feed_id = $('.popup-photo-detail').attr('data-feedid');
//  				  var photo_id = str[0];
//  				  var account_id = str[1];
//  				  var comment = $(this).html();
//
//  				//get userId added tag
//  				var userIdStr = getUserIdStr(comment);
//  				//remove add tag button
//  				var commentTmp = comment.replace(/<a class="close-btn close-btn-hover" href="(.*?)"(.*?)><\/a>/g, '');
//				commentTmp = commentTmp.replace(/class="uiToken"/g,'');
//				commentTmp = commentTmp.replace(/class="close-btn close-btn-hover"/g,'');
//
//  				  $.post(baseurl + "/photo2feed/addcomment",{
//  	  				  'feed_id':feed_id,
//  					  'photo_id': photo_id,
//  					  'account_id': account_id,
//  					  'comment': commentTmp,
//  					  'account_list_to': userIdStr
//  					  }, function(data){
//  						if(data.error == 1){
//  							alert(data.message);
//  						}else{
//                            var comment = data.comment;
//                            var owner = comment.owner_info;
////                            commentPostPhoto(avatar, userName, timePost, dateTimePost, comment, commentId, del, edit )
//  							var valueComment = commentPostPhoto(photo_id, data.picture, data.name, '', data.create_date, commentTmp, comment.id, comment.del, comment.edit);
//
//  							$("#addCommentPhoto_" + photo_id).append(valueComment);
//  							$('div.cmt .comment3').html('');
//
//  							var numberComment = $("#number-Comment").html().trim();
//  							numberComment++;
//  							$("#number-Comment").text(numberComment);
//  						}
//  						busyCommentPhoto = false;
//  		            },'json');
//  			  }
//  		 }
//  	  }
//	 });
});
</script>
