<div class="asideCont clearfix" id="newproduct">
    <div class="bgTitlef9f9f9 titleReport">ADD SCREENSHOT PRODUCT
        <div class="floatright clear">
            <a href="javascript:void(0)" onClick="window.history.back();" class="button gray">[Back]</a>
        </div>
    </div>
    <table width="100%" cellspacing="0" cellpadding="0" border="1" class="tblComm">
        <tbody>
            <tr>
                <td valign="top" width="20%">
                    <div class="padLefRig20">
                        <ul class="ulListIfSch">
                            <?php
                               $sImageUrl = (!empty($this->arrProduct['screenshots1'])) ? PATH_NEWS_URL .'/'. $this->arrProduct['screenshots1'] : 'http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image';
                             ?>
                            <li>                        
                                <form name="uploadImage" url="<?php echo BASE_URL . "/upload/upload/type/1"; ?>">
                                    <div class="fileupload fileupload-new" data-provides="fileupload" input-id="1">
                                        <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="img" src="<?php echo $sImageUrl;?>" /></div>
                                        <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                        <div>
                                            <span class="btn btn-file"><span class="fileupload-new" id="btnUpload">Select image</span><span class="fileupload-exists">Change</span><input type="file" name="file_upload" accept="image/png, image/gif, image/jpeg" /></span>
                                            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                        </div>
                                    </div>
                                    <div id="photoUploadResult1" class="hidden imageResult"></div>
                                </form>
                                <input type="hidden" name="gImage1" value ="<?php echo $this->arrProduct['screenshots1'];?>" id ="gImage1" />
                                <p class="error" id="pImageError" ></p>
                            </li>
                        </ul>
                    </div>
                </td>
                <td valign="top" width="20%">
                    <div class="padLefRig20">
                        <ul class="ulListIfSch">
                            
                            <?php
                               $sImageUrl = (!empty($this->arrProduct['screenshots2'])) ? PATH_NEWS_URL .'/'. $this->arrProduct['screenshots2'] : 'http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image';
                             ?>
                             
                            <li>                        
                                <form name="uploadImage" url="<?php echo BASE_URL . "/upload/upload/type/1"; ?>">
                                    
                                    <div class="fileupload fileupload-new" data-provides="fileupload" input-id="2">
                                        <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="img" src="<?php echo $sImageUrl;?>" /></div>
                                        <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                        <div>
                                            <span class="btn btn-file"><span class="fileupload-new" id="btnUpload">Select image</span><span class="fileupload-exists">Change</span><input type="file" name="file_upload" accept="image/png, image/gif, image/jpeg" /></span>
                                            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                        </div>
                                    </div>
                                    <div id="photoUploadResult2" class="hidden imageResult"></div>
                                </form>
                                  <input type="hidden" name="gImage2" value ="<?php echo $this->arrProduct['screenshots2'];?>" id ="gImage2" />
                            </li>
                        </ul>
                    </div>
                </td>
                <td valign="top" width="20%">
                    <div class="padLefRig20">
                        <ul class="ulListIfSch">
                            
                            <?php
                               $sImageUrl = (!empty($this->arrProduct['screenshots3'])) ? PATH_NEWS_URL .'/'. $this->arrProduct['screenshots3'] : 'http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image';
                             ?>
                            
                            <li>                        
                                <form name="uploadImage" url="<?php echo BASE_URL . "/upload/upload/type/1"; ?>">
    
                                    <div class="fileupload fileupload-new" data-provides="fileupload" input-id="3">
                                        <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="img" src="<?php echo $sImageUrl;?>" /></div>
                                        <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                        <div>
                                            <span class="btn btn-file"><span class="fileupload-new" id="btnUpload">Select image</span><span class="fileupload-exists">Change</span><input type="file" name="file_upload" accept="image/png, image/gif, image/jpeg" /></span>
                                            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                        </div>
                                    </div>
                                    <div id="photoUploadResult3" class="hidden imageResult"></div>
                                </form>
                                  <input type="hidden" name="gImage3" value ="<?php echo $this->arrProduct['screenshots3'];?>" id ="gImage3" />
                            </li>
                        </ul>
                    </div>
                </td>
                <td valign="top" width="20%">
                    <div class="padLefRig20">
                        <ul class="ulListIfSch">
                            
                            <?php
                               $sImageUrl = (!empty($this->arrProduct['screenshots4'])) ? PATH_NEWS_URL .'/'. $this->arrProduct['screenshots4'] : 'http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image';
                             ?>
                            
                            <li>                        
                                <form name="uploadImage" url="<?php echo BASE_URL . "/upload/upload/type/1"; ?>">
                                   
                                    <div class="fileupload fileupload-new" data-provides="fileupload" input-id="4">
                                        <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="img" src="<?php echo $sImageUrl;?>" /></div>
                                        <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                        <div>
                                            <span class="btn btn-file"><span class="fileupload-new" id="btnUpload">Select image</span><span class="fileupload-exists">Change</span><input type="file" name="file_upload" accept="image/png, image/gif, image/jpeg" /></span>
                                            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                        </div>
                                    </div>
                                    <div id="photoUploadResult4" class="hidden imageResult"></div>
                                </form>
                                  <input type="hidden" name="gImage4" value ="<?php echo $this->arrProduct['screenshots4'];?>" id ="gImage4" />
                            </li>
                        </ul>
                    </div>
                </td>
                <td valign="top" width="20%">
                    <div class="padLefRig20">
                        <ul class="ulListIfSch">
                            
                            <?php
                               $sImageUrl = (!empty($this->arrProduct['screenshots5'])) ? PATH_NEWS_URL .'/'. $this->arrProduct['screenshots5'] : 'http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image';
                             ?>
                            
                            <li>                        
                                <form name="uploadImage" url="<?php echo BASE_URL . "/upload/upload/type/1"; ?>">
                                   
                                    <div class="fileupload fileupload-new" data-provides="fileupload" input-id="5">
                                        <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;"><img class="img" src="<?php echo $sImageUrl;?>" /></div>
                                        <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                        <div>
                                            <span class="btn btn-file"><span class="fileupload-new" id="btnUpload">Select image</span><span class="fileupload-exists">Change</span><input type="file" name="file_upload" accept="image/png, image/gif, image/jpeg" /></span>
                                            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                        </div>
                                    </div>
                                    <div id="photoUploadResult5" class="hidden imageResult"></div>
                                </form>
                                 <input type="hidden" name="gImage5" value ="<?php echo $this->arrProduct['screenshots5'];?>" id ="gImage5" />
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>

            <tr>
                <td valign="top" colspan="5">
                    <div class="floatleft mLeft10 mTop10">
                        <a href="#" id="btnAdd" class="button green">Add</a>
                        <span id="btnSubmitting" class="button gray hidden">Submitting...</span>
                       <input type="hidden" name="productid" value ="<?php echo $this->iProductID;?>" id ="productid" />
                    </div>                    
                </td>                    
            </tr>
        </tbody>
    </table>
</div>

<script type="text/javascript">

    document.domain = "<?php echo DOMAIN; ?>";
    
    $('.fileupload').fileupload({"name":"file_upload"});
    
    
    $('#btnAdd').click(function() {

            
        var image1 = $('#photoUploadResult1 .response .image_id').html();
        var image2 = $('#photoUploadResult2 .response .image_id').html();
        var image3 = $('#photoUploadResult3 .response .image_id').html();
        var image4 = $('#photoUploadResult4 .response .image_id').html();
        var image5 = $('#photoUploadResult5 .response .image_id').html();
        
        
      
        var oldimage1 = $('#gImage1').val();
        var oldimage2 = $('#gImage2').val();
        var oldimage3 = $('#gImage3').val();
        var oldimage4 = $('#gImage4').val();
        var oldimage5 = $('#gImage5').val();
        var id = $('#productid').val();
        
        
        if (image1 != undefined) {
            oldimage1 = $('#photoUploadResult1 .response .image_id').html() + "." + $('#photoUploadResult1 .response .image_format').html();
        } 
        
        
        if (image2 != undefined) {
            oldimage2 = $('#photoUploadResult2 .response .image_id').html() + "." + $('#photoUploadResult2 .response .image_format').html();
        } 
        
        
        if (image3 != undefined) {
            oldimage3 = $('#photoUploadResult3 .response .image_id').html() + "." + $('#photoUploadResult3 .response .image_format').html();
        } 
        
        
        if (image4 != undefined) {
            oldimage4 = $('#photoUploadResult4 .response .image_id').html() + "." + $('#photoUploadResult4 .response .image_format').html();
        } 
        
        if (image5 != undefined) {
            oldimage5 = $('#photoUploadResult5 .response .image_id').html() + "." + $('#photoUploadResult5 .response .image_format').html();
        } 
        
        
        var params ={
            image1:oldimage1,
            image2:oldimage2,
            image3:oldimage3,
            image4:oldimage4,
            image5:oldimage5, 
            id:id
        };
        
       

        $.post("<?php echo BASE_ADMIN_URL; ?>/product/updscreenshots", params, function(result){
            if(result.error == 0)
            {
                    window.location= '<?php echo BASE_ADMIN_URL; ?>/product/index/page/<?php echo $this->iPage;?>';
            }
            else
            {
                alert(result.message);
               
            }
        },'json');
    });
</script>