
<?php
 $sImageUrl = (!empty($this->arrProduct['image_url'])) ? PATH_NEWS_URL .'/'. $this->arrProduct['image_url'] : '';
   
?>
<div class="asideCont borPaddNon clearfix" id="newproduct">
    <table width="100%" cellspacing="0" cellpadding="0" border="1" class="tblComm">
        <tbody>
            <tr>
                <th align="left" colspan="2">UPDATE PRODUCT</th>
            </tr>
          
            <tr>
                <td valign="top">
                    <div class="padLefRig20">
                        
                        <ul class="ulListIfSch">
                              
                             <li>
                                <p class="titleDes"><label>Product Name</label></p>
                                <input type="text" id="gTitle" style="width:650px;" name="gTitle" placeholder="Enter productname" value="<?php echo $this->arrProduct['name'];?>">
                                <p class="error" id="gTitleError" ></p>
                            </li>
                            
                            <li>
                                <p class="titleDes"><label>Content</label></p>
                                <textarea style="width:258px; font-size: 13px;" id="gContent" name="gContent" placeholder="Content"><?php echo $this->arrProduct['content'];?></textarea>
                                <p class="error" id="gContentError" ></p>
                            </li>
                            <li>                        
                                <p class="titleDes"><label>Type</label></p>
                                <select id="gType" style="width:659px;" name="gType" class="seleComm">
                                    <?php foreach ($this->arrProductType as $key => $value): 
                                        
                                        $selected = '';
                                         if($this->arrProduct['type'] == $key)
                                         {
                                             $selected ='selected="selected"';
                                         }
                                        ?>
                                    <option value="<?php echo $key; ?>"  <?php echo $selected;?>><?php echo $value; ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <p class="error" id="gTypeError" ></p>
                            </li>
                            
                             <li>
                                <p class="titleDes"><label>Sort Order</label></p>
                                <input type="text" style="width:650px;" id="gSort" name="gSort" placeholder="Sort order" value="<?php echo $this->arrProduct['sort_order'];?>">
                                <p class="error" id="gSortError" ></p>
                            </li>

                           <li>                        
                                <p class="titleDes"><label>Image</label></p>
                                <form name="uploadImage" url="<?php echo BASE_URL . "/upload/upload/type/1"; ?>">
                                    <div class="fileupload fileupload-new" data-provides="fileupload">
                                        <div class="fileupload-new thumbnail" style="width: 150px;"><img class="img" src="<?php echo !empty($sImageUrl)?$sImageUrl:'http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image';?>" width="150px" /></div>
                                        <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                        <div>
                                            <span class="btn btn-file"><span class="fileupload-new" id="btnUpload">Select image</span><span class="fileupload-exists">Change</span><input type="file" name="file_upload" accept="image/png, image/gif, image/jpeg" /></span>
                                            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                                        </div>
                                    </div>
                                    <div id="photoUploadResult" class="hidden"></div>
                                </form>
                                <p class="error" id="pImageError" ></p>
                                <input type="hidden" name="gPicture" value ="<?php echo $this->arrProduct['image_url'];?>" id ="gPicture" />
                            </li>
                           <li>                        
                                <p class="titleDes"><label>Platform Type</label></p>
                                <div >
                                       <label>
                                            <select  name="platform"  id="platform">
                                     <?php
                                       if(!empty($this->arrPlatForm))
                                       {
                                              foreach($this->arrPlatForm as $key=>$value)
                                              {
                                           ?>
                                    
                                       
                                                 <option value="<?php echo $key;?>" > <?php echo $value; ?>&nbsp;&nbsp;&nbsp;&nbsp;
                                  
                                        <?php
                                              }
                                       }
                                       ?>
                                            </select>
                                       </label>
                                </div>
                                <p class="error" id="gDisplayError" ></p>
                            </li>
                            
                            <li>                        
                                <p class="titleDes"><label>Device Type</label></p>
                                <div >
                                     <?php
                                       if(!empty($this->arrDeviceType))
                                       {
                                             
                                              foreach($this->arrDeviceType as $key=>$value)
                                              {
                                                  $check ='';
                           
                                                  if(($this->arrProduct['device_type'] & $key)>0)
                                                  {
                                                       $check ="checked='checked'";
                                                  }
                                           ?>
                                    
                                        <label>
                                            <input type="checkbox" onClick="checkDevice(this, '<?php echo $key;?>');" class="device" <?php echo $check;?> name="device[]" value="<?php echo $key;?>" > <?php echo $value; ?>&nbsp;&nbsp;&nbsp;&nbsp;
                                        </label>
                                        <?php
                                              }
                                       }
                                       ?>
                                   
                                </div>
                                <p class="error" id="gDisplayError" ></p>
                            </li>
                    
 
                            
                            <li id="linkid8"  style="display:<?php echo (($this->arrProduct['device_type']&8)>0)?'block':'none';?>"> 
                                <p class="titleDes"><label>Web Link</label></p>
                                <input type="text" style="width:650px;" id="gLink" name="gLink" placeholder="Enter link" value="<?php echo $this->arrProduct['link'];?>">
                                <p class="error" id="gSourceError" ></p>
                            </li>
                             <li id="linkid1" style="display:<?php echo (($this->arrProduct['device_type']&1)>0)?'block':'none';?>">
                                <p class="titleDes"><label>IOS Link</label></p>
                                <input type="text" style="width:650px;" id="gIosLink" name="gIosLink" placeholder="Enter IOS Link" value="<?php echo $this->arrProduct['ios_link'];?>">
                                <p class="error" id="gSourceError" ></p>
                            </li>
                            <li id="linkid2" style="display:<?php echo (($this->arrProduct['device_type']&2)>0)?'block':'none';?>">
                                <p class="titleDes"><label>Android Link</label></p>
                                <input type="text" style="width:650px;" id="gAndroidLink" name="gAndroidLink" placeholder="Enter Android Link" value="<?php echo $this->arrProduct['android_link'];?>">
                                <p class="error" id="gSourceError" ></p>
                            </li>
                            <li id="linkid4" style="display:<?php echo (($this->arrProduct['device_type']&4)>0)?'block':'none';?>">
                                <p class="titleDes"><label>Window phone Link</label></p>
                                <input type="text" style="width:650px;" id="gWindowLink" name="gWindowLink" placeholder="Enter Window Link" value="<?php echo $this->arrProduct['window_link'];?>">
                                <p class="error" id="gSourceError" ></p>
                            </li>

                            
                            <?php
                             $check1='checked';
                             $check2='';
                             
                             if($this->arrProduct['active'] ==0)
                             {
                                  $check1='';
                                  $check2='checked';
                             }
                             
                             ?>
                            <li>                        
                                <p class="titleDes"><label>Active</label></p>
                                <div class="product-display">
                                    <label class="radio">
                                        <input type="radio" name="gDisplay" value="1" <?php echo $check1;?>>Yes
                                    </label>
                                    <label class="radio">
                                        <input type="radio" name="gDisplay" value="0" <?php echo $check2;?>>No
                                    </label>
                                </div>
                                <p class="error" id="gDisplayError" ></p>
                            </li>
                            
                        </ul>
                    </div>
                </td>
            </tr>                  
            <tr>
                <td valign="top" colspan="2">
                    <div class="floatleft mLeft10 mTop10">
                        <a href="javascript:void(0)"  id="btnAdd1" class="button green">Update</a>
                         <input  type="hidden" name="product_id" id="product_id" value="<?php echo $this->arrProduct['product_id'];?>" />
                    </div>                    
                </td>                    
            </tr>
        </tbody>
    </table>
</div>
<div style="height: 30px"></div>

<div id="toTop">^ Back to Top</div> 
<script type="text/javascript" src="<?php echo $this->static->backend->js;?>/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
    function checkDevice(self, value)
    {
        if(self.checked){
            $('#linkid' + value).css('display', 'block');
        }
        else{
            $('#linkid' + value).css('display', 'none');
        }
    }
    
    tinymce.init({
        selector: "textarea",
        elements : "gContent",
        width: "659px",
        height: "300px",
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste moxiemanager"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
    });
    
    document.domain = "<?php echo DOMAIN; ?>";
    $('.fileupload').fileupload({"name":"itemImage"});
    
    
    $(function() {
	$(window).scroll(function() {
            if($(this).scrollTop() != 0) {
                    $('#toTop').fadeIn();	
            } else {
                    $('#toTop').fadeOut();
            }
	});
 
	$('#toTop').click(function() {
		$('body,html').animate({scrollTop:0},800);
	});	
    });
    
    
    $('#btnAdd1').click(function() {

        var title  = $('#gTitle').val(); 
        var content  = tinyMCE.get('gContent').getContent(); /*$('#gContent').val();*/ 
        var link  = $('#gLink').val(); 
        var ioslink  = $('#gIosLink').val(); 
        var androidlink  = $('#gAndroidLink').val(); 
        var windowlink  = $('#gWindowLink').val(); 
        var platform    = $('#platform').val();
        var device=0;
        
        
         /* Check device */
        $(".device:checkbox").each(function() 
        {
             if (this.checked && $.isNumeric(this.value)) {
                 if(device  ==0)
                 {
                     device = this.value;
                 }
                 else
                 {
                       device = parseInt(device) + parseInt(this.value);
                 }

             }
         });
        
       
        
        var sort  = $('#gSort').val(); 
        var type  = $('#gType').val(); 
        var active = $("input:radio[name='gDisplay']:checked").val();
        var image = $('#photoUploadResult .response .image_id').html();
        var id  = $('#product_id').val(); 
        var picture = $('#gPicture').val();
        
        
        if (title =='') {
            alert('Please input Product name!');
            return;
        }

   
        
        if (image == undefined) {
            image = picture;
        } else {
            image = $('#photoUploadResult .response .image_id').html() + "." + $('#photoUploadResult .response .image_format').html();
        }
        
        
        
        if (image =='') {
            alert('Please input Product image!');
            return;
        }

        

        var params = {
            title:title,
            content:content,
            link:link,
            image:image,
            active:active,
            sort: sort,
            type: type,
            ioslink:ioslink,
            androidlink:androidlink,
            windowlink:windowlink,
            platform:platform,
            device:device,
            id:id
        };

        $.post("<?php echo BASE_ADMIN_URL; ?>/product/add", params, function(result){
            if(result.error == 0)
            {
                window.location= '<?php echo BASE_ADMIN_URL; ?>/product/index/page/<?php echo $this->iPage;?>';
            }
            else
            {
                alert(result.message);
            }
        },'json');
        
    });
  
</script>
