 <script type="text/javascript" src="<?php echo $this->static->frontend->js . '/jquery.min.js' ?>"></script>
 
 <link rel="stylesheet" type="text/css" href="<?php echo $this->static->frontend->css . '/date_input.css';?>">
 <script type="text/javascript" src="<?php echo $this->static->frontend->js . '/jquery.date_input.js' ?>"></script>
 
 <div class="row">
        <input type="hidden" class="date_input" name="date"> 
        <span id="scheduleid">
            
        </span>
 </div>
 
<script type="text/javascript">$($.date_input.initialize);</script>
<script language="javascript">
function getCalendarData(month, year)
{
      $.get("<?php echo BASE_URL;?>/index/calendar",{month:month,year:year},function(result){

         $.each(result.data.list, function( i, item ) {
             
            $('#' + item.date).addClass('state-event');
            $('#' + item.date).addClass('active');
         })
         
   },'json');
}

function getCalendarDetail(day,month, year)
{
      $.get("<?php echo BASE_URL;?>/index/calendardetail",{day:day,month:month,year:year},function(result){

        $('#scheduleid').html(result);
         
   });
}

getCalendarData(0,0);
getCalendarDetail(<?php echo date('d', time());?>,<?php echo date('m', time());?>,<?php echo date('Y', time());?>);
</script>