
<div id="task-reminder">                      
<div class="task-day">
   <div class="task-day-title">
           <h4><?php echo $this->sTextDay;?></h4>
   </div>
          <div class="task-day-content">

<?php
  if(!empty($this->arrCalendar))
  {
        foreach ($this->arrCalendar as $value)
        {
   ?>
            <p>
               <span><?php echo $value['subject'];?></span>
               <span class="fr"><?php echo $value['startDate'];?>-<?php echo $value['endDate'];?></span>
            </p>  
  <?php
        }
  }
  else
  {
  ?>
     <p>
               <span>No event!!!</span>
               <span class="fr"></span>
     </p>           
  <?php
  }
  ?>
 </div>
</div>
</div>

