<?php
  if(!empty($this->arrCalendar))
  {
        foreach ($this->arrCalendar as $key=>$value)
        {
   ?>
        <div id="task-reminder">                      
        <div class="task-day">
           <div class="task-day-title">
                   <h4><?php echo $key;?></h4>
           </div>
                  <div class="task-day-content">

                <?php
                   foreach ($value as $val)
                   {
                   ?>
                    <p>
                       <span><?php echo $val['subject'];?></span>
                       <span class="fr"><?php echo $val['startDate'];?>-<?php echo $val['endDate'];?></span>
                    </p>  
                   <?php
                   }
                   ?>
             </div>
        </div>
        </div>

  <?php
        }
  }
  ?>