<script src="<?= $this->static->frontend->js ;?>/indexCtrl.js"></script>
<!--Khu vực tìm kiếm-->
    <div ng-controller="searchCtrl" class="container clearfix">
      <div class="mbn-search clearfix hidden-xs" id="topSearch">
        <div class="container-top-seach row">
          <div class="col-md-3 col-sm-3 col-xs-3 top-search-location">
            <i id="mbn-top-search-city-icon" class="fa fa-map-marker fa-2x marker"></i>
            <input ng-model="cbTinhThanh" value="{{cbTinhThanh}}" class="hide" />                              
            <div class="chosen-container chosen-container-single chosen-container-single-nosearch chosen-container-active" style="width: 100%;" title="">
              <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-search" data-gtm-action="mbn-city-dropdown" class="chosen-single" tabindex="-1">
                <span class="drop-cat">                    
                  <span class="cat-name-tt">Toan quoc</span>
                </span>
                <div><span class="caret"></span></div>
              </a>
              <!-- chosen drop -->  
              <div class="chosen-drop">
                <div class="chosen-search">
                  <input type="text" autocomplete="off" readonly="">
                </div>
                <ul class="chosen-results">                    
                  <li ng-mouseenter="changeColor($event)" ng-mouseleave="changeColor($event)" ng-click="chosenTT(x)" class="active-result" style="font-weight: bold;" ng-repeat="x in tinhthanh" >{{x.name}}</li>                   
                </ul>
              </div>
              <!-- END chosen drop -->
            </div>      
          </div>
          <!-- col giua -->
          <div class="col-md-4 col-sm-4 col-xs-4 top-search-category">
            <input ng-model="cbDanhMuc" value="{{cbDanhMuc}}" class="hide" />
            <div class="chosen-container chosen-container-single chosen-container-single-nosearch" style="width: 100%;" title="">
              <a data-gtm-event="mbn-event-link" data-gtm-category="mbn-search" data-gtm-action="mbn-category-dropdown" class="chosen-single" tabindex="-1">
                <span class="drop-cat">
                    <span class="cat-icon"><i class="fa fa-th-large fa-2x" style="color:#ccc"></i></span>
                    <span class="cat-name cat-name-dm">Tất cả chuyên mục<span></span></span>
                  </span>
                <div><span class="caret"></span></div>
              </a>
              <!-- chosen drop -->  
              <div class="chosen-drop">
                <div class="chosen-search">
                  <input type="text" autocomplete="off" readonly="">
                </div>
                <ul class="chosen-results">                    
                  <li ng-mouseenter="changeColor($event)" ng-mouseleave="changeColor($event)" ng-click="chosenDM(x)" class="active-result" style="font-weight: bold;" ng-repeat="x in danhmuc" >{{x.name}}</li>                   
                </ul>
              </div>
              <!-- END chosen drop -->
            </div>      
          </div>
          <!-- col phai -->
          <div class="col-md-5 col-sm-5 col-xs-5 top-search-keyword">
            <div class="input-group">
              <input ng-model="txtSearch" name="txtSearch" id="txtSearch" type="text" class="form-control input-keyword" maxlength="50">
              <a class="input-group-addon btn-search" ng-click="search()" href="javascript:void();"> <i class="fa fa-search"></i> &nbsp;Tìm</a>
            </div>
          </div>
        </div>
      </div>
    </div>
<!--End Khu vực tìm kiếm-->

<!-- Banner top -->
    <div ng-controller="bannerCtrl" id="bannerTop" class="panel panel-banner container clearfix">
      <div class="panel-heading text-right">          
        <button id="closeBannerTop" type="button" class="close">&times;</button>
      </div>
      <div class="panel-body bodyBannerTop">
        <ul>
          <li ng-repeat="qc in bannertop">
            <a href="{{qc.url}}"><img class="img-thumbnail" src="<?= $this->static->frontend->banner; ?>{{qc.src}}" /></a>
          </li>            
        </ul>  
      </div>
    </div>
<!-- Banner top -->

<!-- tin VIP -->
      <div ng-controller="homeCtrl" ng-init="userId='<?= $this->arrLogin[account_id]; ?>'; upperTotals='<?= $this->arrLogin[upper_times]; ?>'" id="NewsVIP" class="panel panel-default">
        <div class="panel-heading text-center">
          <span>TIN ĐĂNG VIP</span>
        </div>
        <div class="panel-body bodyPanelVip">
          <div class="row rowNewsVip">
            <!-- start col left -->            
            <div class="col-md-6 col-sm-6 col-xs-12 vip-news-cell">
              <!-- start row 1 col left -->
              <div ng-repeat="item in leftItem" class="row vip-bottom">
                <!-- news col 1 -->
                <div class="col-md-2 col-sm-3 col-xs-3 vip-news-col-1">
                  <div class="vip-news-thumbs-image"> 
                    <div class="vip-news-thumbs-image-extra">                 
                      <a href="{{item.detailURL}}">
                        <img class="thumbnail" src="{{item.src}}" border="0" alt="{{item.tittle}}" title="{{item.tittle}}">
                      </a>
                    </div>  
                  </div>
                </div>
                <!-- end news col 1 -->
                <!-- news col 2 -->
                <div class="col-md-8 col-sm-6 col-xs-6 vip-news-col-2">
                  <div nowrap="nowrap" class="vip-thumbs-subject">
                    <h5><a itemprop="name" title="{{item.tittle}}" href="{{item.detailURL}}" class="ad-subject"> {{item.tittle}} </a><span class="fa fa-check-square"></span></h5>
                                        
                    <span class="vip-news-address">{{item.location}}</span>                    
                    <span class="vip-news-price">{{item.price}}</span>                    
                  </div>
                </div>  
                <!-- end col 2 -->
                <!-- news col 3 -->
                <div class="col-md-2 col-sm-3 col-xs-3 text-center">
                  <span class="vip-news-date">{{item.create_date}}</span>                  
                  <p ng-if="item.isOwner === 1 && upperTotals > 0">&nbsp; <span class="vip-news-number-up">({{upperTotals}})</span></p>
                  <span ng-if="item.isOwner === 1 && (item.upperToday === 0 || upperTotals > 0)"><a href="javascript:void" ng-click="upperNews(item)"><img src="<?= $this->static->frontend->images ?>/up_sm.png" /></a></span>
                </div>
              </div>
              <!-- End row 1 col left -->              
            </div>
            <!-- end col left -->

            <!-- start col right -->
            <div class="col-md-6 col-sm-6 col-xs-12 vip-news-cell">
              <!-- Start row 1 col right -->
              <div ng-repeat="item in rightItem" class="row vip-bottom">
                <!-- news col 1 -->
                <div class="col-md-2 col-sm-3 col-xs-3 vip-news-col-1">
                  <div class="vip-news-thumbs-image"> 
                    <div class="vip-news-thumbs-image-extra">                 
                      <a href="{{item.detailURL}}">
                        <img class="thumbnail" src="{{item.src}}" border="0" alt="{{item.tittle}}" title="{{item.tittle}}">
                      </a>
                    </div>  
                  </div>
                </div>
                <!-- end news col 1 -->
                <!-- news col 2 -->
                <div class="col-md-8 col-sm-6 col-xs-6 vip-news-col-2">
                  <div nowrap="nowrap" class="vip-thumbs-subject">
                    <h5><a itemprop="name" title="{{item.tittle}}" href="{{item.detailURL}}" class="ad-subject"> {{item.tittle}} </a><span class="fa fa-check-square"></span></h5>
                                        
                    <span class="vip-news-address">{{item.district + ", " + item.city}}</span>                    
                    <span class="vip-news-price">{{item.price}}</span>                    
                  </div>
                </div>  
                <!-- end col 2 -->
                <!-- news col 3 -->
                <div class="col-md-2 col-sm-3 col-xs-3 text-center">
                  <span class="vip-news-date">{{item.create_date}}</span>
                  <p ng-if="item.isOwner === 1 && upperTotals > 0">&nbsp; <span class="vip-news-number-up">({{upperTotals}})</span></p>
                  <span ng-if="item.isOwner === 1 && (item.upperToday === 0 || upperTotals > 0)"><a href="javascript:void" ng-click="upperNews(item)"><img src="<?= $this->static->frontend->images ?>/up_sm.png" /></a></span>
                </div>
              </div>
              <!-- End row 1 col right -->              
            </div>
            <!-- end col right -->            
          </div>
          <!-- end row 1 news vip -->
        </div>
      </div>  
<!-- End Tin VIP -->