 <section class="slide-wrapper">
     
     <?php
        if(!empty($this->arrProduct['data']))
        {
                $k=0;
               foreach($this->arrProduct['data'] as $value)
               {
                   
                     if($k==0)
                     {
                     ?>
     
                            <article class="first-child" style="background-image:url(<?php echo PATH_NEWS_URL .'/'. $value['image_url']; ?>);">
                                <a href="/product/detail/id/<?php echo $value['product_id'];?>">
                                    <span class="footer">
                                        <span class="name"><?php echo $value['name'];?></span>
                                        <span class="position"><?php echo strip_tags($value['content']);?></span>
                                    </span>
                                </a>
                            </article>
                     <?php
                     }else{
                        ?>
                            <article style="background-image:url(<?php echo PATH_NEWS_URL .'/'. $value['image_url']; ?>);">
                                <a href="/product/detail/id/<?php echo $value['product_id'];?>">
                                    <span class="footer">
                                        <span class="name"><?php echo $value['name'];?></span>
                                        <span class="position"><?php echo strip_tags($value['content']);?></span>
                                    </span>
                                </a>
                            </article>
     
        <?php
                     }
                 $k++;
               }
        }
        ?>
    
    
   
</section>
<script language=javascript">        
$('.slide-wrapper').bxSlider({
		slideWidth: 175,
		useCSS : false,
		minSlides: 9,
		maxSlides: 9,
		moveSlides: 0,
		slideMargin: 0,
		pager : false,
		infiniteLoop: false,
		hideControlOnEnd: true
	});
</script>